/**
 * Inlines `drizzle/*.sql` + the journal into `src/db/migrations.ts`, the shape
 * `drizzle-orm/expo-sqlite/migrator` expects. Metro cannot import `.sql` files, so this runs after
 * `drizzle-kit generate` (see the `db:generate` script) and the output is committed.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const out = path.join(root, 'drizzle');
const journal = JSON.parse(readFileSync(path.join(out, 'meta/_journal.json'), 'utf8')) as {
  entries: { idx: number; tag: string }[];
};
const migrations = journal.entries.map((e) => {
  const file = readdirSync(out).find((f) => f === `${e.tag}.sql`);
  if (!file) throw new Error(`missing ${e.tag}.sql`);
  return [`m${String(e.idx).padStart(4, '0')}`, readFileSync(path.join(out, file), 'utf8')];
});

const source = `// Generated by scripts/bundle-migrations.ts from drizzle/; do not edit.
export default {
  journal: ${JSON.stringify(journal, null, 2)},
  migrations: {
${migrations.map(([k, sql]) => `    ${k}: ${JSON.stringify(sql)},`).join('\n')}
  },
};
`;
writeFileSync(path.join(root, 'src/db/migrations.ts'), source);
console.log(`bundled ${migrations.length} migration(s) into src/db/migrations.ts`);
