#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — register the domain a Clerk production instance needs.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

DOMAIN="${DOMAIN:-mibokids.app}"
# Cloudflare's at-cost price for .app at the time of writing. Stage 3 compares
# what the page actually quotes against this, because a premium listing or a
# reseller page is the one way this purchase goes wrong quietly.
EXPECTED_PRICE="14.20"
SPEC="docs/spec/05-store-listing.md"

# The library opens the default browser, which here is Arc. Cloudflare is worked
# in Chrome, so try Chrome by name first and hand back to the library otherwise —
# a wrapper rather than a shadowing copy, matching setup-store-listing.sh.
open_url_chrome() {
  local url="$1"
  if command -v open >/dev/null 2>&1 &&
     open -a "Google Chrome" "$url" >/dev/null 2>&1; then
    printf '  %s↗ opening in Chrome%s %s\n' "$GREEN" "$RESET" "$url"
    return 0
  fi
  open_url "$url"
}

# fail "..." — a hard stop, in the library's red. Every exit in this wizard is a
# refusal to spend money on a wrong premise, so they should not read like notes.
fail() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }

# ns_of DOMAIN — the domain's nameservers, one per line, empty when unregistered.
ns_of() { dig +short NS "$1" 2>/dev/null | sed 's/\.$//' | sort; }

banner "Register $DOMAIN — the domain Clerk production needs"

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Preflight — is this still true?"
say "Three things have to hold before a browser is worth opening."
say ""

if ! command -v dig >/dev/null 2>&1; then
  fail "dig is not installed, and stage 5 verifies the purchase with it."
  note "  macOS: brew install bind        Debian/Ubuntu: apt install dnsutils"
  exit 1
fi
step "dig is present."

# The repo is the source of truth for which domain this is. A wizard that buys a
# name the spec no longer mentions is worse than no wizard.
if [[ -f "$SPEC" ]]; then
  if grep -q "$DOMAIN" "$SPEC"; then
    step "$SPEC still names $DOMAIN."
  else
    warn "$SPEC does not mention $DOMAIN."
    warn "The spec has moved without this script. Read it before buying anything."
    exit 1
  fi
else
  note "  $SPEC not found — run this from the repo root to check the spec."
fi

existing_ns=$(ns_of "$DOMAIN")
if [[ -n "$existing_ns" ]]; then
  warn "$DOMAIN already resolves to nameservers:"
  while IFS= read -r ns; do note "    $ns"; done <<< "$existing_ns"
  say ""
  if printf '%s' "$existing_ns" | grep -qi 'ns\.cloudflare\.com'; then
    say "Those are Cloudflare's, so this may already be yours. Skip to stage 6 —"
    say "or press Ctrl-C and run: clerk deploy"
  else
    fail "Someone else registered it. Pick another name before going further."
  fi
  exit 1
fi
step "$DOMAIN has no nameservers — still unregistered."
say ""
note "Buying it is the blocker for a Clerk production instance: the Frontend API"
note "lives at clerk.$DOMAIN, so there is no pk_live until this domain exists."
pause

# ── 2 ───────────────────────────────────────────────────────────────────
stage "Cloudflare — an account with a verified email"
say "Cloudflare refuses to register a domain to an account whose email address"
say "has not been verified. It is the single most common way this stalls, so it"
say "gets checked before the purchase rather than discovered inside it."
open_url_chrome "https://dash.cloudflare.com/profile"
say ""
step "Sign in if you are not already."
step "On Profile, look for a 'Verify email' prompt. If one is there, clear it now —"
step "Cloudflare sends a link; click it and come back."
say ""
note "Any plan works. Registrar is at-cost on the free plan; nothing here needs Pro."
if ! confirm "Is your account email verified?"; then
  fail "Stopping here. Verify the email, then re-run this script."
  exit 1
fi
pause

# ── 3 ───────────────────────────────────────────────────────────────────
stage "Search for $DOMAIN, and read the price it quotes"
say "Cloudflare sells at wholesale: you pay the registry price with no markup."
open_url_chrome "https://dash.cloudflare.com/?to=/:account/domains/register"
say ""
step "Domain Registration → Register domains."
step "Search for the name without the suffix:"
note "    ${DOMAIN%%.*}"
step "Find the .${DOMAIN#*.} result in the list."
say ""
warn "If it now shows as taken, stop — stage 1 said otherwise minutes ago, and"
warn "something is wrong with either the search or the name."
say ""
ask PRICE_SHOWN "What yearly price does Cloudflare quote? (numbers only, e.g. 14.20)"

# A premium or reseller listing is the quiet failure here: the page still looks
# like a normal purchase, and the difference only shows in the number.
price_int=${PRICE_SHOWN%%.*}
if [[ "$price_int" =~ ^[0-9]+$ ]] && (( price_int > 30 )); then
  warn "That is well above the ~\$$EXPECTED_PRICE at-cost price for this TLD."
  warn "Likely a premium registry listing. Cloudflare passes those through at the"
  warn "registry's price, and it is not refundable."
  if ! confirm "Do you still want to buy it at \$$PRICE_SHOWN/year?"; then
    fail "Stopping. Nothing has been paid."
    exit 1
  fi
else
  step "\$$PRICE_SHOWN is in the expected range (~\$$EXPECTED_PRICE at cost)."
fi
pause

# ── 4 ───────────────────────────────────────────────────────────────────
stage "Buy it"
say "Registration term: one year. Cloudflare charges the same per year whatever"
say "the term, so a longer one buys no discount — only insulation from forgetting"
say "to renew, which auto-renew already covers."
say ""
step "Term: 1 year. Leave auto-renew on."
step "Contact details — ASCII only. Cloudflare rejects non-Latin characters, so"
step "no Hebrew in the registrant, admin, technical or billing fields."
step "WHOIS privacy is included and on by default. Nothing to add."
say ""
warn "Two things about this purchase are not reversible:"
note "  - The registration itself. Domains are not refundable."
note "  - Nameservers. A domain registered at Cloudflare must use Cloudflare DNS"
note "    for as long as it stays there. That suits Clerk and Railway, but moving"
note "    DNS elsewhere later means transferring the domain to another registrar."
say ""
if ! confirm "Ready to complete the purchase?"; then
  fail "Stopping. Nothing has been paid; re-run when you are ready."
  exit 1
fi
say ""
step "Complete the checkout in Chrome now."
pause "Press Enter once Cloudflare says the domain is registered."

# ── 5 ───────────────────────────────────────────────────────────────────
stage "Verify it is genuinely yours"
say "A dashboard that says 'success' and a resolver that has never heard of the"
say "domain are different facts. Clerk needs the second one — it cannot issue a"
say "certificate for clerk.$DOMAIN against a dashboard."
say ""
say "Polling public DNS for $DOMAIN's nameservers."

# Registration is usually visible in seconds; the timeout is generous because the
# alternative — declaring success early — sends the human to `clerk deploy` with
# a domain that resolves nowhere.
deadline=$((SECONDS + 300))
found=""
while (( SECONDS < deadline )); do
  found=$(ns_of "$DOMAIN")
  [[ -n "$found" ]] && break
  printf '  %s· no nameservers yet, %ss left%s\r' \
    "$DIM" "$((deadline - SECONDS))" "$RESET"
  sleep 10
done
printf '\033[2K'

if [[ -z "$found" ]]; then
  warn "Still nothing after five minutes."
  note "That is not necessarily a failed purchase — registry propagation can lag."
  note "Check it yourself with:  dig +short NS $DOMAIN"
  note "Then continue with:      clerk deploy"
  SKIPPED+=("confirming $DOMAIN resolves — dig +short NS $DOMAIN")
else
  step "$DOMAIN now answers with:"
  while IFS= read -r ns; do note "    $ns"; done <<< "$found"
  if printf '%s' "$found" | grep -qi 'ns\.cloudflare\.com'; then
    step "Cloudflare nameservers, as expected — DNS is yours to edit."
  else
    warn "Those are not Cloudflare nameservers. Registered elsewhere?"
    SKIPPED+=("checking why $DOMAIN is not on Cloudflare nameservers")
  fi
fi
pause

# ── 6 ───────────────────────────────────────────────────────────────────
stage "What this unblocks"
say "The domain is the prerequisite, not the goal. Three things were waiting on it."
say ""
step "1. Clerk production. It is interactive and needs your terminal, so run it"
step "   yourself rather than from a script:"
note "       clerk deploy"
note "       clerk deploy status      # until it reports complete"
note "   It will hand you CNAME records for clerk.$DOMAIN to add in Cloudflare."
say ""
step "2. The production build's keys. Today both the preview and production"
step "   profiles in apps/mobile/eas.json carry a pk_test_ development key, and"
step "   the API runs sk_test_. Those become pk_live_ / sk_live_ once Clerk"
step "   production exists — mobile profiles plus the Railway environment."
say ""
step "3. The store URLs. App Store Connect currently points App Review at"
step "   api-production-c5c7.up.railway.app/privacy. The decision on record is to"
step "   move the privacy and support URLs to $DOMAIN before submitting, which"
step "   means pointing $DOMAIN at the API and re-saving both fields in ASC."
say ""
note "None of the three belong in this wizard: two need credentials that do not"
note "exist yet, and the third changes a record App Review reads."

finish
note "Registered $DOMAIN at \$${PRICE_SHOWN:-?}/year. Next: clerk deploy"
printf '\n'
