#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

API_ENV="$ROOT/apps/api/.env"
MOBILE_ENV="$ROOT/apps/mobile/.env"

# clerk_cli — the Clerk CLI, installed globally if present, else via npx.
clerk_cli() {
  if command -v clerk >/dev/null 2>&1; then clerk "$@"; else npx -y clerk@latest "$@"; fi
}

banner "Mibo — Clerk setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the things this wizard needs before it touches Clerk."
[[ -f "$ROOT/pnpm-workspace.yaml" ]] || { warn "not the chores repo root ($ROOT)"; exit 1; }
note "repo root: $ROOT"

if command -v clerk >/dev/null 2>&1; then
  note "clerk CLI: $(clerk -v 2>/dev/null || echo installed)"
else
  warn "clerk CLI not installed globally — every step will run it through npx (slower)."
  say "Install it once for a faster run:  brew install clerk/stable/clerk"
  confirm "Continue with npx?" || exit 1
fi

if docker ps --filter name=chores-pg --format '{{.Names}}' 2>/dev/null | grep -q chores-pg; then
  note "postgres: chores-pg is up on :5499"
else
  warn "the chores-pg container is not running — the API will fail to migrate on boot."
  say "Start it with:"
  say "  docker run -d --name chores-pg -p 5499:5432 -e POSTGRES_PASSWORD=postgres \\"
  say "    -e POSTGRES_DB=chores postgres:17-alpine"
  SKIPPED+=("start the chores-pg Postgres container")
fi
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Sign in to Clerk"
say "The CLI signs in through your browser. A tab will open — approve it there,"
say "then come back here."
if clerk_cli whoami >/dev/null 2>&1; then
  note "already signed in as: $(clerk_cli whoami 2>/dev/null | head -n3 | tr '\n' ' ')"
  confirm "Sign in as a different account?" && clerk_cli auth login
else
  clerk_cli auth login
fi
pause "Press Enter once the CLI says you're signed in"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The Clerk application"
say "Mibo needs one Clerk application. Its development instance is what you'll"
say "use on the emulator and both kids' devices until the store release."
if confirm "Create a NEW Clerk application called 'Mibo'? (No = link an existing one)"; then
  clerk_cli apps create "Mibo" || warn "create failed — falling back to linking an existing app"
  clerk_cli link || true
else
  say "Pick the app from the list the CLI shows."
  clerk_cli link
fi
note "linked app:"
clerk_cli whoami 2>/dev/null || true
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Pull the API keys"
say "Pulling this app's development keys, then writing them where each workspace"
say "expects them — the secret key never leaves apps/api/.env."
PULLED="$(mktemp)"
trap 'rm -f "$PULLED"' EXIT
PK=""; SK=""
if clerk_cli env pull --instance dev --file "$PULLED" >/dev/null 2>&1; then
  PK=$(grep -hoE 'pk_(test|live)_[A-Za-z0-9._$-]+' "$PULLED" | head -n1 || true)
  SK=$(grep -hoE 'sk_(test|live)_[A-Za-z0-9._$-]+' "$PULLED" | head -n1 || true)
fi
rm -f "$PULLED"

if [[ -n "$PK" && -n "$SK" ]]; then
  note "pulled a publishable key and a secret key from Clerk"
else
  warn "couldn't pull the keys automatically — copy them from the dashboard instead."
  clerk_cli open dashboard >/dev/null 2>&1 || open_url "https://dashboard.clerk.com"
  step "Open the API keys page for this application (sidebar: Configure → API keys)."
  step "Copy the Publishable key (starts pk_test_)."
  ask CLERK_PK "Paste the publishable key:"
  PK="$CLERK_PK"
  step "Reveal and copy the Secret key (starts sk_test_)."
  ask_secret CLERK_SK "Paste the secret key:"
  SK="$CLERK_SK"
fi

# apps/api/.env — the server half.
ENV_FILE="$API_ENV"
ask DATABASE_URL "Postgres URL for local dev [Enter for the docker default]:"
DATABASE_URL="${DATABASE_URL:-postgres://postgres:postgres@localhost:5499/chores}"
write_env DATABASE_URL "$DATABASE_URL"
write_env PORT "3000"
write_env CLERK_SECRET_KEY "$SK"

# apps/mobile/.env — the device half. A phone can't reach the API on localhost,
# so this is the machine's LAN address (the emulator alias 10.0.2.2 also works).
LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || true)"
[[ -z "$LAN_IP" ]] && LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
[[ -z "$LAN_IP" ]] && LAN_IP="10.0.2.2"
ENV_FILE="$MOBILE_ENV"
say "The device reaches the API over the network, not localhost."
ask API_HOST "API host the device should call [Enter for $LAN_IP]:"
API_HOST="${API_HOST:-$LAN_IP}"
write_env EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY "$PK"
write_env EXPO_PUBLIC_API_URL "http://$API_HOST:3000"
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Teach the dev server to read apps/api/.env"
say "apps/api boots with 'tsx watch src/index.ts', and nothing in the repo loads"
say "a .env file — so the keys you just saved would still be invisible to it."
say "tsx passes --env-file straight through to Node, which fixes it with no new"
say "dependency. Railway is unaffected: it runs 'start' with real env vars."
DEV_SCRIPT_OK=""
grep -q -- '--env-file' "$ROOT/apps/api/package.json" && DEV_SCRIPT_OK=yes
if [[ -n "$DEV_SCRIPT_OK" ]]; then
  note "apps/api/package.json already passes --env-file — nothing to do"
else
  say ""
  say "  before:  \"dev\": \"tsx watch src/index.ts\""
  say "  after:   \"dev\": \"tsx watch --env-file=.env src/index.ts\""
  say ""
  if confirm "Apply that one-line change to apps/api/package.json?"; then
    tmp=$(mktemp)
    sed 's|"dev": "tsx watch src/index.ts"|"dev": "tsx watch --env-file=.env src/index.ts"|' \
      "$ROOT/apps/api/package.json" > "$tmp"
    if grep -q -- '--env-file' "$tmp"; then
      mv "$tmp" "$ROOT/apps/api/package.json"
      printf '  %s\u2713 patched%s apps/api/package.json dev script\n' "$GREEN" "$RESET"
    else
      rm -f "$tmp"
      warn "the dev script didn't match the expected text — patch it by hand"
      SKIPPED+=("add --env-file=.env to the dev script in apps/api/package.json")
    fi
  else
    SKIPPED+=("add --env-file=.env to the dev script in apps/api/package.json")
  fi
fi
pause "Press Enter to continue"

# ── 6 ───────────────────────────────────────────────────────────────────
stage "Sign-in method — email code"
say "The parent sign-in screen calls signIn.emailCode, so the instance must offer"
say "email address as an identifier with email-code verification."
CFG="$(mktemp)"
clerk_cli config pull --instance dev > "$CFG" 2>/dev/null || true
if grep -q 'email_code' "$CFG" 2>/dev/null; then
  note "the instance config mentions email_code — looks enabled"
else
  warn "couldn't confirm email-code sign-in from the config — set it by hand."
  clerk_cli open dashboard >/dev/null 2>&1 || open_url "https://dashboard.clerk.com"
  step "Sidebar: Configure → Email, phone, username (search the sidebar if the layout differs)."
  step "Turn Email address ON as an identifier."
  step "Set its verification method to Email verification code (not a magic link)."
  pause "Press Enter once email-code sign-in is on"
fi
rm -f "$CFG"

# ── 7 ───────────────────────────────────────────────────────────────────
stage "Sign-in method — Google"
say "The same screen offers 'Continue with Google' via startSSOFlow({ strategy:"
say "'oauth_google' }). That needs the Google social connection switched on."
CFG="$(mktemp)"
clerk_cli config pull --instance dev > "$CFG" 2>/dev/null || true
if grep -q '"google"' "$CFG" 2>/dev/null; then
  note "the instance config mentions google — looks enabled"
else
  warn "couldn't confirm the Google connection from the config — set it by hand."
  clerk_cli open dashboard >/dev/null 2>&1 || open_url "https://dashboard.clerk.com"
  step "Sidebar: Configure → SSO connections."
  step "Add connection → For all users → Google."
  step "On a development instance, leave Clerk's shared credentials on — your own"
  step "  Google OAuth client is only required for production."
  pause "Press Enter once Google is on"
fi
rm -f "$CFG"

# ── 8 ───────────────────────────────────────────────────────────────────
stage "Redirect URL for the native app"
say "After Google sign-in the browser hands control back to the app through the"
say "'mibo' scheme (app.json). Clerk only redirects to URLs on its allowlist, so"
say "an unregistered scheme leaves the parent stuck in the browser tab."
clerk_cli open dashboard >/dev/null 2>&1 || open_url "https://dashboard.clerk.com"
step "Find the Redirect URLs / allowlist for this instance in the dashboard."
step "Add:  mibo://parent"
step "Add:  mibo://          (the bare scheme, for anything else that redirects)"
warn "Google sign-in cannot work in Expo Go — it needs the dev client build."
pause "Press Enter once both URLs are registered"

# ── 9 ───────────────────────────────────────────────────────────────────
stage "Hook Clerk up to the agents"
say "Two separate things: the MCP server (live Clerk SDK snippets) and the Clerk"
say "skills (Expo, backend API, and CLI know-how for this stack)."
if confirm "Register the Clerk MCP server in Claude Code?"; then
  clerk_cli mcp install --client claude || warn "mcp install failed — run 'clerk mcp install' by hand"
  note "verify inside Claude Code with /mcp"
else
  SKIPPED+=("clerk mcp install --client claude")
fi
if confirm "Install the clerk-expo, clerk-backend-api and clerk-cli skills?"; then
  npx -y skills add clerk/skills --skill clerk-expo || warn "clerk-expo skill failed"
  npx -y skills add clerk/skills --skill clerk-backend-api || warn "clerk-backend-api skill failed"
  npx -y skills add clerk/skills --skill clerk-cli || warn "clerk-cli skill failed"
else
  SKIPPED+=("npx skills add clerk/skills --skill clerk-expo (and clerk-backend-api, clerk-cli)")
fi
pause "Press Enter to continue"

# ── 10 ──────────────────────────────────────────────────────────────────
stage "Verify"
say "Starting the API alone to prove the keys and the database are good."
clerk_cli doctor || true
say ""
say "Booting apps/api in the background…"
# One process, not 'pnpm dev' — a watcher behind pnpm would survive the kill
# below and keep port 3000 busy for the real run.
( cd "$ROOT/apps/api" && "$ROOT/node_modules/.bin/tsx" --env-file=.env src/index.ts ) \
  >/tmp/mibo-api-boot.log 2>&1 &
API_PID=$!
HEALTHY=""
for _ in $(seq 1 30); do
  if curl -fsS http://localhost:3000/health >/dev/null 2>&1; then HEALTHY=yes; break; fi
  sleep 1
done
kill "$API_PID" >/dev/null 2>&1 || true
if [[ -n "$HEALTHY" ]]; then
  note "GET /health answered — DATABASE_URL, CLERK_SECRET_KEY and the migrations are all good"
else
  warn "the API never answered on :3000 — last lines of its log:"
  tail -n 15 /tmp/mibo-api-boot.log 2>/dev/null | sed 's/^/    /'
  SKIPPED+=("get the API booting (see /tmp/mibo-api-boot.log)")
fi
say ""
say "Now run the real thing:  pnpm dev"
say "Then sign in as a parent in the app — email code first, then Google."
pause "Press Enter to finish"

finish
