#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES — the four device hand-tests still unchecked on issue #75.
#
# Lifted out of setup-premium.sh stages 12-15 so they can be run on their own:
# the configuration stages they used to sit behind are all done, and nobody
# should re-walk eleven dashboard stages to record a device result.
#
# Everything here is a human with a phone. The script only asks and records,
# then offers to post the results to #75.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

BROWSER_APP="${BROWSER_APP:-Google Chrome}"
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s %s(%s)%s\n' "$GREEN" "$RESET" "$url" "$DIM" "$BROWSER_APP" "$RESET"
  if [[ "$OSTYPE" == darwin* ]] && open -a "$BROWSER_APP" "$url" >/dev/null 2>&1; then
    return
  fi
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser - visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser - visit it manually: $url"
}

ISSUE=75
SANDBOX_TESTER="donkeypoker2024@gmail.com"
PARTNER_TESTER="donkeypoker2024+partner@gmail.com"
RESULTS=()

# ask_plain KEY "Prompt" — ask with no ENV_FILE default behind it. What this
# wizard asks for are per-run facts about a test household, not configuration
# worth remembering.
ask_plain() {
  local key="$1" input
  printf '  %s%s%s ' "$BOLD" "$2" "$RESET"
  read -r input || true
  printf -v "$key" '%s' "$input"
}

# backdate_grace — the child quota is not reachable by adding a child, which is
# what this wizard used to ask for and nobody could ever see. On the free tier
# `add_child` never refuses: the second child is admitted and stamped with a
# `read_only_after` fourteen days out (packages/shared/src/entitlement.ts,
# docs/spec/01-product.md), and the price appears when that date passes, on the
# child's own edit screen. So the only way to reach it today is to move the
# date into the past.
#
# It runs against the live Railway Postgres because the device points at
# https://mibokids.app — the one API the RevenueCat webhook writes into. It
# touches only rows that already carry a non-null `read_only_after`, which is
# to say over-quota children and nothing else.
#
# It updates exactly one row, named by the id the listing printed, and never by
# anything typed free-hand. That is deliberate twice over: this is the live
# production database, where a first name is not unique and a household you
# have never met has children called what yours are called — matching on a name
# would end a real customer's grace and lock them out of their own child. And
# an id checked against [0-9a-f-] cannot carry SQL or shell syntax through the
# two quoting layers between here and psql.
_skip_backdate() {
  warn "$1"
  SKIPPED+=("backdating read_only_after for the child-quota check")
  return 1
}

# The listing takes no input at all; the update takes one validated id.
BACKDATE_LIST_SQL="select id, household_id, first_name, read_only_after from children where read_only_after is not null order by read_only_after desc;"

# `railway run` injects the api service's own variables, and DATABASE_URL among
# them points at postgres.railway.internal — a name that resolves inside
# Railway's private network and nowhere else. From a laptop it fails with
# "could not translate host name". DATABASE_PUBLIC_URL is the proxy address
# that does resolve, so prefer it and keep DATABASE_URL as the fallback for
# anywhere this runs inside Railway.
_psql() {
  railway run --service api -- sh -c "psql \"\${DATABASE_PUBLIC_URL:-\$DATABASE_URL}\" -c \"$1\""
}

backdate_grace() {
  local child_id="" sql_update

  if ! command -v railway >/dev/null 2>&1 || ! command -v psql >/dev/null 2>&1; then
    _skip_backdate "railway or psql missing — end the grace by hand on the api database"
    return 1
  fi

  say "Children currently inside a grace window, newest first:"
  if ! _psql "$BACKDATE_LIST_SQL"; then
    warn "If that said it could not translate 'postgres.railway.internal', the"
    warn "service has no DATABASE_PUBLIC_URL — open a shell with 'railway"
    warn "connect Postgres' and run these there instead:"
    note "  $BACKDATE_LIST_SQL"
    note "  update children set read_only_after = now() - interval '1 day' where id = '<the id of your second child>';"
    _skip_backdate "could not reach the database — check 'railway link' first"
    return 1
  fi

  ask_plain child_id "Paste the id of YOUR second child from that list (Enter to skip):"
  if [[ -z "$child_id" ]]; then
    _skip_backdate "no id given — skipping the backdate"
    return 1
  fi
  if [[ ! "$child_id" =~ ^[0-9a-fA-F-]{36}$ ]]; then
    _skip_backdate "'$child_id' is not a child id — copy one from the list above"
    return 1
  fi
  warn "This is the production database. Check that id is yours before saying yes."
  if ! confirm "End the grace on child $child_id?"; then
    _skip_backdate "not confirmed — grace left alone"
    return 1
  fi

  sql_update="update children set read_only_after = now() - interval '1 day' where read_only_after is not null and id = '$child_id';"
  if ! _psql "$sql_update"; then
    _skip_backdate "the update failed — the grace has NOT ended, so the next check would lie"
    return 1
  fi
  printf '  %s✓ grace ended%s — now quit and reopen Mibo on the device\n' "$GREEN" "$RESET"
}

# check "M3.x" "what the tester should see" — record pass/fail for the comment.
check() {
  local label="$1" expectation="$2" reply=""
  step "$expectation"
  printf '  %s? %s — did that happen? [y/n/Enter = not yet]%s ' "$YELLOW" "$label" "$RESET"
  read -r reply || true
  case "$reply" in
    [Yy]*)
      RESULTS+=("- [x] $label — $expectation")
      printf '  %s✓ recorded as passing%s\n' "$GREEN" "$RESET" ;;
    [Nn]*)
      RESULTS+=("- [ ] $label — FAILED: $expectation")
      printf '  %s✗ recorded as failing%s\n' "$RED" "$RESET" ;;
    *)
      RESULTS+=("- [ ] $label — not yet run: $expectation")
      printf '  %s· recorded as not yet run%s\n' "$DIM" "$RESET" ;;
  esac
}

banner "Mibo — the four device hand-tests left on #75"

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Before you start"
say "You need the iPhone with the dev client, Metro running (pnpm dev), and"
say "Wi-Fi ON — not just the USB cable."
say ""
warn "A phone with Wi-Fi off still bundles from Metro over USB and then hangs"
warn "on a spinner forever, because every remote call sits unsatisfied with"
warn "'No network route'. Check Safari loads a page before blaming the app."
say ""
note "Sandbox testers already created:"
note "  buyer:   $SANDBOX_TESTER"
note "  partner: $PARTNER_TESTER"
note "Sandbox compresses a month to five minutes and renews six times, so a"
note "subscription bought now is gone in about half an hour. That is a feature"
note "for the expiry test and a nuisance for the others — do the tests that"
note "need premium while it is live."
pause "Ready?"

# ── 2 ───────────────────────────────────────────────────────────────────
stage "M3.4 — restore and partner"
say "The purchase half is already verified (transaction 2000001239633691)."
say "These two clauses are what is still open."
say ""
check "M3.4 restore on reinstall" "Delete Mibo, reinstall the dev client, sign in as the same parent, tap Restore Purchases → premium returns with no local state."
say ""
note "The point is that entitlement comes from the server, not from anything"
note "the deleted app was keeping. If it only works because a local cache"
note "survived, it has not passed."
say ""
check "M3.4 partner sees premium" "Sign in as the SECOND parent, who bought nothing. The household reads premium for them too."
note "This is ADR-0016 in practice: the webhook writes households.entitlement,"
note "so entitlement belongs to the household and not to the buyer's device."
pause

# ── 3 ───────────────────────────────────────────────────────────────────
stage "M3.12 — photo proof"
say "Needs a chore with photo proof required, on a premium household."
say ""
check "M3.12 camera opens" "Tapping done on a photo-proof chore opens the camera from the done moment — not a separate upload screen later."
check "M3.12 waiting copy" "After the snap the card reads as waiting for a parent, not as complete. The child should not think they are finished."
check "M3.12 offline upload" "Put the phone in airplane mode, snap the proof: it is accepted locally. Turn the network back on → it uploads without being asked."
note "Airplane mode is the honest test. Do not just background the app."
pause

# ── 4 ───────────────────────────────────────────────────────────────────
stage "M3.8 — allowance screen and Hebrew RTL"
check "M3.8 allowance screen" "The allowance screen renders correctly on the device — not only in the simulator."
say ""
say "Then: Settings → General → Language & Region → iPhone Language → עברית."
say "The device restarts into Hebrew. Reopen Mibo."
check "M3.8 Hebrew RTL" "The screen mirrors properly — no clipped text, no reversed numbers, currency on the correct side."
warn "Numbers are the usual failure: they stay left-to-right inside mirrored"
warn "text, and a naive flip reverses them. Read an actual balance to check."
note "Remember to set the language back afterwards."
pause

# ── 5 ───────────────────────────────────────────────────────────────────
stage "The M3 exit criterion — one pass, end to end"
say "A single run on a FREE household. Not six separate checks on whatever"
say "state the phone happens to be in — that is what makes it an exit"
say "criterion rather than a checklist."
say ""
warn "The household you have been testing on is premium now. Either use a"
warn "fresh one, or wait out the sandbox expiry (~30 minutes from purchase),"
warn "which re-locks it through the same webhook path #62 covers."
say ""
say "The child quota does not fire when you add the child. Adding the second"
say "child succeeds — it is admitted under a 14-day grace — and the price only"
say "appears once that grace has ended, on that child's own edit screen."
say ""
step "Add a second child to the free household. It will be accepted; that is correct."
backdate_grace || true   # skipping it is a choice, not a failure; set -e must not end the run here
say ""
note "Quit, not background. The household — and with it read_only_after — is"
note "fetched when the provider mounts and after a write, and there is no"
note "pull-to-refresh, so a backgrounded app keeps showing the old grace."
check "quota shows a price" "Fully quit and reopen Mibo, then open that second child to edit them: the screen is locked and offers a price instead."
note "Only that child's own row is locked. A shared chore stays editable —"
note "that is the narrow scope canDo() gives edit_child, and a chore that has"
note "become uneditable is a failure, not a pass."
note "The backdated date is left as it is. It needs no undo: the purchase two"
note "checks down flips the household to premium, and canDo() lets premium do"
note "everything without ever reading read_only_after."
say ""
check "webhook flips entitlement" "A sandbox purchase flips the household to premium via the webhook — not via anything the client wrote."
check "custom reward" "A custom reward can be added and redeemed."
check "payout drops coins" "A payout is recorded and the child's coins drop. Balance is SUM(coins), so it must drop by the redemption, not be overwritten."
check "history past 7 days" "The grid scrolls past 7 days."
check "photo chore pays" "A photo chore is completed, approved, and pays."
pause

# ── 6 ───────────────────────────────────────────────────────────────────
stage "Report back to issue #$ISSUE"
say "Posting the hand-test results as a comment."
if (( ${#RESULTS[@]} == 0 )); then
  warn "No hand-test results recorded — nothing to report."
  SKIPPED+=("the hand-test comment on issue #$ISSUE")
  finish
  exit 0
fi
comment=$(printf '## Hand-test results\n\nRun via `scripts/device-hand-tests.sh` on %s.\n\n%s\n' \
  "$(date -u '+%Y-%m-%d %H:%M UTC')" "$(printf '%s\n' "${RESULTS[@]}")")
printf '\n%s\n\n' "$comment"
if confirm "Post this to issue #$ISSUE?"; then
  if printf '%s' "$comment" | gh issue comment "$ISSUE" --body-file - >/dev/null 2>&1; then
    printf '  %s✓ posted%s to issue #%s\n' "$GREEN" "$RESET" "$ISSUE"
  else
    warn "gh could not post — copy the comment above onto the issue by hand."
    SKIPPED+=("the hand-test comment on issue #$ISSUE")
  fi
else
  SKIPPED+=("the hand-test comment on issue #$ISSUE")
fi
pause

finish
note "Every box that came back green can be ticked on #75. When all four"
note "sections are green the issue closes and M3 is complete."
printf '\n'
