#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — M4.7 the production iOS build and the TestFlight release (issue #83).
#
# The last stage of M4, and the one that cannot be re-run cheaply: a store build
# takes twenty to forty minutes on EAS and every mistake in it is found at the end.
# So the first stage is longer than the rest and refuses to move until the things
# that kill a build twenty minutes in are checked — the Sentry credentials above
# all, which live in an EAS environment and not in this repo.
#
# Nothing here writes to the app's code. It writes one value to `eas.json` (stage 3)
# and otherwise drives `eas`, App Store Connect and a physical device.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

# The library opens the default browser, which here is Arc. App Store Connect and
# expo.dev are worked in Chrome, so try Chrome by name and hand back to the library.
BROWSER_APP="${BROWSER_APP:-Google Chrome}"
open_url_chrome() {
  local url="$1"
  if [[ "$OSTYPE" == darwin* ]] && open -a "$BROWSER_APP" "$url" >/dev/null 2>&1; then
    printf '  %s↗ opening%s %s %s(%s)%s\n' "$GREEN" "$RESET" "$url" "$DIM" "$BROWSER_APP" "$RESET"
    return
  fi
  open_url "$url"
}

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
MOBILE="$REPO_ROOT/apps/mobile"
EAS_JSON="$MOBILE/eas.json"
APP_JSON="$MOBILE/app.json"
API_BASE="${API_BASE:-https://mibokids.app}"
BUNDLE_ID="com.mibokids.app"
PROFILE="production"
CHANNEL="production"
# The EAS environment the store build reads its variables from. The same string as
# the profile and the channel, and a different thing from both: EAS derives a build's
# environment from the profile's shape rather than its name, and the profile names
# this one explicitly since #78. Spelled separately so that the day the store profile
# reads a differently-named environment, the check below moves with it.
ENVIRONMENT="production"
ISSUE=83

# The production Clerk instance, named literally — the CLI otherwise picks one for
# you, and #85 exists partly because a wizard did that and configured development
# while production sat unconfigured behind a store build. The redirect is the URL
# the app actually asks for, built by makeRedirectUri({ scheme: 'mibo', path:
# 'sso-callback' }) in src/components/parent-sign-in.tsx — and the only one checked
# below: `mibo://` and `mibo://parent` are also registered and are historical, so
# asserting them would fail a healthy instance for URLs nothing redirects to.
PROD_CLERK_INSTANCE="${PROD_CLERK_INSTANCE:-ins_3Ju3HWvao1YJ00AczgcGiG8Q9aI}"
APP_REDIRECT_URL="mibo://sso-callback"

# The four EAS environment variables a store build needs, and what each one is for.
SENTRY_VARS=(SENTRY_ORG SENTRY_PROJECT SENTRY_AUTH_TOKEN EXPO_PUBLIC_SENTRY_DSN)

# Device and section verification, reported to issue #83 by the last stage.
RESULTS=()
preflight_ok=1

# eas_mobile ARGS... — run the EAS CLI in apps/mobile, where the app config is.
# A subshell rather than a `cd`, so a failing stage does not leave the wizard in
# another directory for the stages after it.
eas_mobile() { (cd "$MOBILE" && eas "$@"); }

# clerk_cli ARGS... — the Clerk CLI, global if installed, else through npx. Not a
# `have` entry: check 8 is the only caller, and it degrades to a warning rather
# than blocking a release on a CLI nobody needs installed to build an app.
clerk_cli() {
  if command -v clerk >/dev/null 2>&1; then clerk "$@"; else npx -y clerk@latest "$@"; fi
}

# have TOOL "why it matters" — report a tool's presence, and record what breaks
# without it. A reporter rather than a predicate: a missing tool is already in
# SKIPPED and has already cleared preflight_ok by the time this returns, so there is
# nothing for a caller to branch on and no call site needs `|| true` to survive
# `set -e`.
have() {
  local tool="$1" why="$2"
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$tool"
    return 0
  fi
  printf '  %s✗%s %s — %s\n' "$RED" "$RESET" "$tool" "$why"
  SKIPPED+=("install $tool — $why")
  preflight_ok=0
  return 0
}

# strip_ansi — drop SGR colour codes from captured output. The EAS CLI colours its
# output even when stdout is not a terminal, so `eas env:list` hands back each name
# as ESC[1mNAME ESC[22m=value and a `grep "^NAME="` against it never matches — the
# check then reports every variable missing however well the environment is set up.
# Both preflight checks that read that output anchor on line starts, so both need it.
strip_ansi() { sed $'s/\x1b\[[0-9;]*m//g'; }

# url_serves URL "marker" — is this URL live and serving the page we mean? Captured
# whole rather than piped into grep -q: under `set -o pipefail` a reader that closes
# on the first match kills curl with SIGPIPE, and a live page reads as a dead one.
url_serves() {
  local url="$1" marker="$2" body=""
  if body=$(curl -fsS --max-time 15 "$url" 2>/dev/null) && [[ "$body" == *"$marker"* ]]; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$url"
    return 0
  fi
  printf '  %s✗%s %s does not serve the page App Review expects\n' "$RED" "$RESET" "$url"
  return 1
}

# manifest_serves RUNTIME — does the updates server offer an update to a client
# claiming to be this binary? The three ways criterion 4 fails are all server-side
# and all invisible on the device: an update group published against the wrong
# channel, against a runtime the binary does not have, or for Android only. Each
# one leaves the app launching its embedded bundle forever, which looks exactly
# like an app that is up to date. So this asks u.expo.dev the question the app asks
# on launch, and reads the update id back out of the response headers.
#
# `-D -` puts the headers on stdout ahead of the multipart body so the whole reply
# is captured in one pass and matched in bash — same reason as url_serves, and here
# the body is a multipart blob nobody wants to parse in shell.
manifest_serves() {
  local runtime="$1" url="" reply="" id=""
  url=$(jq -r '.expo.updates.url // empty' "$APP_JSON" 2>/dev/null) || url=""
  if [[ -z "$url" ]]; then
    printf '  %s✗%s app.json names no updates.url, so there is no endpoint to ask\n' \
      "$RED" "$RESET"
    return 1
  fi
  if ! reply=$(curl -fsS -D - --max-time 20 "$url" \
      -H 'expo-platform: ios' \
      -H "expo-runtime-version: $runtime" \
      -H "expo-channel-name: $CHANNEL" \
      -H 'expo-protocol-version: 1' \
      -H 'expo-api-version: 1' \
      -H 'accept: multipart/mixed' 2>/dev/null); then
    printf '  %s✗%s the updates server served no manifest for ios on runtime %s\n' \
      "$RED" "$RESET" "$runtime"
    return 1
  fi
  id=$(printf '%s' "$reply" | tr -d '\r' | sed -n 's/^expo-update-id: *//p' | head -1)
  if [[ -z "$id" ]]; then
    printf '  %s✗%s a reply carrying no expo-update-id — nothing is published for runtime %s\n' \
      "$RED" "$RESET" "$runtime"
    return 1
  fi
  printf '  %s✓%s ios / runtime %s / channel %s → update %s\n' \
    "$GREEN" "$RESET" "$runtime" "$CHANNEL" "$id"
  return 0
}

# check "label" "what must be true" — record a step as verified, failing, or not yet
# run. Bare Enter is the third answer: most of these need a TestFlight build on a
# physical device, and a step nobody could attempt yet is not a step that failed.
check() {
  local label="$1" expectation="$2" reply=""
  step "$expectation"
  printf '  %s? %s — did that happen? [y/n/Enter = not yet]%s ' "$YELLOW" "$label" "$RESET"
  read -r reply || true
  case "$reply" in
    [Yy]*)
      RESULTS+=("- [x] $label — $expectation")
      printf '  %s✓ recorded as passing%s\n' "$GREEN" "$RESET" ;;
    [Nn]*)
      RESULTS+=("- [ ] $label — FAILED: $expectation")
      printf '  %s✗ recorded as failing%s\n' "$RED" "$RESET" ;;
    *)
      RESULTS+=("- [ ] $label — not yet run: $expectation")
      printf '  %s· recorded as not yet run%s\n' "$DIM" "$RESET" ;;
  esac
}

banner "Mibo — the production iOS build, and the TestFlight release"

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Preflight — everything that kills a store build twenty minutes in"
say "A store build is forty minutes of somebody else's computer. Eight things are"
say "checked here because each one fails late, or silently, or both."
say ""
say "1. The tools the later stages shell out to:"
have eas   "the build and the submit are eas commands"
have jq    "checks 7 and 8 read eas.json and Clerk with it, and stage 3 edits eas.json"
have curl  "check 5 cannot tell a live privacy policy from a dead one without it"
have git   "check 3 reads the tree this build would be cut from"
have gh    "the last stage posts the result onto issue #$ISSUE"
say ""

say "2. Who EAS thinks you are:"
if eas_who=$(eas_mobile whoami 2>&1); then
  printf '  %s✓%s logged in as %s\n' "$GREEN" "$RESET" "$(printf '%s' "$eas_who" | head -1)"
else
  warn "eas whoami failed — run 'eas login'. Nothing after stage 4 can work."
  SKIPPED+=("eas login")
  preflight_ok=0
fi
say ""

say "3. The tree this build would be cut from:"
# EAS uploads the working tree, not HEAD, so an uncommitted file ships in the
# binary and nothing records what was in it.
git_head=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)
git_branch=$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
git_dirty=$(git -C "$REPO_ROOT" status --porcelain 2>/dev/null || true)
printf '  %s%s%s on %s%s%s\n' "$BOLD" "$git_head" "$RESET" "$BOLD" "$git_branch" "$RESET"
if [[ -n "$git_dirty" ]]; then
  warn "The tree is dirty. EAS uploads the working tree, not HEAD — an uncommitted"
  warn "file goes into the binary and no commit says what was in it."
  printf '%s\n' "$git_dirty" | sed -n '1,10p' | while read -r line; do note "  $line"; done
  SKIPPED+=("commit or stash the working tree before the build in stage 5")
else
  printf '  %s✓%s clean\n' "$GREEN" "$RESET"
fi
say ""

say "4. The Sentry credentials, in the EAS '$ENVIRONMENT' environment:"
# This is the check the whole stage exists for. The Sentry config plugin is added
# unconditionally (app.config.ts), and giving it no org and project does not make
# the source-map upload sit out — it writes a sentry.properties of comments, and the
# build task that reads it is gated on SENTRY_DISABLE_AUTO_UPLOAD alone. The
# production profile does not set that variable, deliberately (#78), so a build
# whose environment holds no credentials reaches sentry-cli with nothing and dies
# twenty minutes in. scripts/setup-sentry.sh writes `preview` and `production`, but
# it was `preview`-only until #78 and a project set up before that has three of
# these missing in an environment nobody looks at.
if env_list=$(eas_mobile env:list "$ENVIRONMENT" 2>&1 | strip_ansi); then
  missing_vars=()
  for var in "${SENTRY_VARS[@]}"; do
    if printf '%s' "$env_list" | grep -q "^${var}="; then
      printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$var"
    else
      printf '  %s✗%s %s missing from the %s environment\n' "$RED" "$RESET" "$var" "$ENVIRONMENT"
      missing_vars+=("$var")
    fi
  done
  if (( ${#missing_vars[@]} )); then
    say ""
    warn "${#missing_vars[@]} of ${#SENTRY_VARS[@]} missing. A store build reaches sentry-cli with nothing"
    warn "and fails at the upload step — twenty minutes of build, and then nothing."
    note "  scripts/setup-sentry.sh writes all four to 'preview' and 'production'."
    if confirm "Run scripts/setup-sentry.sh now?"; then
      "$REPO_ROOT/scripts/setup-sentry.sh" || warn "setup-sentry.sh failed — it is idempotent, so re-run it."
    else
      SKIPPED+=("the ${#SENTRY_VARS[@]} Sentry variables in the EAS '$ENVIRONMENT' environment (run scripts/setup-sentry.sh)")
      preflight_ok=0
    fi
  fi
else
  warn "eas env:list failed — could not confirm the Sentry credentials."
  note "  Without them the build fails at the source-map upload, not at the start."
  SKIPPED+=("confirm the Sentry variables in the EAS '$ENVIRONMENT' environment")
fi
say ""

say "5. The three URLs the store listing and the paywall point at:"
# The paywall links two of these (guideline 3.1.2, adc3bb9) and the listing links
# all three (#82). A link App Review taps to nothing is the same rejection as no link.
urls_ok=1
url_serves "$API_BASE"         "Mibo"    || urls_ok=0
url_serves "$API_BASE/privacy" "Privacy" || urls_ok=0
url_serves "$API_BASE/terms"   "Terms"   || urls_ok=0
if (( ! urls_ok )); then
  warn "App Review taps these. A dead one is a rejection on guideline 3.1.2 or 5.1.1,"
  warn "and the paywall renders the links regardless of whether they resolve."
  SKIPPED+=("bring the store URLs back up — scripts/deploy-api.sh")
  preflight_ok=0
fi
say ""

say "6. The bundled assets, and that the live API is this commit:"
if (cd "$MOBILE" && pnpm check:assets >/dev/null 2>&1); then
  printf '  %s✓%s icons, splash and the Android layers match app.json\n' "$GREEN" "$RESET"
else
  warn "pnpm --filter mobile check:assets fails. The store build would ship the"
  warn "icon and splash that check describes, and Apple rejects a missing one."
  SKIPPED+=("pnpm --filter mobile check:assets")
  preflight_ok=0
fi
# A container that boots says nothing about which build is in it: an API that
# predates #84 answers /health normally and 404s /terms and /privacy. Which is why
# this is reported rather than enforced — what the release needs from the API is
# that those two pages exist, and check 5 above just proved they do. A mobile-only
# commit puts the deploy "behind HEAD" without changing anything the API serves,
# and that is the common case here, so a failure is a note and not a blocker.
# Captured rather than left to print between the wizard's own formatted lines, and
# then replayed through `note` so the shas it names stay readable in this frame.
if deploy_out=$("$REPO_ROOT/scripts/check-deploy.sh" "$API_BASE" 2>&1); then
  printf '  %s✓%s the live API is this commit\n' "$GREEN" "$RESET"
elif (( urls_ok )); then
  printf '%s\n' "$deploy_out" | sed -n '1,4p' | while read -r line; do note "  $line"; done
  note "  Behind HEAD, but serving all three pages — which is what this release"
  note "  needs from it. Redeploy if the last API change has to be live too."
else
  printf '%s\n' "$deploy_out" | sed -n '1,4p' | while read -r line; do note "  $line"; done
  warn "Behind HEAD, and not serving the pages above. Redeploy before submitting."
  SKIPPED+=("scripts/deploy-api.sh — the live API is behind this tree")
fi
say ""

say "7. The public app variables, in BOTH places that have to carry them:"
# The trap that made criterion 4 fail for the whole of M4 without anybody noticing.
# `eas build` reads eas.json's build.<profile>.env AND the EAS environment; `eas
# update` reads ONLY the EAS environment — Expo documents it plainly ("Environment
# variables set on the env field in build profiles are not available when you run
# eas update"). So a variable that lives only in eas.json is compiled into the
# binary and missing from every OTA bundle. The app then throws in its root layout
# before rendering, expo-updates rolls back to the embedded bundle, and the result
# is indistinguishable from an app that is simply up to date: no crash the user
# sees, no failed command, nothing in the channel to look at. The only signal is a
# Sentry error nobody is watching for.
#
# Checked as a parity diff rather than a list of names, so a variable added to
# eas.json later is covered without editing this script.
env_parity_ok=1
if eas_env_out=$(eas_mobile env:list "$ENVIRONMENT" 2>&1 | strip_ansi); then
  while IFS= read -r var; do
    [[ -z "$var" ]] && continue
    if printf '%s' "$eas_env_out" | grep -q "^${var}="; then
      printf '  %s✓%s %s is in eas.json and the %s environment\n' \
        "$GREEN" "$RESET" "$var" "$ENVIRONMENT"
    else
      printf '  %s✗%s %s is in eas.json but NOT in the %s environment\n' \
        "$RED" "$RESET" "$var" "$ENVIRONMENT"
      env_parity_ok=0
    fi
  done < <(jq -r --arg p "$PROFILE" \
    '.build[$p].env // {} | keys[] | select(startswith("EXPO_PUBLIC_"))' "$EAS_JSON" 2>/dev/null)
  if (( ! env_parity_ok )); then
    say ""
    warn "The build would work and every OTA update would be dead on arrival: the"
    warn "bundle ships without these, the app throws before its first screen, and"
    warn "expo-updates silently rolls back to the embedded bundle. It looks exactly"
    warn "like an app with no update waiting."
    note "  Mirror each one into the EAS environment, reading the value from eas.json"
    note "  rather than retyping a key:"
    printf '      %scd apps/mobile && eas env:set %s --name NAME \\%s\n' \
      "$BOLD" "$ENVIRONMENT" "$RESET"
    # shellcheck disable=SC2016  # the $(...) is printed for a human to copy, not run here
    printf '      %s  --value "$(jq -r .build.%s.env.NAME eas.json)" \\%s\n' \
      "$BOLD" "$PROFILE" "$RESET"
    printf '      %s  --visibility plaintext --scope project%s\n' "$BOLD" "$RESET"
    SKIPPED+=("mirror the EXPO_PUBLIC_ variables from eas.json into the EAS '$ENVIRONMENT' environment")
  fi
else
  warn "eas env:list failed — could not compare eas.json against the environment."
  SKIPPED+=("compare eas.json's EXPO_PUBLIC_ variables against the EAS '$ENVIRONMENT' environment")
fi
say ""

say "8. Sign in with Apple, on the PRODUCTION Clerk instance:"
# Criterion 3 of this ticket, and guideline 4.8 for the review after it: an app that
# offers Google must also offer Apple. Both halves of that live on Clerk's production
# instance rather than in the binary, and neither is visible from the app — which is
# what makes this a preflight check and not a device step.
#
# #85 found the connection saved with all its credentials and never switched on, and
# the redirect allowlist completely empty. Both were fixed with no rebuild, because
# Clerk reads them server-side when the flow starts. That is the good news and the
# whole argument for checking here: found now it is a dashboard click, found after the
# build it is a tester deciding the app is broken and a second forty-minute build cut
# to fix something that was never in the binary.
#
# The entitlement is deliberately not checked. @clerk/expo's config plugin adds
# com.apple.developer.applesignin unconditionally (withClerkAppleSignIn), so a Mibo
# build has always carried it — verified in #85 by stripping ios.usesAppleSignIn back
# out and re-introspecting. An entitlement is the one thing here a rebuild is the only
# fix for, and it has never been the fault.
#
# The connection object is pulled out once, and an unreadable one takes the same
# branch as an unreachable instance: a jq that could not parse the reply has not
# established that Apple is switched off, and saying so would send somebody to fix
# a dashboard that is already right.
# A check that cannot read is a check that protects nothing, so the Clerk login is
# offered here rather than discovered as a failure below. `clerk` is deliberately not in
# check 1's tool list: this is its only caller and npx supplies it.
if ! clerk_cli whoami >/dev/null 2>&1; then
  note "Not signed in to the Clerk CLI, which is how this check reads production."
  if confirm "Sign in now? (a browser tab opens)"; then
    clerk_cli auth login || warn "clerk auth login failed — the two checks below cannot run."
  fi
fi
# jq names the faults itself, in one pass over the pulled config. The alternative — a
# read per field — needs a `|| true` on each to survive `set -e`, and that turns a jq
# that failed into a credential that is missing: the wizard then sends somebody to fix
# a dashboard that is already right. Here a jq that cannot parse the reply produces no
# output, fails the `&&`, and takes the "could not read" branch instead.
#
# Two toggles are read because #85 found only the inner one set. `enabled` is whether
# Apple is a live SSO connection at all; `authenticatable` is whether a parent who has
# never signed in may sign UP with it. Enabled without authenticatable is the quieter
# version of the same 4.8 problem — it signs an existing account in and turns every new
# parent away, so it passes the one test somebody is likely to run.
if clerk_cfg=$(clerk_cli config pull --instance "$PROD_CLERK_INSTANCE" 2>/dev/null) \
   && [[ -n "$clerk_cfg" ]] \
   && apple_report=$(printf '%s' "$clerk_cfg" | jq -e -r '
        .connection_oauth_apple as $a
        | [ (if $a.enabled then empty
             else "is not enabled — Apple is not a live SSO connection at all" end),
            (if $a.authenticatable then empty
             else "is not authenticatable — no parent can SIGN UP with Apple" end),
            (["client_id", "team_id", "key_id"][]
             | select(($a[.] // "") == "") | "has no " + .) ]
        | join("\n")' 2>/dev/null); then
  apple_faults=()
  while IFS= read -r fault; do
    [[ -n "$fault" ]] && apple_faults+=("$fault")
  done <<<"$apple_report"
  if (( ${#apple_faults[@]} == 0 )); then
    printf '  %s✓%s the Apple connection is enabled and authenticatable, with custom credentials\n' \
      "$GREEN" "$RESET"
  else
    for fault in "${apple_faults[@]}"; do
      printf '  %s✗%s the Apple connection %s\n' "$RED" "$RESET" "$fault"
    done
    warn "The Apple button is dead on the shipped app, and an app offering Google"
    warn "without Apple is a guideline 4.8 rejection. No rebuild fixes it and none is"
    warn "needed — it is Clerk-side, and a saved connection reaches the build already"
    warn "on the device."
    note "  scripts/setup-apple-signin.sh walks the Apple and Clerk halves of it."
    SKIPPED+=("enable the Apple SSO connection on the production Clerk instance (scripts/setup-apple-signin.sh)")
    preflight_ok=0
  fi
else
  warn "Could not read the production Clerk config, so nothing here has been checked."
  warn "An unread check is not a passed one: the first store build shipped against an"
  warn "instance nobody had looked at, and this is the look."
  note "  Configure → SSO connections → Apple, with the instance selector on Production."
  SKIPPED+=("confirm the Apple SSO connection is enabled on production Clerk")
  preflight_ok=0
fi
# The allowlist is checked separately because it fails differently: the connection can
# be perfect and every sign-in still stops at "the current redirect url ... does not
# match an authorised url", which reads as an app bug and is not one.
#
# Matched as whole lines, and only once jq has parsed the reply into them. `mibo://` is
# a prefix of the URL that matters and is registered in its own right, so a substring
# match finds the allowlist healthy off an entry that does nothing — the fault #85 found
# in scripts/clerk-setup.sh's own verification. The match runs in bash rather than
# through `grep -q` because a reader that stops at the first line kills the writer with
# SIGPIPE, and under `pipefail` a correct answer reads as a failed command.
if redirect_json=$(clerk_cli api --instance "$PROD_CLERK_INSTANCE" /redirect_urls 2>/dev/null) \
   && allowed=$(printf '%s' "$redirect_json" | jq -e -r '.[].url' 2>/dev/null); then
  if [[ $'\n'"$allowed"$'\n' == *$'\n'"$APP_REDIRECT_URL"$'\n'* ]]; then
    printf '  %s✓%s %s is on the production redirect allowlist\n' "$GREEN" "$RESET" "$APP_REDIRECT_URL"
  else
    printf '  %s✗%s %s is NOT on the production redirect allowlist\n' "$RED" "$RESET" "$APP_REDIRECT_URL"
    warn "Every parent sign-in on the store build stops at Clerk, Apple and Google"
    warn "alike. This is exactly what the first TestFlight build hit."
    note "  scripts/setup-apple-signin.sh registers it, or add it under"
    note "  Configure → Paths → Redirect URLs on the production instance."
    SKIPPED+=("register $APP_REDIRECT_URL on the production Clerk redirect allowlist")
    preflight_ok=0
  fi
else
  warn "Could not read the production redirect allowlist — check it by hand."
  SKIPPED+=("confirm $APP_REDIRECT_URL is on the production Clerk redirect allowlist")
  preflight_ok=0
fi
say ""

if (( preflight_ok )); then
  printf '  %s%s✓ preflight clean%s\n' "$BOLD" "$GREEN" "$RESET"
else
  warn "Preflight found something. Every item is in the summary at the end."
fi
pause "Press Enter when the preflight looks right."

# ── 2 ───────────────────────────────────────────────────────────────────
stage "The version this release carries, and the runtime it pins"
app_version=$(jq -r '.expo.version' "$APP_JSON" 2>/dev/null || echo unknown)
say "app.json says version $app_version."
say ""
if [[ "$app_version" == 0.* ]]; then
  warn "A 0.x version is what App Store Connect will print on the store page and in"
  warn "TestFlight. Bump apps/mobile/app.json to 1.0.0 before building."
  SKIPPED+=("bump apps/mobile/app.json version out of 0.x")
else
  printf '  %s✓%s a release version, not a 0.x placeholder\n' "$GREEN" "$RESET"
fi
say ""
note "Two things follow from that number, and both are easy to get wrong:"
note ""
note "  · runtimeVersion uses the 'appVersion' policy, so the runtime version IS"
note "    $app_version. An update published while this is the version reaches only"
note "    binaries built while it was the version. Bumping it strands the old ones"
note "    — deliberately, because a JS bundle cannot change native code."
note ""
note "  · appVersionSource is 'remote', so the BUILD NUMBER is EAS's, not this"
note "    file's, and EAS increments it for you. Never hand-edit a buildNumber."
say ""
say "What EAS currently holds for iOS:"
# Captured whole and then filtered: the command prints its environment-loading
# chatter and three pbxproj warnings before the one line that answers the question,
# and under `set -o pipefail` a reader that stops early kills it with SIGPIPE.
if version_out=$(eas_mobile build:version:get --platform ios 2>&1); then
  version_line=$(printf '%s\n' "$version_out" | grep -i 'buildNumber' || true)
  if [[ -n "$version_line" ]]; then
    printf '%s\n' "$version_line" | while read -r line; do note "  $line"; done
    note "  The next build takes the number after that one."
  else
    note "  nothing yet — this would be the first build, and EAS starts the count."
  fi
else
  note "  eas could not read it; the build in stage 5 sets it either way."
fi
pause

# ── 3 ───────────────────────────────────────────────────────────────────
stage "The App Store Connect app id, into the submit profile"
say "eas.json carries a submit profile named '$PROFILE' with an empty ios block."
say "Filling in ascAppId is what lets 'eas submit' go straight to the right app"
say "record instead of looking it up and asking."
say ""
current_asc=$(jq -r '.submit.production.ios.ascAppId // empty' "$EAS_JSON" 2>/dev/null || true)
if [[ -n "$current_asc" ]]; then
  printf '  %s✓%s eas.json already names ascAppId %s\n' "$GREEN" "$RESET" "$current_asc"
  note "  Re-running this stage is safe; Enter keeps it."
else
  say "It is the numeric id in the App Store Connect URL of the app record —"
  say "appstoreconnect.apple.com/apps/<THIS NUMBER>/... — not the bundle id."
  open_url_chrome "https://appstoreconnect.apple.com/apps"
fi
say ""
asc_app_id=""
printf '  %sApp Store Connect app id (digits only; Enter to skip):%s ' "$BOLD" "$RESET"
read -r asc_app_id || true
asc_app_id="${asc_app_id//[[:space:]]/}"
if [[ -z "$asc_app_id" ]]; then
  if [[ -z "$current_asc" ]]; then
    note "Skipped. 'eas submit' will find the app by bundle id and ask to confirm."
    SKIPPED+=("submit.production.ios.ascAppId in apps/mobile/eas.json")
  fi
elif [[ ! "$asc_app_id" =~ ^[0-9]+$ ]]; then
  warn "That is not the app id — it is digits only. Not written."
  SKIPPED+=("submit.production.ios.ascAppId in apps/mobile/eas.json")
elif tmp_eas=$(mktemp) && jq --arg id "$asc_app_id" \
     '.submit.production.ios.ascAppId = $id' "$EAS_JSON" > "$tmp_eas"; then
  mv "$tmp_eas" "$EAS_JSON"
  printf '  %s✓ wrote%s ascAppId %s → apps/mobile/eas.json\n' "$GREEN" "$RESET" "$asc_app_id"
  warn "eas.json is committed, so this is now an uncommitted change. Commit it —"
  warn "and mind stage 1's check 3, which wants a clean tree before the build."
else
  rm -f "${tmp_eas:-}"
  warn "Could not edit eas.json — add submit.production.ios.ascAppId by hand."
  SKIPPED+=("submit.production.ios.ascAppId in apps/mobile/eas.json")
fi
pause

# ── 4 ───────────────────────────────────────────────────────────────────
stage "iOS distribution credentials"
say "A store build needs an Apple Distribution certificate and an App Store"
say "provisioning profile for $BUNDLE_ID. EAS can make and hold both."
say ""
step "In another terminal: cd apps/mobile && eas credentials"
step "Pick iOS → $PROFILE → Build Credentials → 'All: Set up all the"
step "required credentials to build your project'."
note "  It signs you into Apple, makes the certificate and the profile, and keeps"
note "  them on EAS. A certificate is per-account and there is a limit of two —"
note "  reuse an existing one rather than making a third."
say ""
note "The App Store Connect API key from scripts/setup-appstore-api-key.sh is a"
note "separate thing: that one reads App Store Connect for RevenueCat, this one"
note "signs a binary. EAS can use the same key for the upload in stage 6."
say ""
warn "Sign in with Apple is not a credential this stage sets. #77 implemented it"
warn "through Clerk's SSO flow, which uses Apple's web OAuth and an Apple Services"
warn "ID rather than the app's provisioning profile — so nothing you do in"
warn "'eas credentials' makes the Apple button work or stops it working."
say ""
note "That side was configured and verified on the production instance in #85, and"
note "check 8 of stage 1 reads it back before every release. The Services ID, team"
note "and key live on Clerk; scripts/setup-apple-signin.sh is the wizard for them."
say ""
note "There is no non-interactive way to list what EAS holds — 'eas credentials' is"
note "a menu and has no :list subcommand — so this stage cannot check the"
note "credentials for you. The build in stage 5 is the check: it stops at the start"
note "and asks, rather than failing at the end, when signing is not set up."
pause "Press Enter once the certificate and profile exist."

# ── 5 ───────────────────────────────────────────────────────────────────
stage "Build"
say "The command, and what it does:"
printf '      %scd apps/mobile && eas build --platform ios --profile %s%s\n' "$BOLD" "$PROFILE" "$RESET"
say ""
note "  · reads the EAS '$ENVIRONMENT' environment — the four variables from stage 1"
note "  · uploads the working tree, not HEAD"
note "  · takes the remote build number and increments it"
note "  · uploads source maps to Sentry at the end, which is the step that fails"
note "    when the credentials are missing"
say ""
warn "Twenty to forty minutes, and the failure modes are all at the far end."
say ""
if confirm "Start the build now? (it streams here until it finishes)"; then
  if eas_mobile build --platform ios --profile "$PROFILE"; then
    printf '  %s✓ build finished%s\n' "$GREEN" "$RESET"
    RESULTS+=("- [x] Production iOS build — compiled on EAS with the $PROFILE profile")
  else
    warn "The build failed. The log URL above says where; the usual late failure is"
    warn "the Sentry upload, which is stage 1 check 4."
    RESULTS+=("- [ ] Production iOS build — FAILED on EAS, see the build log")
  fi
else
  note "Not started. Run it in another terminal and come back — the stages after"
  note "this one only need the finished build, not this wizard's session."
  SKIPPED+=("eas build --platform ios --profile $PROFILE")
fi
pause

# ── 6 ───────────────────────────────────────────────────────────────────
stage "Submit to App Store Connect"
say "The build has to reach App Store Connect before TestFlight has anything to"
say "process. --latest picks the most recent finished build for the platform."
printf '      %scd apps/mobile && eas submit --platform ios --profile %s --latest%s\n' \
  "$BOLD" "$PROFILE" "$RESET"
say ""
note "It asks for an App Store Connect API key the first time and remembers it —"
note "the same key scripts/setup-appstore-api-key.sh created, or a new one."
note "Upload plus Apple's own processing is usually ten to twenty minutes."
say ""
if confirm "Submit the latest build now?"; then
  if eas_mobile submit --platform ios --profile "$PROFILE" --latest; then
    printf '  %s✓ uploaded%s\n' "$GREEN" "$RESET"
    RESULTS+=("- [x] Upload to App Store Connect — eas submit accepted the build")
  else
    warn "The submit failed. A rejected upload is usually a missing agreement, a"
    warn "bundle id Apple does not know, or a build number Apple already has."
    RESULTS+=("- [ ] Upload to App Store Connect — FAILED, see the submit output")
  fi
else
  SKIPPED+=("eas submit --platform ios --profile $PROFILE --latest")
fi
pause

# ── 7 ───────────────────────────────────────────────────────────────────
stage "TestFlight"
open_url_chrome "https://appstoreconnect.apple.com/apps"
say "On the app record → TestFlight:"
step "Wait for the build to leave 'Processing'. Apple emails when it does."
step "Export compliance should not be asked — app.json sets"
step "ITSAppUsesNonExemptEncryption to false, so the binary answers it itself."
note "  If it is asked, the build predates that key and the binary is the wrong one."
step "Internal Testing → add yourself to a group, and add the build to it."
note "  Internal testers need no Beta App Review, so the build is installable in"
note "  minutes. External testing does need review and is not what this ticket asks."
say ""
step "On the device: install TestFlight, accept the invite, install Mibo."
warn "Delete any dev-client or preview build of Mibo first. They share a bundle id,"
warn "so the TestFlight install replaces one and inherits its on-device database —"
warn "which is not the fresh install criterion 1 asks for."
pause "Press Enter once the build is installed on a physical device."

# ── 8 ───────────────────────────────────────────────────────────────────
stage "The production channel, and the source maps an OTA update needs"
say "Criterion 4 is that the production channel reaches this binary. The build"
say "carries channel '$CHANNEL' (eas.json), so an update published there reaches it"
say "— for runtime version $app_version and no other."
say ""
say "Two commands, and the second one is the one that gets forgotten:"
printf '      %spnpm --filter @chores/shared build%s\n' "$BOLD" "$RESET"
printf '      %scd apps/mobile && eas update --channel %s --environment %s --clear-cache --message "..."%s\n' \
  "$BOLD" "$CHANNEL" "$ENVIRONMENT" "$RESET"
printf '      %scd apps/mobile && npx --package=@sentry/react-native sentry-expo-upload-sourcemaps dist%s\n' \
  "$BOLD" "$RESET"
say ""
note "The build-time source-map upload #78 set up covers the binary's own bundle"
note "and nothing else. An OTA bundle is a different bundle with different debug"
note "ids, so a crash in an update comes back as unsymbolicated hex unless the"
note "second command runs. Carried here from #79, which found it."
note ""
note "--environment is not optional: EAS requires it from SDK 55 on, and Mibo is"
note "on 57. It is what makes the OTA bundle carry the same EXPO_PUBLIC_ values the"
note "store build was compiled with — the API URL and the Clerk key among them. An"
note "update built against the wrong environment points a shipped app at the wrong"
note "backend, and nothing about it looks wrong."
note ""
note "@chores/shared resolves to its dist/, built by tsc — so 'eas update' bundles"
note "whatever that directory happens to hold. It does NOT build workspace packages."
note "On EAS Build this never bites, because pnpm install runs the package's"
note "'prepare' script; locally a stale dist/ means an OTA hotfix to shared code"
note "publishes the OLD code and looks like it worked. Hence the build first."
note ""
note "--clear-cache for the same class of reason: Metro caches transformed modules"
note "per file, and a rebuilt dependency it believes it has already seen can be"
note "served from that cache."
note ""
note "'eas update' exports to dist/ — its --input-dir default — with source maps,"
note "and dist/ is what the second command reads. SENTRY_AUTH_TOKEN has to be in"
note "this shell's environment for it: the token is an EAS secret, readable on a"
note "builder and not from here, so export it by hand for this one command."
say ""
warn "An update is instant and irreversible for anyone who fetches it. Publish a"
warn "copy fix, not a behaviour change."
warn ""
warn "Make it a copy fix you can SEE. Criterion 4 is that the installed app picks"
warn "the update up, and a no-op update cannot show that on a device: the screen is"
warn "byte-identical either way, so the OTA check in stage 9 becomes a question"
warn "nobody can answer honestly. Change a heading, read it on the device, then"
warn "change it back and publish once more."
say ""
if confirm "Publish an update to the '$CHANNEL' channel now?"; then
  update_message=""
  printf '  %sUpdate message:%s ' "$BOLD" "$RESET"
  read -r update_message || true
  [[ -z "$update_message" ]] && update_message="verify the $CHANNEL channel (#$ISSUE)"
  if ! (cd "$REPO_ROOT" && pnpm --filter @chores/shared build); then
    warn "The shared package did not build, so the update would carry a stale copy."
    SKIPPED+=("pnpm --filter @chores/shared build, then re-run the update")
  fi
  if eas_mobile update --channel "$CHANNEL" --environment "$ENVIRONMENT" --clear-cache --message "$update_message"; then
    printf '  %s✓ published%s\n' "$GREEN" "$RESET"
    say ""
    step "Asking the updates server what it serves an iOS client on runtime $app_version."
    if manifest_serves "$app_version"; then
      RESULTS+=("- [x] 4. The $CHANNEL channel serves this binary — ios, runtime $app_version")
    else
      warn "The update published, but the server does not offer it to this binary."
      warn "Compare the runtime the update carries against the build's $app_version;"
      warn "a runtime mismatch is the usual cause and no device will ever show it."
      SKIPPED+=("investigate why $CHANNEL serves no ios manifest for runtime $app_version")
    fi
    say ""
    if [[ -z "${SENTRY_AUTH_TOKEN:-}" ]]; then
      warn "SENTRY_AUTH_TOKEN is not set, so the source maps were not uploaded."
      SKIPPED+=("upload the OTA source maps: SENTRY_AUTH_TOKEN=... npx --package=@sentry/react-native sentry-expo-upload-sourcemaps dist")
    elif (cd "$MOBILE" && npx --package=@sentry/react-native sentry-expo-upload-sourcemaps dist); then
      printf '  %s✓ source maps uploaded%s\n' "$GREEN" "$RESET"
    else
      warn "The source-map upload failed. The update is live either way; its stack"
      warn "traces will be unsymbolicated until the upload is re-run against dist/."
      SKIPPED+=("re-run the OTA source-map upload from apps/mobile")
    fi
  else
    warn "eas update failed — the channel is unproven."
    SKIPPED+=("eas update --channel $CHANNEL --environment $ENVIRONMENT --clear-cache")
  fi
else
  SKIPPED+=("eas update --channel $CHANNEL --environment $ENVIRONMENT, and its source-map upload")
fi
pause

# ── 9 ───────────────────────────────────────────────────────────────────
stage "Device verification — the five steps on the ticket"
say "On the physical device, on the TestFlight build. Answer honestly: bare Enter"
say "records a step as not yet run, which is not the same as failing."
say ""
check "1. Fresh install" "TestFlight installs Mibo onto a device that had no Mibo on it, and it launches."
check "Icon and splash" "The home screen shows the production icon, and the splash screen is Mibo's, not Expo's."
note "Apple sign-in fails Clerk-side, not in the binary — the connection or the"
note "redirect allowlist, both of check 8, and both fixable without a rebuild."
check "2. Sign in with Apple" "A real Apple ID signs in as a parent, and lands in parent mode."
check "2. Sign in with Google" "Google sign-in still works — Apple sign-in was added beside it, not over it."
check "3. Household setup" "A household can be created, a Join Code issued, and a second device pairs with it as a Kid Device."
check "3. Parent PIN" "On the paired device the Parent PIN reaches parent mode, and a wrong PIN does not."
check "4. Paywall renders" "A gate shows the paywall with all three prices, and the renewal terms and both document links under them."
check "4. Sandbox purchase" "A sandbox purchase completes and the household turns premium without a restart."
check "5. OTA update" "The visible change from stage 8 reached the device — reopen once so it fetches in the background, then again so it launches the update."
pause

# ── 10 ──────────────────────────────────────────────────────────────────
stage "The M4 exit criterion"
say "One pass over what the milestone said it would deliver (#76 §5)."
say ""
check "Submitted to TestFlight" "A production build of $BUNDLE_ID is on TestFlight and installable."
check "Sign in with Apple" "Apple sign-in works on a real device with a real Apple ID."
check "COPPA privacy policy" "$API_BASE/privacy is live and linked from the store listing and the paywall."
check "Listing metadata" "The App Store listing, privacy labels and age rating are complete and published."
check "Production credentials" "The build carries the production Clerk key, the production Sentry project, and RevenueCat's live products."
pause

# ── 11 ──────────────────────────────────────────────────────────────────
stage "Report back to issue #$ISSUE"
say "Posting the result as a comment."
if (( ${#RESULTS[@]} == 0 )); then
  warn "Nothing recorded — nothing to report."
  SKIPPED+=("the release comment on issue #$ISSUE")
  finish
  exit 0
fi
# shellcheck disable=SC2016  # the backticks are Markdown for the issue comment
comment=$(printf '## Production iOS build and TestFlight release\n\nRun via `scripts/release-ios.sh` on %s.\nVersion %s, commit %s, channel `%s`.\n\n%s\n' \
  "$(date -u '+%Y-%m-%d %H:%M UTC')" "$app_version" "$git_head" "$CHANNEL" \
  "$(printf '%s\n' "${RESULTS[@]}")")
printf '\n%s\n\n' "$comment"
if confirm "Post this to issue #$ISSUE?"; then
  if printf '%s' "$comment" | gh issue comment "$ISSUE" --body-file - >/dev/null 2>&1; then
    printf '  %s✓ posted%s to issue #%s\n' "$GREEN" "$RESET" "$ISSUE"
  else
    warn "gh could not post — copy the comment above onto the issue by hand."
    SKIPPED+=("the release comment on issue #$ISSUE")
  fi
else
  SKIPPED+=("the release comment on issue #$ISSUE")
fi
pause

finish
note "M4 is the last milestone before the store, and every sibling of this ticket is"
note "closed — #85 included, so Apple sign-in is live on production. What remains is"
note "whatever stage 9 and stage 10 recorded above as failing or not yet run."
printf '\n'
