#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES — M7.7 the Android release: closed test, fourteen days, Production (issue #114).
#
# The Play developer account is personal, so Production stays locked until a closed
# test has held at least 12 opted-in testers for 14 continuous days and Google has then
# approved an application for production access. That is three sittings weeks apart,
# so the wizard runs in three modes and remembers what the earlier ones recorded:
#
#   scripts/release-android.sh               build, upload to Closed testing, testers,
#                                            rollout — and the clock, if 12 are in already
#   scripts/release-android.sh --clock       record the day the 12th tester opted in
#   scripts/release-android.sh --production  after the 14 days: apply for production
#                                            access, then (once granted) promote the same
#                                            .aab, publish the production channel, verify
#
# Each mode reports to issue #114. Nothing here writes to the app's code; it drives
# `eas`, Play Console and a physical device. scripts/release-ios.sh is the model.
# ──────────────────────────────────────────────────────────────────────────

MODE=closed
case "${1:-}" in
  "")           ;;
  --clock)      MODE=clock ;;
  --production) MODE=production ;;
  *) printf 'usage: %s [--clock | --production]\n' "$0" >&2; exit 2 ;;
esac
case "$MODE" in
  closed)     TOTAL_STAGES=8 ;;
  clock)      TOTAL_STAGES=2 ;;
  production) TOTAL_STAGES=6 ;;
esac

# Play Console and expo.dev are worked in Chrome, not the default browser — the same
# wrapper as scripts/release-ios.sh.
BROWSER_APP="${BROWSER_APP:-Google Chrome}"
open_url_chrome() {
  local url="$1"
  if [[ "$OSTYPE" == darwin* ]] && open -a "$BROWSER_APP" "$url" >/dev/null 2>&1; then
    printf '  %s↗ opening%s %s %s(%s)%s\n' "$GREEN" "$RESET" "$url" "$DIM" "$BROWSER_APP" "$RESET"
    return
  fi
  open_url "$url"
}

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
MOBILE="$REPO_ROOT/apps/mobile"
EAS_JSON="$MOBILE/eas.json"
APP_JSON="$MOBILE/app.json"
API_BASE="${API_BASE:-https://mibokids.app}"
PACKAGE="com.mibokids.app"
PROFILE="production"
CHANNEL="production"
ENVIRONMENT="production"
PLAY_CONSOLE="https://play.google.com/console"
# packages/shared/src/setup.ts shares this in the join-code text, so it has to resolve.
PLAY_URL="https://play.google.com/store/apps/details?id=$PACKAGE"
OPT_IN_URL="https://play.google.com/apps/testing/$PACKAGE"
ISSUE=114
# Play's rule for a personal account, and the buffer the ticket asks for on top of it:
# one tester dropping out below MIN_TESTERS restarts the 14 days, so recruit past it.
MIN_TESTERS=12
AIM_TESTERS=15
CLOCK_DAYS=14

# What the three sittings hand each other. Ignored by .gitignore's .env.*; nothing
# secret goes in — the tester group's address is the most personal thing here.
ENV_FILE="$REPO_ROOT/scripts/.env.release-android"

# Every variable the store build and the OTA bundle need from the EAS environment. The
# four Sentry ones because a build without them dies at the source-map upload twenty
# minutes in (release-ios.sh, check 4); the RevenueCat key because purchases.ts reads it
# and without it the paywall has nothing to sell (#110). The EXPO_PUBLIC_ variables in
# eas.json are added at run time: `eas update` reads only the environment, so one that
# lives only in eas.json is missing from every OTA bundle (release-ios.sh, check 7).
REQUIRED_VARS=(SENTRY_ORG SENTRY_PROJECT SENTRY_AUTH_TOKEN EXPO_PUBLIC_SENTRY_DSN
               EXPO_PUBLIC_REVENUECAT_ANDROID_KEY)

RESULTS=()
preflight_ok=1

eas_mobile() { (cd "$MOBILE" && eas "$@"); }
strip_ansi() { sed $'s/\x1b\[[0-9;]*m//g'; }

# have TOOL "why it matters" — as in release-ios.sh: a reporter, not a predicate.
have() {
  local tool="$1" why="$2"
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$tool"
    return 0
  fi
  printf '  %s✗%s %s — %s\n' "$RED" "$RESET" "$tool" "$why"
  SKIPPED+=("install $tool — $why")
  preflight_ok=0
  return 0
}

# check "label" "what must be true" — y / n / Enter = not yet run.
check() {
  local label="$1" expectation="$2" reply=""
  step "$expectation"
  printf '  %s? %s — did that happen? [y/n/Enter = not yet]%s ' "$YELLOW" "$label" "$RESET"
  read -r reply || true
  case "$reply" in
    [Yy]*)
      RESULTS+=("- [x] $label — $expectation")
      printf '  %s✓ recorded as passing%s\n' "$GREEN" "$RESET" ;;
    [Nn]*)
      RESULTS+=("- [ ] $label — FAILED: $expectation")
      printf '  %s✗ recorded as failing%s\n' "$RED" "$RESET" ;;
    *)
      RESULTS+=("- [ ] $label — not yet run: $expectation")
      printf '  %s· recorded as not yet run%s\n' "$DIM" "$RESET" ;;
  esac
}

# record "label" "outcome" pass|fail — a result the wizard measured itself.
record() {
  if [[ "$3" == pass ]]; then
    RESULTS+=("- [x] $1 — $2")
    printf '  %s✓ %s%s\n' "$GREEN" "$2" "$RESET"
  else
    RESULTS+=("- [ ] $1 — FAILED: $2")
    printf '  %s✗ %s%s\n' "$RED" "$2" "$RESET"
  fi
}

# Dates are whole days, taken at noon so a DST change never moves one across midnight.
# BSD date first (macOS), GNU date as the fallback.
today() { date +%Y-%m-%d; }
epoch_of() { date -j -f '%Y-%m-%d %H:%M' "$1 12:00" +%s 2>/dev/null || date -d "$1 12:00" +%s; }
# BSD date rolls 2026-02-30 over to March rather than refusing it, so a date is valid
# only if it survives the round trip unchanged.
valid_date() { [[ "$1" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ && "$(plus_days 0 "$1" 2>/dev/null)" == "$1" ]]; }
plus_days() {
  local e=$(( $(epoch_of "$2") + $1 * 86400 ))
  date -r "$e" +%Y-%m-%d 2>/dev/null || date -d "@$e" +%Y-%m-%d
}
days_since() { echo $(( ( $(epoch_of "$(today)") - $(epoch_of "$1") + 43200 ) / 86400 )); }

# latest_build — the newest finished Android build on the production profile, as
# "id versionCode appVersion commit archiveUrl" on one tab-separated line, or nothing.
# Tabs and "-" for a missing field, because `read` collapses runs of whitespace and an
# empty field would shift the archive URL into the commit.
latest_build() {
  eas_mobile build:list --platform android --build-profile "$PROFILE" --status finished \
      --limit 1 --json 2>/dev/null \
    | jq -r '.[0] // empty | [.id, .appBuildVersion, .appVersion, .gitCommitHash,
                             (.artifacts.applicationArchiveUrl // .artifacts.buildUrl)]
             | map(. // "-") | @tsv' 2>/dev/null || true
}

# check_eas_env — every REQUIRED_VAR and every EXPO_PUBLIC_ variable in eas.json is in
# the EAS production environment. Returns 1 on a gap or an unreadable environment.
check_eas_env() {
  local env_list="" var ok=0 vars=("${REQUIRED_VARS[@]}")
  if ! env_list=$(eas_mobile env:list "$ENVIRONMENT" 2>&1 | strip_ansi); then
    warn "eas env:list failed — could not read the '$ENVIRONMENT' environment."
    return 1
  fi
  while IFS= read -r var; do
    [[ -n "$var" ]] && vars+=("$var")
  done < <(jq -r --arg p "$PROFILE" \
    '.build[$p].env // {} | keys[] | select(startswith("EXPO_PUBLIC_"))' "$EAS_JSON" 2>/dev/null)
  for var in "${vars[@]}"; do
    if printf '%s' "$env_list" | grep -q "^${var}="; then
      printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$var"
    else
      printf '  %s✗%s %s missing from the %s environment\n' "$RED" "$RESET" "$var" "$ENVIRONMENT"
      ok=1
    fi
  done
  return "$ok"
}

# manifest_serves RUNTIME — release-ios.sh's check, asked as an Android client: does
# u.expo.dev offer an update to this binary on this channel?
manifest_serves() {
  local runtime="$1" url="" reply="" id=""
  url=$(jq -r '.expo.updates.url // empty' "$APP_JSON" 2>/dev/null) || url=""
  [[ -n "$url" ]] || { printf '  %s✗%s app.json names no updates.url\n' "$RED" "$RESET"; return 1; }
  if ! reply=$(curl -fsS -D - --max-time 20 "$url" \
      -H 'expo-platform: android' \
      -H "expo-runtime-version: $runtime" \
      -H "expo-channel-name: $CHANNEL" \
      -H 'expo-protocol-version: 1' \
      -H 'expo-api-version: 1' \
      -H 'accept: multipart/mixed' 2>/dev/null); then
    printf '  %s✗%s no manifest for android on runtime %s\n' "$RED" "$RESET" "$runtime"
    return 1
  fi
  id=$(printf '%s' "$reply" | tr -d '\r' | sed -n 's/^expo-update-id: *//p' | head -1)
  if [[ -z "$id" ]]; then
    printf '  %s✗%s no expo-update-id — nothing published for runtime %s\n' "$RED" "$RESET" "$runtime"
    return 1
  fi
  printf '  %s✓%s android / runtime %s / channel %s → update %s\n' \
    "$GREEN" "$RESET" "$runtime" "$CHANNEL" "$id"
}

# What earlier sittings recorded.
CLOSED_BUILD_ID=$(_existing CLOSED_BUILD_ID || true)
CLOSED_VERSION_CODE=$(_existing CLOSED_VERSION_CODE || true)
CLOSED_APP_VERSION=$(_existing CLOSED_APP_VERSION || true)
CLOSED_COMMIT=$(_existing CLOSED_COMMIT || true)
CLOSED_TEST_STARTED=$(_existing CLOSED_TEST_STARTED || true)
PRODUCTION_APPLIED=$(_existing PRODUCTION_APPLIED || true)

git_head=$(git -C "$REPO_ROOT" rev-parse --verify -q HEAD 2>/dev/null) || git_head=unknown
git_branch=$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
app_version=$(jq -r '.expo.version' "$APP_JSON" 2>/dev/null || echo unknown)

# ── the clock stage, shared by the first sitting and --clock ─────────────────
# clock_stage [inline] — "inline" when called inside another stage, so the counter
# does not advance.
clock_stage() {
  if [[ "${1:-}" == inline ]]; then
    printf '\n  %sThe %s-day clock%s\n' "$BOLD" "$CLOCK_DAYS" "$RESET"
  else
    stage "The $CLOCK_DAYS-day clock"
  fi
  say "Play counts from the day the ${MIN_TESTERS}th tester opted in, not from the rollout,"
  say "and it restarts if the count drops below $MIN_TESTERS on any day in between."
  open_url_chrome "$PLAY_CONSOLE"
  step "Mibo → Dashboard → the 'Apply for production' card shows testers opted in"
  step "and the days counted so far."
  say ""
  if [[ -n "$CLOSED_TEST_STARTED" ]]; then
    note "Recorded start: $CLOSED_TEST_STARTED — day $(days_since "$CLOSED_TEST_STARTED") of $CLOCK_DAYS."
    if confirm "Has the count stayed at $MIN_TESTERS or more every day since then?"; then
      RESULTS+=("- [x] Closed test clock — $MIN_TESTERS+ opted in since $CLOSED_TEST_STARTED")
      return 0
    fi
    warn "Then the clock restarted on the day it climbed back to $MIN_TESTERS."
  fi
  local opted="" started=""
  printf '  %sTesters opted in right now:%s ' "$BOLD" "$RESET"
  read -r opted || true
  opted="${opted//[[:space:]]/}"
  if [[ ! "$opted" =~ ^[0-9]+$ ]] || (( 10#$opted < MIN_TESTERS )); then
    warn "Fewer than $MIN_TESTERS — the clock has not started. Keep recruiting (aim $AIM_TESTERS+), then:"
    printf '      %sscripts/release-android.sh --clock%s\n' "$BOLD" "$RESET"
    RESULTS+=("- [ ] Closed test clock — not started: ${opted:-?} of $MIN_TESTERS testers opted in")
    SKIPPED+=("scripts/release-android.sh --clock once $MIN_TESTERS testers are opted in")
    return 0
  fi
  printf '  %sDay the %sth opted in (YYYY-MM-DD, Enter = today):%s ' "$BOLD" "$MIN_TESTERS" "$RESET"
  read -r started || true
  started="${started//[[:space:]]/}"
  [[ -z "$started" ]] && started=$(today)
  if ! valid_date "$started" || (( $(days_since "$started") < 0 )); then
    warn "Not a date, or one in the future — nothing recorded. Re-run with --clock."
    SKIPPED+=("record the closed-test start: scripts/release-android.sh --clock")
    return 0
  fi
  CLOSED_TEST_STARTED="$started"
  write_env CLOSED_TEST_STARTED "$started"
  RESULTS+=("- [x] Closed test clock — $opted testers opted in, counting from $started")
  if (( 10#$opted < AIM_TESTERS )); then
    warn "$opted is a thin margin: one dropout below $MIN_TESTERS restarts all $CLOCK_DAYS days."
  fi
}

# ── the report, shared by every mode ────────────────────────────────────────
report_stage() {
  # Always the last stage, including when --production stops early to wait on Google.
  _STAGE_INDEX=$((TOTAL_STAGES - 1))
  stage "Report back to issue #$ISSUE"
  local title earliest="" clock_line="Closed-test clock: not started."
  case "$MODE" in
    closed)     title="Android closed test" ;;
    clock)      title="Android closed test — the clock" ;;
    production) title="Android Production release" ;;
  esac
  if [[ -n "$CLOSED_TEST_STARTED" ]]; then
    earliest=$(plus_days "$CLOCK_DAYS" "$CLOSED_TEST_STARTED")
    clock_line="Closed-test clock started **$CLOSED_TEST_STARTED**; the earliest day to apply for production access is **$earliest**."
  fi
  if (( ${#RESULTS[@]} == 0 )); then
    warn "Nothing recorded — nothing to report."
    SKIPPED+=("the report comment on issue #$ISSUE")
    return 0
  fi
  local comment
  # shellcheck disable=SC2016  # the backticks are Markdown for the issue comment
  comment=$(printf '## %s\n\nRun via `scripts/release-android.sh%s` on %s.\nVersion %s, versionCode %s, commit %s, channel `%s`.\n%s\n\n%s\n' \
    "$title" "$( [[ $MODE == closed ]] || printf ' --%s' "$MODE" )" \
    "$(date -u '+%Y-%m-%d %H:%M UTC')" \
    "${CLOSED_APP_VERSION:-$app_version}" "${CLOSED_VERSION_CODE:-?}" \
    "$(printf '%s' "${CLOSED_COMMIT:-$git_head}" | cut -c1-7)" "$CHANNEL" \
    "$clock_line" "$(printf '%s\n' "${RESULTS[@]}")")
  printf '\n%s\n\n' "$comment"
  if confirm "Post this to issue #$ISSUE?"; then
    if printf '%s' "$comment" | gh issue comment "$ISSUE" --body-file - >/dev/null 2>&1; then
      printf '  %s✓ posted%s to issue #%s\n' "$GREEN" "$RESET" "$ISSUE"
    else
      warn "gh could not post — copy the comment above onto the issue by hand."
      SKIPPED+=("the report comment on issue #$ISSUE")
    fi
  else
    SKIPPED+=("the report comment on issue #$ISSUE")
  fi
  pause
}

# ══ --clock ════════════════════════════════════════════════════════════════
if [[ "$MODE" == clock ]]; then
  banner "Mibo on Android — record the closed test's 14-day clock"
  clock_stage
  pause
  report_stage
  finish
  [[ -n "$CLOSED_TEST_STARTED" ]] && \
    note "Apply for production on or after $(plus_days "$CLOCK_DAYS" "$CLOSED_TEST_STARTED"): scripts/release-android.sh --production"
  printf '\n'
  exit 0
fi

# ══ --production ═══════════════════════════════════════════════════════════
if [[ "$MODE" == production ]]; then
  banner "Mibo on Android — production access, and the Production release"

  # ── 1 ─────────────────────────────────────────────────────────────────
  stage "What the closed test recorded"
  have eas  "the production channel update is an eas command"
  have jq   "the environment check reads eas.json with it"
  have curl "the store URL and the update manifest are checked with it"
  have gh   "the last stage posts onto issue #$ISSUE"
  say ""
  if [[ -z "$CLOSED_VERSION_CODE" ]]; then
    warn "No closed-test build is recorded in ${ENV_FILE#"$REPO_ROOT"/}. Run the wizard without"
    warn "flags first — or, if the closed test was run by hand, type its versionCode now."
    printf '  %sversionCode on Closed testing:%s ' "$BOLD" "$RESET"
    read -r CLOSED_VERSION_CODE || true
    CLOSED_VERSION_CODE="${CLOSED_VERSION_CODE//[[:space:]]/}"
    [[ -n "$CLOSED_VERSION_CODE" ]] && write_env CLOSED_VERSION_CODE "$CLOSED_VERSION_CODE"
  fi
  say "Closed testing carries versionCode ${BOLD}${CLOSED_VERSION_CODE:-?}${RESET} (version ${CLOSED_APP_VERSION:-?}, commit $(printf '%s' "${CLOSED_COMMIT:-?}" | cut -c1-7))."
  say ""
  if [[ -z "$CLOSED_TEST_STARTED" ]]; then
    warn "No start date is recorded for the $CLOCK_DAYS-day clock."
    clock_stage inline
  fi
  if [[ -n "$CLOSED_TEST_STARTED" ]]; then
    elapsed=$(days_since "$CLOSED_TEST_STARTED")
    if (( elapsed >= CLOCK_DAYS )); then
      if confirm "Has the dashboard shown $MIN_TESTERS+ opted in every day since $CLOSED_TEST_STARTED?"; then
        record "$CLOCK_DAYS continuous days" "$elapsed days at $MIN_TESTERS+ testers since $CLOSED_TEST_STARTED" pass
      else
        warn "Then the clock restarted. Record the new start: scripts/release-android.sh --clock"
        RESULTS+=("- [ ] $CLOCK_DAYS continuous days — the count dipped since $CLOSED_TEST_STARTED")
        report_stage; finish; exit 0
      fi
    else
      warn "Day $elapsed of $CLOCK_DAYS. Play will not offer the application until"
      warn "$(plus_days "$CLOCK_DAYS" "$CLOSED_TEST_STARTED"), unless the recorded date is wrong."
      confirm "Go on anyway (the dashboard already says the requirements are met)?" || {
        RESULTS+=("- [ ] $CLOCK_DAYS days elapsed — day $elapsed, since $CLOSED_TEST_STARTED")
        report_stage; finish; exit 0; }
    fi
  fi
  pause

  # ── 2 ─────────────────────────────────────────────────────────────────
  stage "Production access"
  granted=0
  if confirm "Has Play already granted production access (an email, and Production unlocked)?"; then
    granted=1
    RESULTS+=("- [x] Production access granted")
  elif [[ -n "$PRODUCTION_APPLIED" ]] && \
       ! confirm "Applied on $PRODUCTION_APPLIED. Was it refused, so you must apply again?"; then
    note "Google says a review takes 7 days or less. Re-run --production once the email arrives."
    RESULTS+=("- [ ] Production access — applied $PRODUCTION_APPLIED, awaiting Google's decision")
  else
    open_url_chrome "$PLAY_CONSOLE"
    say "Mibo → Dashboard → 'Apply for production'. Three sections of free text. Google"
    say "reads these for evidence of a real test, so answer from what actually happened:"
    say ""
    say "About your closed test"
    step "How easy was it to recruit testers; how they engaged; what feedback came in"
    step "and how you collected it (the Play feedback channel, email, conversations)."
    say "About your app"
    step "Intended audience: parents — the Play audience is 18+ (ADR-0018). The child"
    step "uses a paired device; the parent installs and sets up the household."
    step "How it provides value, and expected installs in the first year."
    say "Production readiness"
    step "What you changed because of the test, and how you decided it was ready."
    # Captured first: an unknown commit (another clone, a rebase) fails git log, and
    # under pipefail that would end the wizard mid-stage.
    changes=""
    [[ -n "$CLOSED_COMMIT" ]] && \
      changes=$(git -C "$REPO_ROOT" log --oneline --no-merges "$CLOSED_COMMIT..HEAD" 2>/dev/null || true)
    if [[ -n "$changes" ]]; then
      note "  Material for that answer — commits since the closed-test build:"
      printf '%s\n' "$changes" | sed -n '1,25p' | while read -r line; do note "    $line"; done
    fi
    say ""
    warn "A refusal for thin engagement means the closed test continues — the testers"
    warn "stay opted in and you apply again; nothing has to be rebuilt."
    if confirm "Submitted the application?"; then
      PRODUCTION_APPLIED=$(today)
      write_env PRODUCTION_APPLIED "$PRODUCTION_APPLIED"
      RESULTS+=("- [ ] Production access — applied $PRODUCTION_APPLIED, awaiting Google's decision")
      note "Re-run --production once Google's email says access is granted."
    else
      RESULTS+=("- [ ] Production access — application not submitted")
    fi
  fi
  pause
  if (( ! granted )); then
    report_stage
    finish
    exit 0
  fi

  # ── 3 ─────────────────────────────────────────────────────────────────
  stage "Promote the same .aab to Production"
  say "The binary the testers ran for $CLOCK_DAYS days is the one that ships: promoted, not rebuilt."
  open_url_chrome "$PLAY_CONSOLE"
  step "Test and release → Testing → Closed testing → Releases."
  step "The release carrying versionCode ${CLOSED_VERSION_CODE:-?} → Promote release → Production."
  step "Production → Countries / regions: add every country Mibo is sold in."
  step "Release notes (en-US), then Next → Save → Start rollout to Production."
  step "Publishing overview → Send changes for review, if managed publishing is on."
  warn "Do not upload a new .aab here. A rebuild carries a new versionCode nobody tested,"
  warn "and a JS fix made since the closed test belongs in the update in stage 4."
  say ""
  if [[ -n "$CLOSED_COMMIT" && "$CLOSED_COMMIT" != "$git_head" ]]; then
    note "HEAD has moved since the closed-test build. That is fine: Production gets"
    note "versionCode ${CLOSED_VERSION_CODE:-?}, built from $(printf '%s' "$CLOSED_COMMIT" | cut -c1-7)."
  fi
  check "Promoted" "versionCode ${CLOSED_VERSION_CODE:-?} is rolled out to Production (in review or live)."
  pause

  # ── 4 ─────────────────────────────────────────────────────────────────
  stage "The production channel, and its source maps"
  say "The binary's own source maps went to Sentry when EAS built it. An OTA bundle"
  say "has different debug ids, so its maps go up separately after it is published."
  printf '      %spnpm --filter @chores/shared build%s\n' "$BOLD" "$RESET"
  printf '      %scd apps/mobile && eas update --channel %s --environment %s --platform android --clear-cache --message "..."%s\n' \
    "$BOLD" "$CHANNEL" "$ENVIRONMENT" "$RESET"
  printf '      %scd apps/mobile && npx --package=@sentry/react-native sentry-expo-upload-sourcemaps dist%s\n' \
    "$BOLD" "$RESET"
  say ""
  note "--platform android because an iOS binary on version $app_version shares this runtime and"
  note "this channel: an update for both would reach iPhones with nobody watching them."
  note "Every other flag is release-ios.sh stage 8's, for the reasons written there."
  say ""
  warn "An update is instant and irreversible for anyone who fetches it. Make it a"
  warn "copy change you can SEE on the device, then change it back and publish again."
  say ""
  check "Binary source maps" "Sentry → Settings → Source Maps lists the release for $PACKAGE@${CLOSED_APP_VERSION:-$app_version}+${CLOSED_VERSION_CODE:-?}."
  if confirm "Publish an Android update to the '$CHANNEL' channel now?"; then
    say ""
    say "The environment the update bundles from:"
    check_eas_env || warn "A gap above ships an update that throws before its first screen."
    update_message=""
    printf '  %sUpdate message:%s ' "$BOLD" "$RESET"
    read -r update_message || true
    [[ -z "$update_message" ]] && update_message="verify the $CHANNEL channel on Android (#$ISSUE)"
    if ! (cd "$REPO_ROOT" && pnpm --filter @chores/shared build); then
      warn "The shared package did not build — not publishing an update carrying a stale copy."
      SKIPPED+=("pnpm --filter @chores/shared build, then re-run --production for the update")
    elif eas_mobile update --channel "$CHANNEL" --environment "$ENVIRONMENT" --platform android \
         --clear-cache --message "$update_message"; then
      printf '  %s✓ published%s\n' "$GREEN" "$RESET"
      if manifest_serves "$app_version"; then
        RESULTS+=("- [x] The $CHANNEL channel serves android on runtime $app_version")
      else
        RESULTS+=("- [ ] The $CHANNEL channel — FAILED: no android manifest for runtime $app_version")
      fi
      if [[ -z "${SENTRY_AUTH_TOKEN:-}" || -z "${SENTRY_ORG:-}" || -z "${SENTRY_PROJECT:-}" ]]; then
        warn "SENTRY_AUTH_TOKEN, SENTRY_ORG and SENTRY_PROJECT are not all set in this shell,"
        warn "so the OTA source maps were not uploaded."
        SKIPPED+=("upload the OTA source maps: SENTRY_AUTH_TOKEN=... SENTRY_ORG=... SENTRY_PROJECT=... npx --package=@sentry/react-native sentry-expo-upload-sourcemaps dist")
      elif (cd "$MOBILE" && npx --package=@sentry/react-native sentry-expo-upload-sourcemaps dist); then
        record "OTA source maps" "uploaded from apps/mobile/dist" pass
      else
        record "OTA source maps" "the upload from apps/mobile/dist" fail
      fi
    else
      warn "eas update failed — the channel is unproven."
      SKIPPED+=("eas update --channel $CHANNEL --environment $ENVIRONMENT --platform android")
    fi
  else
    SKIPPED+=("eas update --channel $CHANNEL --platform android, and its source-map upload")
  fi
  pause

  # ── 5 ─────────────────────────────────────────────────────────────────
  stage "Live on Google Play"
  say "The join-code share text links $PLAY_URL"
  play_code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "$PLAY_URL&hl=en") || play_code=000
  if [[ "$play_code" == 200 ]]; then
    record "Store URL" "$PLAY_URL resolves (HTTP 200)" pass
  else
    # Not a failure: Production review takes days, and the URL 404s until it passes.
    RESULTS+=("- [ ] Store URL — not live yet: $PLAY_URL answers HTTP $play_code")
    note "  HTTP $play_code — not live yet. Re-run --production once review passes."
  fi
  say ""
  say "On a device whose Google account is NOT a tester — a tester gets the testing track:"
  check "Install" "Mibo installs from the public Play listing and launches."
  check "Purchase" "A purchase turns the household premium, through RevenueCat (#110)."
  check "Push" "A push notification arrives on the Android device (#109)."
  check "OTA update" "The visible change from stage 4 reached the device after two launches."
  pause

  # ── 6 ─────────────────────────────────────────────────────────────────
  report_stage
  finish
  note "Testers stay on the closed track until they leave it; that does not affect Production."
  printf '\n'
  exit 0
fi

# ══ the first sitting: build, upload, testers, rollout ═════════════════════
banner "Mibo on Android — the production build and the closed test"

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Preflight"
say "1. The tools the later stages shell out to:"
have eas  "the build and the submit are eas commands"
have jq   "the environment check and the build lookup read JSON with it"
have curl "the first upload downloads the .aab with it"
have git  "check 3 reads the tree this build would be cut from"
have gh   "the last stage posts onto issue #$ISSUE"
say ""

say "2. Who EAS thinks you are:"
if eas_who=$(eas_mobile whoami 2>&1); then
  printf '  %s✓%s logged in as %s\n' "$GREEN" "$RESET" "$(printf '%s' "$eas_who" | head -1)"
else
  warn "eas whoami failed — run 'eas login'."
  SKIPPED+=("eas login")
  preflight_ok=0
fi
say ""

say "3. The tree this build would be cut from:"
git_dirty=$(git -C "$REPO_ROOT" status --porcelain 2>/dev/null || true)
printf '  %s%s%s on %s%s%s\n' "$BOLD" "$(printf '%s' "$git_head" | cut -c1-7)" "$RESET" "$BOLD" "$git_branch" "$RESET"
if [[ -n "$git_dirty" ]]; then
  warn "The tree is dirty. EAS uploads the working tree, not HEAD — this .aab is the one"
  warn "Production gets in $CLOCK_DAYS+ days, and no commit would say what was in it."
  printf '%s\n' "$git_dirty" | sed -n '1,10p' | while read -r line; do note "  $line"; done
  SKIPPED+=("commit or stash the working tree before the build in stage 3")
else
  printf '  %s✓%s clean\n' "$GREEN" "$RESET"
fi
say ""

say "4. The live API:"
if deploy_out=$("$REPO_ROOT/scripts/check-deploy.sh" "$API_BASE" 2>&1); then
  printf '  %s✓%s the live API is this commit\n' "$GREEN" "$RESET"
else
  printf '%s\n' "$deploy_out" | sed -n '1,4p' | while read -r line; do note "  $line"; done
  warn "Behind HEAD. Testers run against the live API for $CLOCK_DAYS days — redeploy"
  warn "if anything this build calls landed after it (scripts/deploy-api.sh)."
  SKIPPED+=("scripts/deploy-api.sh — the live API is behind this tree")
fi
say ""

say "5. The EAS '$ENVIRONMENT' environment — Sentry, RevenueCat, and eas.json's public vars:"
if ! check_eas_env; then
  say ""
  warn "A missing Sentry variable fails the build at its last step; a missing RevenueCat"
  warn "Android key ships a paywall with nothing to sell; a missing EXPO_PUBLIC_ one"
  warn "kills every OTA update. scripts/setup-sentry.sh and scripts/setup-premium-play.sh"
  warn "write them."
  SKIPPED+=("fill the EAS '$ENVIRONMENT' environment (see stage 1 check 5)")
  preflight_ok=0
fi
say ""

if (( preflight_ok )); then
  printf '  %s%s✓ preflight clean%s\n' "$BOLD" "$GREEN" "$RESET"
else
  warn "Preflight found something. Every item is in the summary at the end."
fi
pause "Press Enter when the preflight looks right."

# ── 2 ───────────────────────────────────────────────────────────────────
stage "The version, the runtime, and the versionCode"
say "app.json says version $app_version, and runtimeVersion uses the 'appVersion'"
say "policy, so the runtime is $app_version too: an update on the '$CHANNEL' channel"
say "reaches this binary only while it is published for $app_version."
if [[ "$app_version" == 0.* ]]; then
  warn "A 0.x version is what Play prints on the listing. Bump app.json first."
  SKIPPED+=("bump apps/mobile/app.json version out of 0.x")
fi
say ""
note "appVersionSource is 'remote' and the profile autoIncrements, so the versionCode"
note "is EAS's and the build takes the next one. Never hand-edit android.versionCode."
if version_out=$(eas_mobile build:version:get --platform android 2>&1); then
  version_line=$(printf '%s\n' "$version_out" | grep -i 'versionCode' || true)
  [[ -n "$version_line" ]] && note "  EAS holds: $version_line"
fi
pause

# ── 3 ───────────────────────────────────────────────────────────────────
stage "Build"
say "The command:"
printf '      %scd apps/mobile && eas build --platform android --profile %s%s\n' "$BOLD" "$PROFILE" "$RESET"
note "  An .aab (the production profile has no buildType), signed with the upload key"
note "  EAS holds, source maps to Sentry at the end."
say ""
build_line=$(latest_build)
reuse=0
if [[ -n "$build_line" && -z "$git_dirty" ]]; then
  IFS=$'\t' read -r b_id b_vc b_ver b_commit _ <<<"$build_line"
  if [[ "$b_commit" == "$git_head" && "$b_ver" == "$app_version" ]]; then
    note "A finished $PROFILE build of this exact commit exists: versionCode $b_vc ($b_id)."
    confirm "Use it instead of building again?" && reuse=1
  fi
fi
if (( ! reuse )); then
  if confirm "Start the build now? (twenty to forty minutes; it streams here)"; then
    if eas_mobile build --platform android --profile "$PROFILE"; then
      printf '  %s✓ build finished%s\n' "$GREEN" "$RESET"
      build_line=$(latest_build)
    else
      warn "The build failed — the log URL above says where. Stage 1 check 5 is the usual cause."
      build_line=""
    fi
  else
    note "Not started. Build in another terminal, then re-run this wizard — it offers"
    note "a finished build of HEAD instead of building again."
    SKIPPED+=("eas build --platform android --profile $PROFILE")
    build_line=""
  fi
fi
if [[ -n "$build_line" ]]; then
  IFS=$'\t' read -r CLOSED_BUILD_ID CLOSED_VERSION_CODE CLOSED_APP_VERSION CLOSED_COMMIT ARCHIVE_URL <<<"$build_line"
  write_env CLOSED_BUILD_ID "$CLOSED_BUILD_ID"
  write_env CLOSED_VERSION_CODE "$CLOSED_VERSION_CODE"
  write_env CLOSED_APP_VERSION "$CLOSED_APP_VERSION"
  write_env CLOSED_COMMIT "$CLOSED_COMMIT"
  RESULTS+=("- [x] Production build — versionCode $CLOSED_VERSION_CODE, version $CLOSED_APP_VERSION, EAS build $CLOSED_BUILD_ID")
else
  # Forget the previous sitting's build too: stage 4 must not upload what this run did
  # not build or choose. The file keeps it until a new build replaces it.
  CLOSED_BUILD_ID=""; CLOSED_VERSION_CODE=""; CLOSED_APP_VERSION=""; CLOSED_COMMIT=""
  ARCHIVE_URL=""
  RESULTS+=("- [ ] Production build — none finished this run")
fi
pause

# ── 4 ───────────────────────────────────────────────────────────────────
stage "Upload to Closed testing"
say "eas.json's submit profile sends to the 'alpha' track — Play's Closed testing —"
say "as a draft, which stage 6 rolls out. But Play refuses an API upload for an app"
say "that has never received a bundle, so the very first one goes through the Console."
say ""
if [[ -z "$CLOSED_BUILD_ID" ]]; then
  warn "No build to upload. Re-run once one has finished."
  SKIPPED+=("upload the .aab to Closed testing")
elif confirm "Has Play ever received an .aab for $PACKAGE — internal testing (#103) counts?"; then
  printf '      %scd apps/mobile && eas submit --platform android --profile %s --id %s%s\n' \
    "$BOLD" "$PROFILE" "$CLOSED_BUILD_ID" "$RESET"
  note "  --id, not --latest: the build recorded above, so the one tested is the one promoted."
  if eas_mobile submit --platform android --profile "$PROFILE" --id "$CLOSED_BUILD_ID"; then
    record "Upload" "versionCode $CLOSED_VERSION_CODE is a draft on Closed testing (eas submit)" pass
  else
    warn "A refused submit is usually the service account (setup-premium-play.sh stage 7)"
    warn "lacking release permission, or a versionCode Play already has."
    record "Upload" "eas submit of versionCode $CLOSED_VERSION_CODE" fail
  fi
else
  aab_dir=$(mktemp -d)
  aab="$aab_dir/mibo-$CLOSED_VERSION_CODE.aab"
  if [[ -n "$ARCHIVE_URL" ]] && curl -fsSL --max-time 300 -o "$aab" "$ARCHIVE_URL"; then
    printf '  %s✓ downloaded%s %s\n' "$GREEN" "$RESET" "$aab"
  else
    warn "Could not download it — take the .aab from the build page on expo.dev."
    open_url_chrome "https://expo.dev/accounts/$(jq -r '.expo.owner' "$APP_JSON")/projects/$(jq -r '.expo.slug' "$APP_JSON")/builds/$CLOSED_BUILD_ID"
  fi
  open_url_chrome "$PLAY_CONSOLE"
  step "Mibo → Test and release → Testing → Closed testing → Create release."
  step "Upload $aab — Play binds $PACKAGE on the first bundle."
  step "Release notes (en-US): First closed test of Mibo."
  step "Next → Save. Do not roll out yet; stage 6 does, once the testers exist."
  check "Upload" "versionCode $CLOSED_VERSION_CODE is saved as a Closed testing release."
fi
pause

# ── 5 ───────────────────────────────────────────────────────────────────
stage "Testers — a Google Group on the closed track"
say "A Google Group rather than an email list: testers join it themselves, and the"
say "track follows the group's membership without a Console edit per person."
open_url_chrome "https://groups.google.com/my-groups"
step "Create group — e.g. mibo-testers. Who can join: anyone can ask, or anyone can join."
step "Who can see members: group managers only — the testers' addresses are personal."
say ""
ask TESTER_GROUP "The group's address (…@googlegroups.com):"
TESTER_GROUP="${TESTER_GROUP//[[:space:]]/}"
if [[ "$TESTER_GROUP" == *@* ]]; then
  write_env TESTER_GROUP "$TESTER_GROUP"
else
  warn "Not an address — not saved."
  SKIPPED+=("the tester Google Group's address")
fi
say ""
open_url_chrome "$PLAY_CONSOLE"
step "Closed testing → the track → Testers → Google Groups → add ${TESTER_GROUP:-the group} → Save."
step "Feedback URL or email address: the support address from the store listing."
step "Countries / regions: every country a tester is in."
say ""
say "Recruit at least $MIN_TESTERS, aim for $AIM_TESTERS or more. Each tester, on the phone's Google account:"
step "joins ${TESTER_GROUP:-the group}, then opens $OPT_IN_URL"
step "→ 'Become a tester' → installs Mibo from Play, and keeps it installed."
note "  The opt-in link answers only once stage 6's release is reviewed and live."
check "Testers" "The closed track lists ${TESTER_GROUP:-the group}, and the opt-in link has been shared."
pause

# ── 6 ───────────────────────────────────────────────────────────────────
stage "Roll out to Closed testing, and try it on a device"
open_url_chrome "$PLAY_CONSOLE"
step "Closed testing → Releases → versionCode ${CLOSED_VERSION_CODE:-?} → Edit → Next."
step "Start rollout to Closed testing."
step "Publishing overview → Send changes for review, if managed publishing is on."
note "  Google reviews a closed release too — hours, sometimes days. Testers see"
note "  nothing until it passes."
say ""
check "Rollout" "versionCode ${CLOSED_VERSION_CODE:-?} is rolled out to Closed testing."
say ""
say "Once it is reviewed, on your own phone through the opt-in link:"
check "Install" "Mibo installs from Play via $OPT_IN_URL and launches."
check "Sign in" "A parent signs in with Google and lands in parent mode."
check "Paywall" "The paywall shows the three Play prices (#110)."
check "Push" "A push notification arrives (#109)."
pause

# ── 7 ───────────────────────────────────────────────────────────────────
clock_stage
pause

# ── 8 ───────────────────────────────────────────────────────────────────
report_stage
finish
if [[ -n "$CLOSED_TEST_STARTED" ]]; then
  note "Apply for production on or after $(plus_days "$CLOCK_DAYS" "$CLOSED_TEST_STARTED"):"
else
  note "Once $MIN_TESTERS testers are opted in: scripts/release-android.sh --clock. $CLOCK_DAYS days after that:"
fi
note "  scripts/release-android.sh --production"
printf '\n'
