#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES — M7.3 Play subscriptions, RevenueCat Android key, service account and RTDN (issue #110).
# ──────────────────────────────────────────────────────────────────────────
#
# The Android half of scripts/setup-premium.sh: that wizard's stages 5-9 are App Store
# Connect only. The RevenueCat project, entitlement `premium`, offering `default` and the
# webhook it set up are reused here, not recreated — Play products join the same packages.

TOTAL_STAGES=15

# open_url override — the library opens the default browser, which here is Arc.
# These dashboards are worked in Chrome, so target it by name and fall back to
# the library's behaviour if it is not installed.
BROWSER_APP="${BROWSER_APP:-Google Chrome}"
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s %s(%s)%s\n' "$GREEN" "$RESET" "$url" "$DIM" "$BROWSER_APP" "$RESET"
  if [[ "$OSTYPE" == darwin* ]] && open -a "$BROWSER_APP" "$url" >/dev/null 2>&1; then
    return
  fi
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser - visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser - visit it manually: $url"
}

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
MOBILE_DIR="$REPO_ROOT/apps/mobile"
MOBILE_ENV="$MOBILE_DIR/.env"
API_BASE="https://mibokids.app"
PACKAGE="com.mibokids.app"
PLAY_CONSOLE="https://play.google.com/console"
RC_PROJECTS="https://app.revenuecat.com/projects"
ISSUE=110

# The Play product ids are fixed by docs/spec/05-store-listing.md → Google Play. RevenueCat
# names a subscription base plan `<subscription>:<base plan>`.
SUBSCRIPTION_ID="premium"
LIFETIME_ID="premium_lifetime"
RC_PLAY_MONTHLY="$SUBSCRIPTION_ID:monthly"
RC_PLAY_ANNUAL="$SUBSCRIPTION_ID:annual"

# Remembered between runs; nothing secret goes in here — the service-account key is only
# ever referenced by its path, never copied. The parent email is personal, which is why
# the file is ignored.
WIZARD_ENV="$REPO_ROOT/scripts/.env.setup-premium-play"   # ignored by .gitignore's .env.*
ENV_FILE="$WIZARD_ENV"

RESULTS=()

# check "label" "what the tester should see" — record a pass/fail for the issue comment.
check() {
  local label="$1" expectation="$2" reply=""
  step "$expectation"
  printf '  %s? %s — did that happen? [y/n/Enter = not yet]%s ' "$YELLOW" "$label" "$RESET"
  read -r reply || true
  case "$reply" in
    [Yy]*)
      RESULTS+=("- [x] $label — $expectation")
      printf '  %s✓ recorded as passing%s\n' "$GREEN" "$RESET" ;;
    [Nn]*)
      RESULTS+=("- [ ] $label — FAILED: $expectation")
      printf '  %s✗ recorded as failing%s\n' "$RED" "$RESET" ;;
    *)
      RESULTS+=("- [ ] $label — not yet run: $expectation")
      printf '  %s· recorded as not yet run%s\n' "$DIM" "$RESET" ;;
  esac
}

# record "label" "outcome" pass|fail — a result the wizard measured itself.
record() {
  if [[ "$3" == pass ]]; then
    RESULTS+=("- [x] $1 — $2")
    printf '  %s✓ %s%s\n' "$GREEN" "$2" "$RESET"
  else
    RESULTS+=("- [ ] $1 — FAILED: $2")
    printf '  %s✗ %s%s\n' "$RED" "$2" "$RESET"
  fi
}

# expand_path "~/x" — the path with a leading ~ resolved; `read` leaves it literal.
expand_path() { local p="$1"; printf '%s' "${p/#\~/$HOME}"; }

# `railway run` injects the api service's variables. DATABASE_URL among them is
# the private-network host, unreachable from a laptop; DATABASE_PUBLIC_URL is the
# proxy that resolves (same reasoning as scripts/device-hand-tests.sh).
_psql_at() {
  cd "$REPO_ROOT" && railway run --service api -- sh -c "psql -At \"\${DATABASE_PUBLIC_URL:-\$DATABASE_URL}\" -c \"$1\""
}

banner "Mibo premium on Android — Play products, service account, RTDN, RevenueCat, EAS"

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools the later stages shell out to."
missing=0
for tool in curl jq eas railway psql gh; do
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$tool"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$tool"
    missing=1
  fi
done
if (( missing )); then
  warn "Install the missing tools first — stages 10, 13, 14 and 15 need them."
  confirm "Continue anyway?" || exit 1
fi
say ""
if eas_user=$(cd "$MOBILE_DIR" && eas whoami 2>/dev/null); then
  printf '  %s✓%s EAS signed in as %s\n' "$GREEN" "$RESET" "$(printf '%s' "$eas_user" | head -n1)"
else
  warn "eas whoami failed — run 'eas login' in another terminal before stage 10."
fi
say ""
say "Checking the live API is *this* commit (the webhook in stage 14 lands on it):"
if ! "$REPO_ROOT/scripts/check-deploy.sh" "$API_BASE"; then
  warn "The live API is behind this working tree."
  confirm "Continue anyway?" || exit 1
fi
say ""
note "This wizard assumes scripts/setup-premium.sh already ran: the RevenueCat project,"
note "entitlement 'premium', offering 'default' and the webhook all exist."
pause "Press Enter when the tooling looks right."

# ── 2 ───────────────────────────────────────────────────────────────────
stage "Play Console — a build with the billing permission on a track"
say "Play will not let you create a single product until an .aab that declares"
say "com.android.vending.BILLING has been uploaded to some track. react-native-purchases"
say "adds that permission to every build, so any production .aab qualifies."
say ""
step "If Mibo already has a release on Internal testing, you are done here."
step "If not, make one first:"
note "  · scripts/setup-play-listing.sh stage 9 walks the first internal-testing upload;"
note "  · #114's first upload would also do, but #114 is blocked by this ticket — so in"
note "    practice it is the internal-testing upload."
note "  The build can come before the RevenueCat key — the products only need Play to"
note "  have seen the permission. Stage 13 builds again with the key inside."
warn "Do not strip BILLING in #113's blocked permissions: the paywall dies with it."
open_url "$PLAY_CONSOLE"
if ! confirm "Is an .aab of $PACKAGE uploaded to any track?"; then
  SKIPPED+=("an .aab on a Play track — stages 4 and 5 cannot create products until one exists")
  warn "Noted. Stages 4 and 5 will be greyed out in Play until it is."
fi
pause

# ── 3 ───────────────────────────────────────────────────────────────────
stage "Play Console — payments profile"
say "Selling anything needs a merchant account linked to the developer account."
open_url "$PLAY_CONSOLE"
step "Settings (left rail, account level) → Payments profile."
step "If it offers 'Create payments profile', create one: business name, address, bank."
note "  Bank verification takes a few days. Products can be set up meanwhile; nobody"
note "  can be charged until it clears — license testers in stage 12 are never charged."
if ! confirm "Is a payments profile linked?"; then
  SKIPPED+=("a Play payments profile — real purchases fail until it is linked")
fi
pause

# ── 4 ───────────────────────────────────────────────────────────────────
stage "Play Console — the subscription '$SUBSCRIPTION_ID' and its two base plans"
say "One subscription, two base plans. Prices are fixed by ADR-0005 and match iOS."
open_url "$PLAY_CONSOLE"
step "Mibo → Monetize with Play → Products → Subscriptions → Create subscription."
step "Product ID: $SUBSCRIPTION_ID        ← exactly this; it can never be changed or reused."
step "Name: Mibo Premium. Save, then fill the benefits/description and save again."
say ""
step "Add base plan → Base plan ID: monthly"
note "  Type: Auto-renewing · Billing period: 1 month · Grace period: Play's default."
step "  Set prices → select all countries → \$6.99 USD → 'Update' to convert the rest."
step "  Save → Activate."
say ""
step "Add base plan → Base plan ID: annual"
note "  Type: Auto-renewing · Billing period: 1 year."
step "  Set prices → all countries → \$39.99 USD → convert. Save → Activate."
say ""
warn "No offers and no free trial — on neither base plan. iOS has none either."
note "Countries: the same as App Store Connect → Pricing and Availability. Play converts"
note "the USD price per country; leave the converted prices as they come."
pause "Press Enter once both base plans read Active."

# ── 5 ───────────────────────────────────────────────────────────────────
stage "Play Console — the one-time product '$LIFETIME_ID'"
open_url "$PLAY_CONSOLE"
step "Monetize with Play → Products → One-time products → Create one-time product."
step "Product ID: $LIFETIME_ID        ← exactly this."
step "Name: Mibo Premium Lifetime. Description: one line is enough."
step "Purchase option: Buy, \$79.99 USD in all countries, converted. Save → Activate."
note "  Leave it non-repeatable / one per user if the form asks — it is a lifetime unlock."
say ""
note "RevenueCat sends a Play one-time purchase as NON_RENEWING_PURCHASE with no"
note "expiry, which is the only shape apps/api/src/revenuecat.ts treats as permanent"
note "(ADR-0016). It stays that way only if RevenueCat never consumes it — stage 11."
check "Play products active" "In Play Console, $SUBSCRIPTION_ID (base plans monthly and annual) and $LIFETIME_ID all read Active."
pause

# ── 6 ───────────────────────────────────────────────────────────────────
stage "Google Cloud — the RevenueCat service account"
say "RevenueCat verifies Play purchases and listens for notifications with a service"
say "account in a Google Cloud project. Mibo's Firebase project (setup-fcm.sh) is a"
say "fine home; any project you own works."
GCP_DEFAULT=$(ENV_FILE="$REPO_ROOT/scripts/.env.setup-fcm" _existing FIREBASE_PROJECT_ID || true)
[[ -n "$GCP_DEFAULT" ]] && note "Firebase project from setup-fcm.sh: $GCP_DEFAULT"
ask GCP_PROJECT_ID "Google Cloud project id to use${GCP_DEFAULT:+ [$GCP_DEFAULT]}:"
GCP_PROJECT_ID="${GCP_PROJECT_ID:-$GCP_DEFAULT}"
GCP_PROJECT_ID="${GCP_PROJECT_ID//[[:space:]]/}"
[[ -n "$GCP_PROJECT_ID" ]] && write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
say ""
step "Enable three APIs (each page says 'Manage' once it is on):"
open_url "https://console.cloud.google.com/apis/library/androidpublisher.googleapis.com?project=${GCP_PROJECT_ID:-_}"
open_url "https://console.cloud.google.com/apis/library/playdeveloperreporting.googleapis.com?project=${GCP_PROJECT_ID:-_}"
open_url "https://console.cloud.google.com/apis/library/pubsub.googleapis.com?project=${GCP_PROJECT_ID:-_}"
pause "Press Enter once all three are enabled."
say ""
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts/create?project=${GCP_PROJECT_ID:-_}"
step "Name: revenuecat · Create and continue."
step "Roles: Pub/Sub Editor, and Monitoring Viewer. Done."
step "Open it → Keys → Add key → Create new key → JSON. A file downloads."
step "Move it OUT of Downloads, somewhere private — not under $REPO_ROOT."
note "  If key creation is refused, an org policy (iam.disableServiceAccountKeyCreation)"
note "  blocks it — lift it for this project under IAM & Admin → Organization policies."
say ""
SA_KEY=""
SA_EMAIL=""
while :; do
  ask SA_KEY_PATH "Path to the service-account key JSON:"
  SA_KEY=$(expand_path "${SA_KEY_PATH:-}")
  if [[ ! -f "$SA_KEY" ]]; then
    warn "No file at '$SA_KEY'."
  elif [[ "$(cd -- "$(dirname -- "$SA_KEY")" && pwd)/" == "$REPO_ROOT/"* ]]; then
    warn "That file is inside the repo. Move it out — one 'git add .' and it is public."
  elif ! jq -e '.type == "service_account"' "$SA_KEY" >/dev/null 2>&1; then
    warn "That is not a service-account key (no \"type\": \"service_account\")."
  elif [[ -n "$GCP_PROJECT_ID" ]] && [[ "$(jq -r '.project_id' "$SA_KEY")" != "$GCP_PROJECT_ID" ]]; then
    warn "The key belongs to project '$(jq -r '.project_id' "$SA_KEY")', not '$GCP_PROJECT_ID'."
    note "  RevenueCat creates its Pub/Sub topic in the key's project, where the APIs above"
    note "  must be on."
  else
    write_env SA_KEY_PATH "$SA_KEY_PATH"
    SA_EMAIL=$(jq -r '.client_email' "$SA_KEY")
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$SA_EMAIL"
    break
  fi
  confirm "Try another path?" || { SKIPPED+=("the RevenueCat service-account key"); SA_KEY=""; break; }
done
pause

# ── 7 ───────────────────────────────────────────────────────────────────
stage "Play Console — invite the service account"
say "The key alone can do nothing in Play until the account is a Play Console user."
open_url "$PLAY_CONSOLE"
step "Users and permissions (left rail, account level) → Invite new users → Email address:"
printf '      %s%s%s\n' "$BOLD" "${SA_EMAIL:-<client_email from the key>}" "$RESET"
step "App permissions → Add app → Mibo."
step "Account permissions — these four, at least:"
note "  · View app information and download bulk reports (read-only)"
note "  · View financial data, orders, and cancellation survey responses"
note "  · Manage orders and subscriptions"
note "  · Manage store presence      (under Store presence — RevenueCat imports with it)"
step "Invite user. It should list as Active straight away."
pause "Press Enter once the service account is an active user."

# ── 8 ───────────────────────────────────────────────────────────────────
stage "RevenueCat — the Play Store app and its credentials"
open_url "$RC_PROJECTS"
step "Project Mibo → Apps & providers → the Play Store app for $PACKAGE."
note "  None yet? + New → Play Store → package name $PACKAGE."
step "Service Account Credentials JSON → upload:"
printf '      %s%s%s\n' "$BOLD" "${SA_KEY:-<the key from stage 6>}" "$RESET"
step "Save. The credentials row shows a status."
say ""
warn "Google takes up to 36 hours to honour a new service account. Until then RevenueCat"
warn "shows the credentials as invalid and every later stage that talks to Google fails."
note "Known nudge: in Play Console, edit any product's description (stage 5's will do),"
note "save, and change it back — that often makes Google validate the account within minutes."
check "Credentials valid" "RevenueCat shows the Play service-account credentials as valid (green)."
pause

# ── 9 ───────────────────────────────────────────────────────────────────
stage "RevenueCat — real-time developer notifications"
say "Play tells RevenueCat about renewals, cancellations and refunds through a Pub/Sub"
say "topic. RevenueCat then calls our webhook — it stays the only entitlement writer"
say "(ADR-0016); nothing in Mibo ever reads Play directly."
open_url "$RC_PROJECTS"
step "Play Store app → Google developer notifications → Connect to Google."
note "  RevenueCat creates the topic in the key's project. If it errors on permissions,"
note "  the roles in stage 6 are wrong — fix them, make a NEW key, re-upload it."
step "Copy the topic id it shows (projects/<project>/topics/<name>)."
ask RTDN_TOPIC "Paste the topic id:"
RTDN_TOPIC="${RTDN_TOPIC//[[:space:]]/}"
[[ -n "$RTDN_TOPIC" ]] && write_env RTDN_TOPIC "$RTDN_TOPIC"
say ""
open_url "$PLAY_CONSOLE"
step "Mibo → Monetize with Play → Monetization setup → Real-time developer notifications."
step "Enable, Topic name:"
printf '      %s%s%s\n' "$BOLD" "${RTDN_TOPIC:-<the topic id>}" "$RESET"
step "Notification content: Subscriptions, voided purchases, and all one-time products."
step "Save changes (bottom right) → Send test notification."
say ""
step "Back in RevenueCat, the developer-notifications row shows 'Last received' just now."
note "No timestamp? Grant google-play-developer-notifications@system.gserviceaccount.com"
note "the Pub/Sub Publisher role on that topic (Cloud console → Pub/Sub → topic →"
note "Permissions), then send the test again."
open_url "https://console.cloud.google.com/cloudpubsub/topic/list?project=${GCP_PROJECT_ID:-_}"
check "RTDN test" "RevenueCat received Play's test notification (a fresh 'Last received')."
pause

# ── 10 ──────────────────────────────────────────────────────────────────
stage "RevenueCat — the Android SDK key, locally and on EAS"
say "apps/mobile/src/lib/purchases.ts reads EXPO_PUBLIC_REVENUECAT_ANDROID_KEY; without it"
say "every Android paywall fails 'RevenueCat is not configured for this build'."
open_url "$RC_PROJECTS"
step "API keys (left sidebar, low down) → copy the Play Store key — it starts 'goog_'."
ENV_FILE="$MOBILE_ENV"
ask EXPO_PUBLIC_REVENUECAT_ANDROID_KEY "Paste the Android (goog_) key:"
EXPO_PUBLIC_REVENUECAT_ANDROID_KEY="${EXPO_PUBLIC_REVENUECAT_ANDROID_KEY//[[:space:]]/}"
if [[ "$EXPO_PUBLIC_REVENUECAT_ANDROID_KEY" != goog_* ]]; then
  if [[ -n "$EXPO_PUBLIC_REVENUECAT_ANDROID_KEY" ]]; then
    warn "That does not start with goog_ — an appl_ key on Android is rejected by the SDK."
  else
    warn "No key captured."
  fi
  SKIPPED+=("EXPO_PUBLIC_REVENUECAT_ANDROID_KEY in apps/mobile/.env and EAS production")
else
  write_env EXPO_PUBLIC_REVENUECAT_ANDROID_KEY "$EXPO_PUBLIC_REVENUECAT_ANDROID_KEY"
  # Public SDK key: inlined into every APK, so plaintext rather than sensitive.
  if (cd "$MOBILE_DIR" && eas env:set production --name EXPO_PUBLIC_REVENUECAT_ANDROID_KEY \
      --value "$EXPO_PUBLIC_REVENUECAT_ANDROID_KEY" --visibility plaintext --non-interactive) >/dev/null 2>&1; then
    printf '  %s✓ set%s EAS production EXPO_PUBLIC_REVENUECAT_ANDROID_KEY\n' "$GREEN" "$RESET"
  else
    warn "eas env:set failed — set it on expo.dev → Environment variables → production."
    SKIPPED+=("EAS production EXPO_PUBLIC_REVENUECAT_ANDROID_KEY")
  fi
fi
ENV_FILE="$WIZARD_ENV"
say ""
say "What EAS production holds now:"
# Captured first: under pipefail a grep with no match would read as eas failing.
if eas_vars=$(cd "$MOBILE_DIR" && eas env:list production 2>/dev/null); then
  printf '%s\n' "$eas_vars" | grep -E 'REVENUECAT' | sed 's/=.*/=…/; s/^/    /' \
    || note "    (no REVENUECAT variables)"
else
  warn "eas env:list failed."
fi
note "The iOS key should be there too; if it is not, the App Store build is broken"
note "in the same way and setup-premium.sh stage 4 never reached EAS."
pause

# ── 11 ──────────────────────────────────────────────────────────────────
stage "RevenueCat — import the Play products"
say "Needs the credentials from stage 8 to be valid: import reads them from Google."
open_url "$RC_PROJECTS"
step "Product catalog → Products → + New → Play Store app → Import."
step "Select all three:"
note "  $RC_PLAY_MONTHLY"
note "  $RC_PLAY_ANNUAL"
note "  $LIFETIME_ID"
note "  (RevenueCat names a base plan <subscription>:<base plan>.)"
say ""
step "Open $LIFETIME_ID → Edit → type: Non-consumable. Save."
warn "Left as a consumable, RevenueCat consumes the purchase: Play lets the parent buy"
warn "lifetime again, and Restore after a reinstall finds nothing on Android."
check "Products valid" "RevenueCat lists $RC_PLAY_MONTHLY, $RC_PLAY_ANNUAL and $LIFETIME_ID (non-consumable), each without a warning."
pause

# ── 12 ──────────────────────────────────────────────────────────────────
stage "RevenueCat — entitlement and offering"
say "The Play products join what setup-premium.sh made; nothing new is created."
open_url "$RC_PROJECTS"
step "Product catalog → Entitlements → premium → Attach: all three Play products."
note "  'premium', lowercase — the server and the app compare it literally."
step "Product catalog → Offerings → default (Current) → each package → Edit:"
note "  Monthly  (type MONTHLY)   → Play Store: $RC_PLAY_MONTHLY"
note "  Annual   (type ANNUAL)    → Play Store: $RC_PLAY_ANNUAL"
note "  Lifetime (type LIFETIME)  → Play Store: $LIFETIME_ID"
say ""
note "premiumPackages() requires exactly those three package types to resolve. A"
note "package with no Play product is dropped on Android and the paywall throws"
note "'must contain three products'."
pause "Press Enter once each of the three packages has its Play product."

# ── 13 ──────────────────────────────────────────────────────────────────
stage "Play Console — license testers, and a build that carries the key"
say "License testers buy for free, and their subscriptions renew every few minutes."
open_url "$PLAY_CONSOLE"
step "Settings (account level) → License testing → add the Google account on the test phone."
step "License response: RESPOND_NORMALLY. Save."
note "  The same account must be a tester on Internal testing, and the phone's Play"
note "  Store must be signed in with it."
say ""
say "EXPO_PUBLIC_* values are inlined at build time, so only a build made after stage"
say "10 has the goog_ key. Build, then upload to Internal testing as in setup-fcm.sh."
if confirm "Start 'eas build -p android --profile production' now?"; then
  (cd "$MOBILE_DIR" && eas build --platform android --profile production) \
    || { warn "The build failed — read the EAS log before carrying on."; SKIPPED+=("production Android build with the RevenueCat key"); }
else
  note "Run it yourself: cd apps/mobile && eas build --platform android --profile production"
fi
open_url "$PLAY_CONSOLE"
step "Internal testing → Create new release → upload the .aab → Start rollout."
step "On the phone: update Mibo from Play (not sideloaded — billing needs the Play install)."
pause "Press Enter once the new build is installed on the phone."

# ── 14 ──────────────────────────────────────────────────────────────────
stage "Device test — paywall, purchase, webhook, restore"
say "Sign in as a parent of a FREE household and hit any premium gate."
check "Three packages" "The paywall shows three prices — annual, monthly, lifetime — in the phone's currency."
# Only events after this instant count, so a Play event from an earlier run cannot pass.
PURCHASE_STARTED=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
step "Buy Monthly. Play's sheet says it is a test purchase and charges nothing."
note "  A test subscription renews every 5 minutes and stops after six renewals; its"
note "  EXPIRATION then flips the household back to free. That is correct, not a bug."
pause "Press Enter once the purchase sheet closed with success."
say ""
say "Reading the household from the live database, so the check is the webhook's work"
say "and not anything the app wrote."
while :; do
  ask PARENT_EMAIL "Email of the parent who bought (blank skips the check):"
  # Lower-cased as the server stores it, and matched against a strict pattern so
  # nothing typed here can carry SQL or shell through the quoting to psql.
  PARENT_EMAIL=$(printf '%s' "$PARENT_EMAIL" | tr '[:upper:]' '[:lower:]')
  [[ -z "$PARENT_EMAIL" ]] && break
  if [[ "$PARENT_EMAIL" =~ ^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]+$ ]]; then
    write_env PARENT_EMAIL "$PARENT_EMAIL"
    break
  fi
  warn "That does not look like an email."
done
# The latest Play event from this run, provided it left the household premium.
WEBHOOK_SQL="select e.type from revenuecat_events e join households h on h.id = e.household_id join parents p on p.household_id = h.id where p.email = '$PARENT_EMAIL' and h.entitlement = 'premium' and e.payload->'event'->>'store' = 'PLAY_STORE' and e.received_at >= '$PURCHASE_STARTED' order by e.received_at desc limit 1;"
webhook_event=""
if [[ -z "$PARENT_EMAIL" ]]; then
  RESULTS+=("- [ ] Webhook flips household — not yet run")
elif ! command -v railway >/dev/null 2>&1 || ! command -v psql >/dev/null 2>&1; then
  warn "railway or psql missing — cannot read the household."
  RESULTS+=("- [ ] Webhook flips household — not yet run: railway or psql missing")
else
  for _ in 1 2 3 4 5 6; do
    webhook_event=$(_psql_at "$WEBHOOK_SQL" 2>/dev/null | tail -n1 || true)
    [[ -n "$webhook_event" ]] && break
    note "  not yet — waiting 5s for the webhook"
    sleep 5
  done
  # The email stays out of the outcome: it is posted to a public issue.
  if [[ -n "$webhook_event" ]]; then
    record "Webhook flips household" "A Play test purchase reached the webhook ($webhook_event) and the buyer's household is premium." pass
  else
    record "Webhook flips household" "No Play event since $PURCHASE_STARTED left the buyer's household premium." fail
    note "Check, in order: RevenueCat → Customers → the Clerk user id shows the purchase;"
    note "Integrations → Webhooks → the delivery and its HTTP status; Railway logs for"
    note "/webhooks/revenuecat. License-tester purchases arrive as SANDBOX, so the webhook"
    note "must send Sandbox events (setup-premium.sh stage 10 sets both)."
  fi
fi
check "Premium without restart" "Premium unlocks in the running app — no force-quit needed."
check "Restore" "Uninstall, reinstall from Play, sign in as the same parent, Restore Purchases → premium returns."
pause

# ── 15 ──────────────────────────────────────────────────────────────────
stage "Report back to issue #$ISSUE"
say "Posting the results as a comment."
if (( ${#RESULTS[@]} == 0 )); then
  warn "No results recorded — nothing to report."
  SKIPPED+=("the results comment on issue #$ISSUE")
  finish
  exit 0
fi
# shellcheck disable=SC2016  # the backticks are Markdown for the issue comment
comment=$(printf '## Play premium setup results\n\nRun via `scripts/setup-premium-play.sh` on %s.\n\n%s\n' \
  "$(date -u '+%Y-%m-%d %H:%M UTC')" "$(printf '%s\n' "${RESULTS[@]}")")
printf '\n%s\n\n' "$comment"
if confirm "Post this to issue #$ISSUE?"; then
  if printf '%s' "$comment" | gh issue comment "$ISSUE" --body-file - >/dev/null 2>&1; then
    printf '  %s✓ posted%s to issue #%s\n' "$GREEN" "$RESET" "$ISSUE"
  else
    warn "gh could not post — copy the comment above onto the issue by hand."
    SKIPPED+=("the results comment on issue #$ISSUE")
  fi
else
  SKIPPED+=("the results comment on issue #$ISSUE")
fi
pause

finish
