#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES — the two credential uploads left over from issue #75.
#
#   1. The App Store Connect API key. Distinct from the In-App Purchase key
#      already uploaded: that one verifies receipts, this one reads App Store
#      Connect on your behalf. Without it RevenueCat cannot import products or
#      sync their prices, so the catalog shows "Could not check".
#   2. The Apple server-to-server notification URL, which is what makes an
#      expiry or a refund reach the webhook promptly instead of waiting for
#      RevenueCat's next receipt recheck — the path #62 exercises when it
#      re-locks a household.
#
# Purchases work without either. Nothing here touches the app's code.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# open_url override — same as setup-premium.sh: these dashboards live in Chrome.
BROWSER_APP="${BROWSER_APP:-Google Chrome}"
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s %s(%s)%s\n' "$GREEN" "$RESET" "$url" "$DIM" "$BROWSER_APP" "$RESET"
  if [[ "$OSTYPE" == darwin* ]] && open -a "$BROWSER_APP" "$url" >/dev/null 2>&1; then
    return
  fi
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser - visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser - visit it manually: $url"
}

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
MOBILE_ENV="$REPO_ROOT/apps/mobile/.env"
BUNDLE_ID="com.mibokids.app"
KEY_STORE="$HOME/.appstoreconnect/private_keys"
ENV_FILE="$MOBILE_ENV"

banner "Mibo — App Store Connect API key and Apple server notifications"

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Create the App Store Connect API key"
say "A team key, not the In-App Purchase key you already uploaded. Both keys"
say "share one Issuer ID, so the page may already show it."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Users and Access → Integrations → App Store Connect API → Team Keys."
step "+ → Name it 'RevenueCat'. Access: App Manager."
note "  App Manager is the minimum RevenueCat accepts. Admin also works;"
note "  Developer, Finance and Sales do not."
step "Generate, then Download the key — a file named AuthKey_XXXXXXXXXX.p8."
warn "Apple lets you download it exactly once. If you lose it, the key is dead"
warn "and you revoke it and make another."
step "Copy the Issuer ID from above the key table, and the Key ID from the row."
pause "Press Enter once the key is downloaded."

# ── 2 ───────────────────────────────────────────────────────────────────
stage "Park the .p8 somewhere it will survive"
say "Downloads is not a safe home for a key that cannot be re-downloaded."
say "$KEY_STORE is where fastlane and EAS look, and is outside the repo."
say ""
ask ASC_KEY_PATH "Path to the downloaded .p8 (drag the file in, or Enter to skip):"
ASC_KEY_PATH="${ASC_KEY_PATH%\'}"; ASC_KEY_PATH="${ASC_KEY_PATH#\'}"   # strip drag-and-drop quoting
ASC_KEY_PATH="${ASC_KEY_PATH/#\~/$HOME}"
if [[ -n "$ASC_KEY_PATH" && -f "$ASC_KEY_PATH" ]]; then
  mkdir -p "$KEY_STORE"
  chmod 700 "$KEY_STORE"
  if [[ "$(cd -- "$(dirname -- "$ASC_KEY_PATH")" && pwd)" != "$KEY_STORE" ]]; then
    cp "$ASC_KEY_PATH" "$KEY_STORE/"
    printf '  %s✓ copied%s %s → %s\n' "$GREEN" "$RESET" "$(basename "$ASC_KEY_PATH")" "$KEY_STORE"
  else
    note "already in $KEY_STORE — left alone."
  fi
  chmod 600 "$KEY_STORE/$(basename "$ASC_KEY_PATH")"
  ASC_KEY_PATH="$KEY_STORE/$(basename "$ASC_KEY_PATH")"
  note "The repo ignores *.p8, but the key belongs outside it regardless."
else
  [[ -n "$ASC_KEY_PATH" ]] && warn "no file at that path — carry on, but keep the .p8 safe yourself."
  SKIPPED+=("copy AuthKey_*.p8 into $KEY_STORE")
fi
say ""
ask ASC_KEY_ID "Key ID (the 10 characters in AuthKey_XXXXXXXXXX.p8):"
ask ASC_ISSUER_ID "Issuer ID (a UUID, shown above the key table):"
[[ -n "$ASC_KEY_ID" ]]    && write_env ASC_KEY_ID "$ASC_KEY_ID"
[[ -n "$ASC_ISSUER_ID" ]] && write_env ASC_ISSUER_ID "$ASC_ISSUER_ID"
note "Recorded for the TestFlight submit in #83; nothing in the app reads them."
pause

# ── 3 ───────────────────────────────────────────────────────────────────
stage "Find the Vendor number"
say "RevenueCat asks for this alongside the key, to read your sales reports."
open_url "https://appstoreconnect.apple.com/business"
step "The Business page opens on your legal entity. The Vendor number is the"
step "eight-digit number in the RIGHT-hand column of that block, directly above"
step "the 'N Countries or Regions' line — not under the address on the left."
note "  Apple's own docs point at Payments and Financial Reports for it; the"
note "  Business landing page shows the same number without the extra click."
ask ASC_VENDOR_NUMBER "Vendor number:"
[[ -n "$ASC_VENDOR_NUMBER" ]] && write_env ASC_VENDOR_NUMBER "$ASC_VENDOR_NUMBER"
pause

# ── 4 ───────────────────────────────────────────────────────────────────
stage "Upload the key to RevenueCat"
say "This is the stage that clears 'Could not check' on the products."
open_url "https://app.revenuecat.com/projects"
step "Open the Mibo project → Apps → the App Store app ($BUNDLE_ID)."
step "Scroll to the App Store Connect API section — separate from the"
note "  In-App Purchase Key section higher up, which is already filled in."
step "Upload the .p8:"
if [[ -n "${ASC_KEY_PATH:-}" && -f "${ASC_KEY_PATH:-}" ]]; then
  printf '      %s%s%s\n' "$BOLD" "$ASC_KEY_PATH" "$RESET"
else
  note "      the AuthKey_*.p8 you downloaded in stage 1"
fi
step "Issuer ID:      ${ASC_ISSUER_ID:-<from stage 2>}"
step "Vendor number:  ${ASC_VENDOR_NUMBER:-<from stage 3>}"
step "Save Changes. RevenueCat validates immediately and complains if the"
note "  key's access level is below App Manager."
pause "Press Enter once RevenueCat has accepted the key."

# ── 5 ───────────────────────────────────────────────────────────────────
stage "Confirm the products are readable"
say "The catalog check runs against App Store Connect through the new key."
open_url "https://app.revenuecat.com/projects"
step "Product catalog → Products. The three Mibo products should now show a"
step "price and a status instead of 'Could not check'."
note "It can take a minute, and a page reload. If a product still fails, the"
note "usual cause is that it is not yet 'Ready to Submit' in App Store Connect,"
note "or the Paid Applications agreement is not Active — not the key."
say ""
warn "If the two subscriptions read 'Missing Metadata' while App Store Connect"
warn "shows each of them 'Ready for Review', do not go hunting through the"
warn "subscriptions. The gap is one level up: Subscriptions → the Mibo premium"
warn "group → Display Name and Description → Create. That group localization is"
warn "a separate form from the per-subscription ones, and while it is empty"
warn "Apple reports MISSING_METADATA on every child subscription. Filling it in"
warn "(English (U.S.) · 'Mibo Premium' · Use App Name) clears all of them."
if ! confirm "Do the products read their prices now?"; then
  SKIPPED+=("products still read 'Could not check' — recheck agreement status and product state")
  warn "Noted. Stage 6 does not depend on this, so carry on."
fi
pause

# ── 6 ───────────────────────────────────────────────────────────────────
stage "Point Apple's server notifications at RevenueCat"
say "RevenueCat can write the URL into App Store Connect itself, using the key"
say "you just uploaded. That is why this stage comes after it."
open_url "https://app.revenuecat.com/projects"
step "Apps → the App Store app → Apple Server to Server notification settings."
step "Click 'Apply in App Store Connect'. It sets both the Production and the"
step "Sandbox URL in one go, at notification version 2."
say ""
note "If that button errors — it needs the key to have propagated — do it by hand:"
note "  App Store Connect → Apps → Mibo → General → App Information →"
note "  App Store Server Notifications. Paste the URL RevenueCat shows into"
note "  both Production and Sandbox, choose Version 2 Notifications, Save."
if confirm "Do you want App Store Connect open for the manual path?"; then
  open_url "https://appstoreconnect.apple.com/apps"
fi
pause "Press Enter once both URLs are set."

# ── 7 ───────────────────────────────────────────────────────────────────
stage "Prove a notification arrives"
say "The section reads 'No notifications received' until Apple sends one, and"
say "Apple only sends one when something happens to a purchase."
open_url "https://app.revenuecat.com/projects"
step "Make a sandbox purchase on the device, or cancel an existing sandbox"
step "subscription — Settings → App Store → Sandbox Account → Manage."
step "Then reload the RevenueCat app page: the notification settings section"
step "should show a recent timestamp instead of 'No notifications received'."
note "Sandbox renewals are compressed — a month is five minutes — so an expiry"
note "is quick to provoke and is exactly the path #62 re-locks a household on."
if ! confirm "Has RevenueCat received a notification?"; then
  SKIPPED+=("Apple notification not yet observed — retry after the next sandbox purchase")
  warn "Noted. The URL is still set; it just has not been exercised."
fi
pause

finish
note "Both leftovers from issue #75 are now done or recorded above."
note "Report back on #75 with: gh issue comment 75 --body '...'"
printf '\n'
