#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — M4.6 App Store Connect listing and privacy labels (GitHub issue #82).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=14

# The library opens the default browser, which here is Arc. App Store Connect is
# worked in Chrome, so try Chrome by name and hand back to the library — a wrapper
# rather than the sibling wizards' shadowing copy, which duplicated the library's
# whole fallback chain and left the function it shadowed dead.
BROWSER_APP="${BROWSER_APP:-Google Chrome}"
open_url_chrome() {
  local url="$1"
  if [[ "$OSTYPE" == darwin* ]] && open -a "$BROWSER_APP" "$url" >/dev/null 2>&1; then
    printf '  %s↗ opening%s %s %s(%s)%s\n' "$GREEN" "$RESET" "$url" "$DIM" "$BROWSER_APP" "$RESET"
    return
  fi
  open_url "$url"
}

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
SPEC="$REPO_ROOT/docs/spec/05-store-listing.md"
API_BASE="${API_BASE:-https://mibokids.app}"
PRIVACY_URL="$API_BASE/privacy"
# The store needs three URLs and the API serves all three (#84). The apex is the
# Support URL: it names an address a parent can write to and links the other two,
# which is the whole of what Apple asks a support page to do.
TERMS_URL="$API_BASE/terms"
SUPPORT_URL="$API_BASE"
BUNDLE_ID="com.mibokids.app"
ISSUE=82

# The approved listing copy, docs/spec/05-store-listing.md. Stage 1 refuses to run
# unless every one of these three strings is still in that file verbatim: a wizard
# that pastes copy the spec no longer holds is worse than no wizard.
TITLE="Mibo: Chores Tracker"
SUBTITLE="Chore Chart & Kids Allowance"
KEYWORDS="behavior,reward,routine,task,family,habit,star,job,checklist,pocket,money,daily,sticker,toddler,teen"
# Held in reserve for a 2.3.8 rejection on the word "Kids" — see stage 3. 30 of 30.
SUBTITLE_FALLBACK="Chore Chart & Family Allowance"

# The guideline 3.1.2 paragraph, built from the prices ADR-0005 fixes ($39.99/yr,
# $6.99/mo, $79.99 lifetime, no trial) — the same three scripts/setup-premium.sh
# creates. Only the two auto-renewable products carry a renewal sentence; Lifetime
# is Non-Consumable, and describing it as renewing would be the opposite of true.
SUBSCRIPTION_BLURB="Mibo Premium is an auto-renewable subscription: \$6.99 per month or \$39.99 per year. \
Payment is charged to your Apple Account at confirmation of purchase. The subscription renews \
automatically unless it is cancelled at least 24 hours before the end of the current period, and your \
account is charged for renewal within 24 hours of the end of that period. Manage or cancel it in your \
Apple Account settings after purchase. Mibo Premium is also available as a one-time purchase of \
\$79.99, which does not renew. Terms of Use: $TERMS_URL  Privacy Policy: $PRIVACY_URL"

# Section-by-section verification, reported to issue #82 by the last stage.
RESULTS=()
# Set by stage 1 and read by stages 4 and 11; set by stage 2 and read by stages 5 and 13.
privacy_live=0
terms_live=0
support_live=0
MADE_FOR_KIDS="no"

# url_serves URL "marker" — is this URL live and serving the page we mean? Captured
# whole rather than piped into grep -q: under `set -o pipefail` a reader that closes
# on the first match kills curl with SIGPIPE, and a live page reads as a dead one.
# Prints the verdict and returns success, so a caller can record it.
url_serves() {
  local url="$1" marker="$2" body=""
  if body=$(curl -fsS --max-time 15 "$url" 2>/dev/null) && [[ "$body" == *"$marker"* ]]; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$url"
    return 0
  fi
  printf '  %s✗%s %s does not serve the page App Review expects\n' "$RED" "$RESET" "$url"
  return 1
}

# live_or_warn FLAG "warn line" ["second warn line"] — report a URL stage 1 already
# probed. Three stages paste a URL and then say the same two things about it, and
# the consequence of a dead one differs per URL, which is what the warn lines carry.
live_or_warn() {
  local flag="$1"
  if (( flag )); then
    note "  Verified live in stage 1."
    return
  fi
  shift
  local line
  for line in "$@"; do warn "  $line"; done
}

# copy "what" "value" — put a value on the clipboard so it goes into the App Store
# Connect form character-for-character. Typing a 100-character keyword field by
# hand is how a keyword field ends up 99 characters with a typo nobody sees.
copy() {
  local label="$1" value="$2" tool=""
  if   command -v pbcopy   >/dev/null 2>&1; then tool="pbcopy"
  elif command -v wl-copy  >/dev/null 2>&1; then tool="wl-copy"
  elif command -v xclip    >/dev/null 2>&1; then tool="xclip -selection clipboard"
  elif command -v clip.exe >/dev/null 2>&1; then tool="clip.exe"
  fi
  printf '  %s%s%s\n' "$BOLD" "$value" "$RESET"
  if [[ -z "$tool" ]]; then
    note "  (no clipboard tool found — copy the line above by hand)"
    return
  fi
  if printf '%s' "$value" | $tool >/dev/null 2>&1; then
    printf '  %s✎ on the clipboard%s %s%s (%s chars)%s\n' \
      "$GREEN" "$RESET" "$DIM" "$label" "${#value}" "$RESET"
  else
    note "  (clipboard write failed — copy the line above by hand)"
  fi
}

# field_len "Label" "$value" LIMIT — count a field against Apple's limit. Counted
# rather than trusted: a keyword field one character over is rejected at upload,
# and one character under is a wasted keyword nobody notices.
field_len() {
  local label="$1" value="$2" limit="$3"
  if (( ${#value} <= limit )); then
    printf '  %s✓%s %-8s %s/%s\n' "$GREEN" "$RESET" "$label" "${#value}" "$limit"
  else
    printf '  %s✗%s %-8s %s/%s — over the limit\n' "$RED" "$RESET" "$label" "${#value}" "$limit"
    fields_ok=0
  fi
}

# label_decl "Group → Type" "purposes" "linked answer" — one App Privacy data type,
# in the order App Store Connect asks: purposes, then linked to identity, then
# tracking. Tracking is hardcoded No: the app carries no advertising or tracking SDK
# and no data goes to a broker, so every type answers the same, and saying it once
# is one fewer place for the eleven declarations to drift apart.
label_decl() {
  local type="$1" purposes="$2" linked="$3"
  step "$type"
  printf '      %s%-20s%s %s\n' "$DIM" "Purposes:" "$RESET" "$purposes"
  printf '      %s%-20s%s %s\n' "$DIM" "Linked to identity:" "$RESET" "$linked"
  printf '      %s%-20s%s %s\n' "$DIM" "Used for tracking:" "$RESET" "No"
}

# check "section" "what must be true" — record a section as verified, failing or
# not yet done. These become the comment on issue #82.
check() {
  local label="$1" expectation="$2" reply=""
  step "$expectation"
  printf '  %s? %s — is that true? [y/n/Enter = not yet]%s ' "$YELLOW" "$label" "$RESET"
  read -r reply || true
  case "$reply" in
    [Yy]*)
      RESULTS+=("- [x] $label — $expectation")
      printf '  %s✓ recorded as done%s\n' "$GREEN" "$RESET" ;;
    [Nn]*)
      RESULTS+=("- [ ] $label — FAILED: $expectation")
      printf '  %s✗ recorded as failing%s\n' "$RED" "$RESET" ;;
    *)
      RESULTS+=("- [ ] $label — not yet done: $expectation")
      printf '  %s· recorded as not yet done%s\n' "$DIM" "$RESET" ;;
  esac
}

banner "Mibo — App Store Connect listing, privacy labels and age rating"

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Preflight — the copy, its lengths, and the privacy URL"
say "Four things have to hold before a single form is opened."
say ""
say "1. The tools the later stages shell out to:"
for tool in curl jq gh; do
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$tool"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$tool"
    case "$tool" in
      curl) SKIPPED+=("install curl — without it this preflight cannot tell a live privacy policy from a dead one")
            warn "Without curl, check 4 below cannot reach the policy and will report a"
            warn "live one as dead. Treat it as unanswered rather than as a failure." ;;
      jq)   SKIPPED+=("install jq — scripts/check-deploy.sh reads the deployed commit with it") ;;
      gh)   SKIPPED+=("install gh — the last stage posts the verification comment with it") ;;
    esac
  fi
done
if command -v pbcopy >/dev/null 2>&1 || command -v xclip >/dev/null 2>&1 \
  || command -v wl-copy >/dev/null 2>&1 || command -v clip.exe >/dev/null 2>&1; then
  printf '  %s✓%s a clipboard tool\n' "$GREEN" "$RESET"
else
  printf '  %s✗%s no clipboard tool — every value will have to be typed by hand\n' "$YELLOW" "$RESET"
fi
say ""
say "2. This script still agrees with the copy in docs/spec/05-store-listing.md"
say "   and the prices in ADR-0005:"
drift=0
for literal in "$TITLE" "$SUBTITLE" "$KEYWORDS"; do
  if grep -Fq -- "$literal" "$SPEC" 2>/dev/null; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$literal"
  else
    printf '  %s✗%s %s — not in the spec any more\n' "$RED" "$RESET" "$literal"
    drift=1
  fi
done
# The 3.1.2 paragraph quotes money at Apple, so its prices are checked against the
# ADR that fixes them rather than trusted. A store Description promising a price the
# products do not charge is both a 3.1.2 rejection and a lie to a parent.
PRICING_ADR="$REPO_ROOT/docs/adr/0005-free-tier-one-child-with-grace-period.md"
# shellcheck disable=SC2016  # a literal dollar sign, not a variable to expand
for price in '$39.99' '$6.99' '$79.99'; do
  if grep -Fq -- "$price" "$PRICING_ADR" 2>/dev/null \
    && [[ "$SUBSCRIPTION_BLURB" == *"$price"* ]]; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$price"
  else
    printf '  %s✗%s %s — the subscription paragraph and ADR-0005 disagree\n' "$RED" "$RESET" "$price"
    drift=1
  fi
done
if (( drift )); then
  warn "The spec has moved and this wizard has not. Fix the constants at the top of"
  warn "this script before pasting anything into App Store Connect."
  exit 1
fi
say ""
say "3. Apple's field limits, counted rather than trusted:"
fields_ok=1
field_len "Title"    "$TITLE"    30
field_len "Subtitle" "$SUBTITLE" 30
field_len "Keywords" "$KEYWORDS" 100
if [[ "$KEYWORDS" == *", "* ]]; then
  printf '  %s✗%s the keyword field has a space after a comma — each one costs a character\n' "$RED" "$RESET"
  fields_ok=0
fi
(( fields_ok )) || { warn "Fix the copy before continuing."; exit 1; }
say ""
say "4. The three URLs the store record points at, all served by the API (#84):"
# Matched on each page's <h1> rather than its <title>: the title of the apex is the
# store title, which the spec expects ASO to keep changing, and a check that breaks
# on a rename is a check that gets deleted.
url_serves "$PRIVACY_URL" "<h1>Mibo — Privacy Policy</h1>" && privacy_live=1
url_serves "$TERMS_URL"   "<h1>Mibo — Terms of Service</h1>" && terms_live=1
url_serves "$SUPPORT_URL" "<h1>Mibo</h1>" && support_live=1
if (( ! privacy_live || ! terms_live || ! support_live )); then
  say ""
  warn "The routes exist in this working tree (apps/api/src/{privacy,terms,landing}.ts)"
  warn "but a live container that predates them 404s. Deploy before submitting:"
  note "    scripts/deploy-api.sh"
  say ""
  "$REPO_ROOT/scripts/check-deploy.sh" "$API_BASE" || true
  SKIPPED+=("deploy the API so the store's URLs resolve — App Review rejects a dead one")
fi
say ""
if [[ -f "$REPO_ROOT/apps/mobile/app.json" ]] \
  && grep -Fq "\"bundleIdentifier\": \"$BUNDLE_ID\"" "$REPO_ROOT/apps/mobile/app.json"; then
  printf '  %s✓%s apps/mobile/app.json builds %s\n' "$GREEN" "$RESET" "$BUNDLE_ID"
else
  warn "apps/mobile/app.json does not name $BUNDLE_ID — check it before filling the store record."
fi
pause "Press Enter when the preflight looks right."

# ── 2 ───────────────────────────────────────────────────────────────────
stage "The one irreversible decision — Made for Kids"
say "Every later stage depends on this, and App Review freezes it: once the app"
say "is approved with Made for Kids selected, the selection cannot be undone, and"
say "the Kids Category rules bind every future update even if you deselect it."
say ""
say "What Made for Kids would cost Mibo:"
note "  · The age bands are 5-and-under, 6-8 and 9-11. Mibo ships two interface"
note "    modes and buys the keyword 'teen' — the product outgrows every band."
note "  · Guideline 1.3: a Kids Category app may not send device information to"
note "    third parties. A hard native crash sends a stack trace and device"
note "    details to Sentry before our allowlist can touch it (ADR-0015) — that is"
note "    documented in the privacy policy and it conflicts with 1.3."
note "  · Third-party analytics is permitted only in limited cases. PostHog on a"
note "    child device is anonymous per device (ADR-0009) and would probably pass;"
note "    Sentry's native crash path is the part that would not."
say ""
say "What staying out of it costs:"
warn "Guideline 2.3.8 reserves child-audience wording for the Kids Category. The"
warn "approved subtitle contains 'Kids', so a 2.3.8 rejection is possible. Stage 3"
warn "carries a prepared replacement, and the Play title's 'for Kids' is Play's"
warn "business, not Apple's."
say ""
note "The recommendation is NOT Made for Kids: keep the 4+ rating, and swap the"
note "subtitle if Apple objects to it."
if confirm "Select Made for Kids anyway?"; then
  MADE_FOR_KIDS="yes"
  warn "Recorded as yes. Stage 5 will select an age band, and Sentry's native crash"
  warn "reporting on child devices has to be turned off before submission."
  SKIPPED+=("Made for Kids chosen — reconcile Sentry's native crash reports with guideline 1.3")
else
  note "Recorded as no — the wizard will tell stage 5 to leave the override alone."
fi
pause

# ── 3 ───────────────────────────────────────────────────────────────────
stage "App Information — name, subtitle, categories"
say "App Store Connect → Apps → Mibo → General → App Information."
open_url_chrome "https://appstoreconnect.apple.com/apps"
say ""
step "Name (2-30 characters):"
copy "Name" "$TITLE"
note "  Never 'Mibo Kids'. 'Kids' belongs to the identifier and never to the brand"
note "  — the icon on a 10-year-old's phone says only 'Mibo'."
say ""
step "Subtitle (max 30):"
copy "Subtitle" "$SUBTITLE"
note "  If App Review cites guideline 2.3.8 on the word 'Kids', this replacement is"
note "  the same length class and keeps the allowance phrase:"
note "    $SUBTITLE_FALLBACK  (${#SUBTITLE_FALLBACK}/30)"
say ""
step "Primary Category: Productivity"
step "Secondary Category: Education"
warn "The milestone brief says 'Secondary: Family'. There is no Family category on"
warn "the App Store — that is Google Play's vocabulary. Education is the closest"
warn "iOS equivalent for a chores-and-routines app; Lifestyle is the alternative."
say ""
step "Content Rights: answer that the app contains no third-party content."
step "Digital Services Act: answer the trader question — the EU storefronts hide"
step "the app until it is answered, and the answer is not part of App Review."
step "Bundle ID must read $BUNDLE_ID. SKU is private, e.g. mibo-ios-001."
pause "Press Enter once App Information is saved."

# ── 4 ───────────────────────────────────────────────────────────────────
stage "App Information — Privacy Policy URL"
say "Required for every iOS app, and required twice over for a child-directed one:"
say "a parent deciding whether to hand the app to a child reads it before there is"
say "an account, which is why it is served by the API and not by the app."
open_url_chrome "https://appstoreconnect.apple.com/apps"
step "General → App Information → Privacy Policy URL:"
copy "Privacy Policy URL" "$PRIVACY_URL"
live_or_warn "$privacy_live" \
  "This URL is 404 right now. Paste it, but deploy before submitting —" \
  "App Review opens it, and a dead policy URL is a rejection."
say ""
step "Leave 'User Privacy Choices URL' empty."
note "  It is for an in-page control that lets a user exercise privacy rights."
note "  Mibo's route is an email to the address in the policy, which the policy"
note "  states, so an empty field is the honest answer rather than a missing one."
pause "Press Enter once the URL is saved."

# ── 5 ───────────────────────────────────────────────────────────────────
stage "Age rating — the 2025 questionnaire"
say "Apple replaced 12+ and 17+ with 13+, 16+ and 18+ and added required questions"
say "about in-app controls, capabilities, medical themes and violence. An app with"
say "unanswered new questions cannot be updated at all."
open_url_chrome "https://appstoreconnect.apple.com/apps"
step "General → App Information → Age Ratings → Set Up Age Ratings."
say ""
step "In-app controls and capabilities — what Mibo actually has:"
note "  Parental controls: YES — a child's device leaves kid mode only with the"
note "    Parent PIN, checked on the device against a synced hash (ADR-0013)."
note "    Say no more than that: the PIN gates leaving kid mode and nothing else."
note "    Every parent action, purchases included, sits behind a Clerk session,"
note "    which is strictly stronger and is the real gate over a purchase."
note "  In-app purchases: YES — the premium subscription, in parent mode only,"
note "    on a screen a child's device cannot reach without both the PIN and a"
note "    parent's sign-in."
note "  Advertising: NO. Mibo contains no ads and no advertising SDK."
note "  Unrestricted web access: NO."
note "  Social media features, messaging between users, user-generated content"
note "    shared with other users: NO. Photo Proof goes to a parent in the same"
note "    household through a five-minute link and reaches nobody else (ADR-0017)."
note "  Age assurance / age verification: NO."
say ""
step "Every content descriptor — violence, sexual content, profanity, horror,"
step "alcohol, drugs, medical or wellness themes, simulated gambling, contests,"
step "gambling, loot boxes — is NONE."
step "The calculated rating should come out 4+. If it does not, one descriptor was"
step "answered wrong; do not accept a higher rating for a chores app."
say ""
if [[ "$MADE_FOR_KIDS" == "yes" ]]; then
  step "Age Categories and Override → Made for Kids → pick the age band."
  warn "Irreversible after approval, and it binds every future update."
else
  step "Age Categories and Override → leave it alone. Do NOT choose Made for Kids"
  step "and do NOT override to a higher rating."
  note "  Per stage 2. The Kids Category cannot be undone after approval."
fi
step "Age Suitability URL: leave empty."
pause "Press Enter once the questionnaire is saved and reads 4+."

# ── 6 ───────────────────────────────────────────────────────────────────
stage "App Privacy — which data types to declare"
say "Apple's rule: you declare what you AND your third-party SDKs collect. The"
say "next four stages follow apps/api/src/privacy.ts, which is the policy the"
say "labels have to agree with — a label that contradicts the policy is the one"
say "inconsistency App Review always finds."
open_url_chrome "https://appstoreconnect.apple.com/apps"
step "Sidebar → App Privacy → Get Started."
step "Answer: Yes, we collect data from this app."
say ""
step "Then select exactly these data types and no others:"
note "  Contact Info → Name, Email Address"
note "  User Content → Photos or Videos, Other User Content"
note "  Identifiers  → User ID, Device ID"
note "  Purchases    → Purchase History"
note "  Usage Data   → Product Interaction, Other Usage Data"
note "  Diagnostics  → Crash Data"
say ""
note "Deliberately NOT selected, and why, in case a reviewer asks:"
note "  Financial Info — Apple and Google take the payment; RevenueCat relays a"
note "    status. No card or bank detail ever reaches us. Purchase History covers it."
note "  Location, Contacts, Health, Sensitive Info, Browsing History, Search"
note "    History — never requested, never collected, from a parent or a child."
note "  Performance Data — Sentry runs with tracesSampleRate 0 and no profiling"
note "    (apps/mobile/src/lib/error-reporting.ts). No performance data leaves"
note "    the device, so declaring it would describe collection that never happens."
note "  Other Diagnostic Data — the scrubbed request breadcrumbs ride inside a"
note "    crash report rather than arriving as a payload of their own."
say ""
warn "The ticket asks for a declaration that no child data is collected. That is not"
warn "the answer this list gives, and the policy is why: a parent types a child's"
warn "first name, a child takes a Photo Proof, and both sit in a household an"
warn "account owns. What is true, and what the labels do say, is that nothing is"
warn "linked to a CHILD's identity — a child has none — and nothing is tracked."
pause "Press Enter once the data types are saved."

# ── 7 ───────────────────────────────────────────────────────────────────
stage "App Privacy — Contact Info and Identifiers"
say "App Store Connect asks three questions per data type, in this order. The"
say "fourth line under each is not Apple's question — it is where the data comes"
say "from, so the answer can be checked rather than remembered."
say ""
label_decl "Contact Info → Email Address" "App Functionality" "Yes"
note "      Source: the parent's address from Clerk, and a partner-invite address"
note "      the household stores so the invitation matches when that person signs in."
say ""
label_decl "Contact Info → Name" "App Functionality" "Yes"
note "      Source: the parent's display name from their sign-in provider, and the"
note "      child's first name a parent typed. A child gives us no name themselves."
say ""
label_decl "Identifiers → User ID" "App Functionality, Analytics" "Yes"
note "      Source: the parent's Clerk account id — it identifies them in PostHog"
note "      and in Sentry. A child has no account, so no user id (ADR-0001)."
say ""
label_decl "Identifiers → Device ID" "App Functionality, Analytics" "Yes"
note "      Linked: a parent's Expo push token, which belongs to their account."
note "      Not linked, and there is no way to say so here: the hashed child-device"
note "      token, the child device's push token, and the random per-device"
note "      analytics id issued when a Join Code is redeemed and retired when the"
note "      device is revoked (ADR-0009)."
warn "The linking question is one radio per data type — a type cannot be filed"
warn "under both headings, whatever an earlier draft of this wizard claimed."
warn "Answer Yes. Over-declaring costs a line on the product page; under-declaring"
warn "is what App Review rejects. The unlinked child path is spelled out in the"
warn "policy, which is where a reviewer reads it against these labels anyway."
pause

# ── 8 ───────────────────────────────────────────────────────────────────
stage "App Privacy — Purchases and User Content"
label_decl "Purchases → Purchase History" "App Functionality" "Yes"
note "      Source: RevenueCat. The household stores which product is active and"
note "      when it renews or expires, plus the webhook messages as received"
note "      (ADR-0016)."
say ""
label_decl "User Content → Photos or Videos" "App Functionality" "Yes"
note "      Linked because the photo hangs off a completion in a household a"
note "      parent's account owns, even though the child who took it has no account."
note "      Source: Photo Proof. A private R2 bucket, a five-minute link for a"
note "      parent in the same household, deleted after 30 days (ADR-0017). Never"
note "      used for advertising or training, never leaves the household."
say ""
label_decl "User Content → Other User Content" "App Functionality" "Yes"
note "      Source: what a family types and does — chore titles, reward titles, the"
note "      pet's name, a child's interface mode and optional reminder time,"
note "      completions, the coin ledger and the grove."
pause

# ── 9 ───────────────────────────────────────────────────────────────────
stage "App Privacy — Usage Data and Diagnostics"
say "A child's device produces these too, but the form takes one linking answer"
say "per data type, so each is filed by its parent-side truth and the child side"
say "is left to the policy."
say ""
label_decl "Usage Data → Product Interaction" "Analytics" "Yes"
note "      Linked: parent mode, where PostHog identifies the parent by account id"
note "      and groups them by household."
note "      Not linked, unsayable here: a child device, known only by its random"
note "      per-device id."
note "      Autocapture and session replay are off everywhere in the app, and"
note "      PostHog is EU-hosted."
say ""
label_decl "Usage Data → Other Usage Data" "Analytics" "No"
note "      Source: the three properties a child device may attach to an event —"
note "      interface mode, a broad age band, and a one-way hash of the household"
note "      id. A child's id, first name and pet name are never sent. The child"
note "      device's platform and language belong here too, rather than under"
note "      Apple's Other Data."
say ""
label_decl "Diagnostics → Crash Data" "App Functionality" "Yes"
note "      Linked: a parent, identified in Sentry by account id."
note "      Not linked, unsayable here: a child device, which sets no Sentry user"
note "      identity. Same single radio as Device ID — answer Yes."
warn "      A crash severe enough to stop the app is written by Sentry's native"
warn "      code before our allowlist runs, and carries a stack trace and device"
warn "      details (ADR-0015). That is disclosed in the policy, and it is why"
warn "      Diagnostics is declared rather than argued away."
say ""
note "Crash Data is the only Diagnostics type: screenshots, session replay and"
note "console-log attachment are off, tracing is off and there is no profiling."
pause

# ── 10 ──────────────────────────────────────────────────────────────────
stage "App Privacy — tracking, the preview, and Publish"
say "The declaration the milestone turns on: nothing Mibo collects is used for"
say "tracking, and nothing about a child is linked to a child's identity."
step "Every data type must read 'Not used for tracking'. There is no advertising"
step "SDK, no IDFA request, no App Tracking Transparency prompt, and no data"
step "broker — the app contains no advertising or tracking SDK at all."
say ""
step "Scroll to Product Page Preview → See Details, and read it as a parent would."
note "  Expect 'Data Linked to You' (contact info, user content, identifiers,"
note "  diagnostics, usage data, purchases) and 'Data Not Linked to You'"
note "  (identifiers, usage data)."
warn "  There must be no 'Data Used to Track You' section at all. If one appears,"
warn "  a data type still answers Yes on the third question — that is the one"
warn "  answer this milestone cannot get wrong, and the form will not say so."
say ""
warn "Publish is per data type: each editor's last button publishes the whole"
warn "section, so a type you opened and abandoned keeps its old answer. Saved is"
warn "not published, an unpublished section blocks submission, and the form looks"
warn "finished either way — so re-read the preview after the last edit."
pause "Press Enter once App Privacy is published."

# ── 11 ──────────────────────────────────────────────────────────────────
stage "Version metadata — keywords, description, URLs, review access"
say "These live on the version page, not App Information: Apps → Mibo →"
say "Distribution → the 1.0 iOS App version in the sidebar."
open_url_chrome "https://appstoreconnect.apple.com/apps"
say ""
step "Keyword field — 100 of 100, no spaces after the commas:"
copy "Keywords" "$KEYWORDS"
note "  Apple forms phrases across title, subtitle and keywords, so nothing in the"
note "  first two repeats here. 'app' is omitted because Apple indexes it anyway,"
note "  and 'ADHD' deliberately — out of scope, and Joon owns the term."
say ""
step "Promotional text, Description and Copyright."
warn "docs/spec/05-store-listing.md specifies the title, subtitle and keywords"
warn "only. The description is not spec'd, so write it as the parent-facing pitch"
warn "and keep it out of 2.3.8 territory: describe what the app does for a family"
warn "rather than claiming children as the audience."
step "Support URL is required and must resolve. It is the apex of our own domain,"
step "which names an address a parent can write to and links both documents:"
copy "Support URL" "$SUPPORT_URL"
live_or_warn "$support_live" \
  "This URL does not answer right now — deploy before submitting."
note "  Marketing URL is optional and there is no marketing site; leave it empty"
note "  rather than pointing it at the same page twice."
say ""
step "Guideline 3.1.2 — the auto-renewable subscription disclosures. This is the"
step "one the submission is rejected on, and it is metadata rather than code:"
note "  The Description must state the subscription's title, its length, the price"
note "  per period, and that it renews unless cancelled at least 24 hours before"
note "  the period ends. Paste this paragraph at the end of the Description —"
note "  the prices are the ones ADR-0005 fixes and setup-premium.sh creates:"
copy "3.1.2 paragraph" "$SUBSCRIPTION_BLURB"
say ""
note "  A functional link to the Terms of Use must be in the Description — the"
note "  paragraph above carries it — and the EULA field has to hold either"
note "  Apple's standard EULA or that same link:"
copy "Terms of Use URL" "$TERMS_URL"
live_or_warn "$terms_live" \
  "This URL does not answer right now — deploy before submitting. Apple" \
  "clicks it, and a dead Terms link is a 3.1.2 rejection."
say ""
# 3.1.2 wants the disclosure on the paywall as well as in the store metadata, and
# that half is a diff rather than a form — it belongs to #83. Read the file rather
# than asserting what is in it: hardcoding "the paywall lacks this" would keep
# reporting it long after #83 lands, which is how a wizard starts lying.
PAYWALL="$REPO_ROOT/apps/mobile/src/app/(parent)/paywall.tsx"
if grep -qi 'renew' "$PAYWALL" 2>/dev/null && grep -qi 'terms' "$PAYWALL" 2>/dev/null; then
  note "3.1.2 wants the same disclosure ON the paywall, and $(basename "$PAYWALL") now"
  note "mentions both renewal and terms — read it once to confirm it reads as Apple"
  note "wants, then treat this as done."
else
  warn "3.1.2 wants the same disclosure ON the paywall, and Mibo's does not carry it:"
  warn "apps/mobile/src/app/(parent)/paywall.tsx shows RevenueCat's price string and"
  warn "nothing else — no renewal sentence, no Terms or Privacy link. Store metadata"
  warn "cannot cover for that. It is a diff, so it belongs to the submission ticket"
  warn "#83; this wizard only records that it is outstanding."
  SKIPPED+=("add the 3.1.2 renewal sentence and the Terms/Privacy links to the in-app paywall (#83)")
fi
say ""
step "Pricing and Availability — Mibo is free with a subscription, so price"
step "tier Free, and pick the territories. A version cannot be submitted without it."
step "Export compliance — apps/mobile/app.json already sets"
step "ITSAppUsesNonExemptEncryption to false, so the build answers this itself and"
step "the version page should not ask. If it asks, the build predates that key."
say ""
step "App Review Information — a demo account and notes. Parent mode needs a"
step "sign-in, so a reviewer who cannot get in rejects on guideline 2.1."
note "  Give a parent email and password that already has a household with a"
note "  child, and explain in the notes how the child side is reached: a parent"
note "  generates a Join Code, and a second device redeems it — a child never"
note "  signs in. Name the Parent PIN too, or the reviewer cannot reach parent"
note "  mode on a device that has joined."
pause "Press Enter once the version metadata is saved."

# ── 12 ──────────────────────────────────────────────────────────────────
stage "Screenshots"
say "Apple now scales one source set down, so the required upload is the largest"
say "iPhone: 6.9 inch, 1320 x 2868 portrait."
warn "The ticket asks for 6.5 and 6.7 inch sets. 6.7 is no longer an upload slot,"
warn "and 6.5 is only required if 6.9 is absent. Upload 6.9 and let Apple scale;"
warn "add a 6.5 set (1284 x 2778) only to control what older devices show."
say ""
step "On the version page → Previews and Screenshots → iPhone 6.9\" Display."
step "Between three and ten images. Four, showing the loops the milestone names:"
note "  1. the kid's done moment"
note "  2. the pet reacting to it"
note "  3. the parent's allowance ledger"
note "  4. a parent approving a chore"
say ""
warn "Guideline 2.3.8 covers screenshots as well as the name. Caption them for a"
warn "parent — 'chores and allowance for your family', not 'an app for kids' —"
warn "while the app is outside the Kids Category."
note "Capture on a real 6.9\" device or the matching simulator; Expo's dev-client"
note "banner must not be in frame."
pause "Press Enter once the screenshots are uploaded."

# ── 13 ──────────────────────────────────────────────────────────────────
stage "Verify every section App Store Connect requires"
say "One pass over the record, section by section. Answer honestly — the point of"
say "this stage is a list of what is still missing, not a clean sheet."
say ""
check "Name and subtitle" "App Information shows '$TITLE' and a subtitle of 30 characters or fewer."
check "Categories" "Primary Productivity, a secondary category set, Content Rights and the DSA trader question answered."
check "Privacy Policy URL" "$PRIVACY_URL is saved and opens the policy in a browser."
check "Age rating" "The questionnaire is complete, the rating reads 4+, and the Made for Kids choice matches this run ($MADE_FOR_KIDS)."
check "App Privacy" "All six data-type groups are answered, every one reads 'not used for tracking', and the section is PUBLISHED."
check "Privacy and policy agree" "The published labels say nothing the policy at $PRIVACY_URL does not."
check "Keywords" "The keyword field holds all 100 characters, with no space after any comma."
check "Description and URLs" "Description, promotional text, Copyright and a Support URL of $SUPPORT_URL are saved."
check "Subscription disclosures" "The Description states the subscription's length, price and renewal terms and links $TERMS_URL, and the EULA field is answered."
check "Pricing and Availability" "The price is Free, territories are chosen, and the version no longer reports it as missing."
check "Export compliance" "The version page does not ask for an encryption answer, because the build carries ITSAppUsesNonExemptEncryption."
check "App Review Information" "A working parent demo account, the Parent PIN, and how a child device joins are in the review notes."
check "Screenshots" "At least three 6.9-inch screenshots are uploaded and show the four core loops."
pause

# ── 14 ──────────────────────────────────────────────────────────────────
stage "Report back to issue #$ISSUE"
say "Posting the section-by-section result as a comment."
if (( ${#RESULTS[@]} == 0 )); then
  warn "Nothing recorded — nothing to report."
  SKIPPED+=("the verification comment on issue #$ISSUE")
  finish
  exit 0
fi
# shellcheck disable=SC2016  # the backticks are Markdown for the issue comment
comment=$(printf '## App Store Connect listing — verification\n\nRun via `scripts/setup-store-listing.sh` on %s.\nMade for Kids: **%s**.\n\n%s\n' \
  "$(date -u '+%Y-%m-%d %H:%M UTC')" "$MADE_FOR_KIDS" "$(printf '%s\n' "${RESULTS[@]}")")
printf '\n%s\n\n' "$comment"
if confirm "Post this to issue #$ISSUE?"; then
  if printf '%s' "$comment" | gh issue comment "$ISSUE" --body-file - >/dev/null 2>&1; then
    printf '  %s✓ posted%s to issue #%s\n' "$GREEN" "$RESET" "$ISSUE"
  else
    warn "gh could not post — copy the comment above onto the issue by hand."
    SKIPPED+=("the verification comment on issue #$ISSUE")
  fi
else
  SKIPPED+=("the verification comment on issue #$ISSUE")
fi
pause

finish
note "The build and the submission itself are #83, and it is blocked on this one."
printf '\n'
