#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES — M3 premium ops (GitHub issue #75).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=16

# open_url override — the library opens the default browser, which here is Arc.
# These dashboards are worked in Chrome, so target it by name and fall back to
# the library's behaviour if it is not installed.
BROWSER_APP="${BROWSER_APP:-Google Chrome}"
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s %s(%s)%s\n' "$GREEN" "$RESET" "$url" "$DIM" "$BROWSER_APP" "$RESET"
  if [[ "$OSTYPE" == darwin* ]] && open -a "$BROWSER_APP" "$url" >/dev/null 2>&1; then
    return
  fi
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser - visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser - visit it manually: $url"
}

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
API_ENV="$REPO_ROOT/apps/api/.env"
MOBILE_ENV="$REPO_ROOT/apps/mobile/.env"
API_BASE="https://api-production-c5c7.up.railway.app"
WEBHOOK_URL="$API_BASE/webhooks/revenuecat"
BUNDLE_ID="com.mibokids.app"
ISSUE=75

# Device hand-test results, filled in by the check stages and reported at the end.
RESULTS=()

# railway_set KEY VALUE — set a variable on the Railway `api` service, hidden from argv.
railway_set() {
  local name="$1" value="$2"
  if ! command -v railway >/dev/null 2>&1; then
    SKIPPED+=("Railway variable $name (railway CLI missing)")
    warn "skipped Railway $name — railway CLI missing"
    return
  fi
  if printf '%s' "$value" | railway variable set "$name" --stdin --service api --skip-deploys >/dev/null 2>&1; then
    printf '  %s✓ set%s Railway variable %s on service api\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Railway variable $name (set it with: railway variable set $name --stdin --service api)")
    warn "skipped Railway $name — the CLI rejected it; see the summary"
  fi
}

# check "M3.x" "what the tester should see" — record a pass/fail for the issue comment.
check() {
  local label="$1" expectation="$2" reply=""
  step "$expectation"
  printf '  %s? %s — did that happen? [y/n/Enter = not yet]%s ' "$YELLOW" "$label" "$RESET"
  read -r reply || true
  case "$reply" in
    [Yy]*)
      RESULTS+=("- [x] $label — $expectation")
      printf '  %s✓ recorded as passing%s\n' "$GREEN" "$RESET" ;;
    [Nn]*)
      RESULTS+=("- [ ] $label — FAILED: $expectation")
      printf '  %s✗ recorded as failing%s\n' "$RED" "$RESET" ;;
    *)
      RESULTS+=("- [ ] $label — not yet run: $expectation")
      printf '  %s· recorded as not yet run%s\n' "$DIM" "$RESET" ;;
  esac
}

banner "Mibo premium setup — RevenueCat, App Store Connect, R2, device tests"

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools the later stages shell out to."
missing=0
for tool in curl jq openssl railway gh; do
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$tool"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$tool"
    missing=1
  fi
done
if (( missing )); then
  warn "Install the missing tools before continuing — stages 9, 10 and 15 need them."
  confirm "Continue anyway?" || exit 1
fi
say ""
say "Checking the live API is up (the webhook in stage 9 points at it):"
if curl --silent --fail --max-time 10 "$API_BASE/health" >/dev/null 2>&1; then
  printf '  %s✓%s %s/health responds\n' "$GREEN" "$RESET" "$API_BASE"
else
  warn "$API_BASE/health did not respond — RevenueCat will not be able to deliver webhooks."
  confirm "Continue anyway?" || exit 1
fi
say ""
note "Railway must be linked to the 'chores' project for stages 9 and 10."
# Captured rather than piped to head: under pipefail, head closing the pipe early
# kills railway with SIGPIPE and a linked project reads as a failure.
if railway_status=$(railway status 2>/dev/null); then
  printf '%s\n' "$railway_status" | sed -n '1,6p'
else
  warn "railway status failed — run 'railway link' in another terminal."
fi
pause "Press Enter when the tooling looks right."

# ── 2 ───────────────────────────────────────────────────────────────────
stage "Apple — bundle ID, app record, agreements"
say "RevenueCat cannot validate its purchase key until Apple knows this bundle id,"
say "and no product can be fetched until the paid agreement is active."
open_url "https://developer.apple.com/account/resources/identifiers/list"
step "+ → App IDs → App → Explicit Bundle ID: $BUNDLE_ID"
step "Leave the In-App Purchase capability checked, then Register."
pause "Press Enter once the identifier exists."
say ""
open_url "https://appstoreconnect.apple.com/apps"
step "+ → New App → iOS, then pick $BUNDLE_ID from the Bundle ID dropdown."
note "  It appears only once the identifier above has propagated — usually seconds."
step "SKU: any private string, e.g. mibo-ios-001. Never shown publicly."
step "Name: Mibo: Chores Tracker"
note "  The approved iOS title, 20 of 30 characters (docs/spec/05-store-listing.md)."
note "  Bare 'Mibo' is taken — ten unrelated apps across both stores, which is why"
note "  the identifier compounds and the title carries the keyword tail instead."
note "  Never 'Mibo Kids': 'Kids' belongs to the identifier and never to the brand."
note "  Play's title differs — Mibo: Chores Tracker for Kids — and is set later."
pause "Press Enter once the app record exists."
say ""
open_url "https://appstoreconnect.apple.com/business"
step "Agreements, Tax, and Banking → Paid Applications must read Active,"
step "with tax and banking details filled in."
warn "Until it is active, products exist but no device can fetch them. The paywall"
warn "then fails as 'current offering is missing' and reads like a RevenueCat fault"
warn "rather than Apple paperwork. Bank verification can take a day or two."
if ! confirm "Is the Paid Applications agreement Active?"; then
  SKIPPED+=("Paid Applications agreement — the products in stage 5 stay unfetchable until it is Active")
  warn "Noted. Carry on configuring; the device stages cannot pass until it clears."
fi
pause

# ── 3 ───────────────────────────────────────────────────────────────────
stage "RevenueCat — project and apps"
say "One RevenueCat project holds both store apps for Mibo."
open_url "https://app.revenuecat.com/projects"
step "Create a project named 'Mibo' (or open it if it already exists)."
step "Inside the project: Apps → + New → App Store. Bundle ID: $BUNDLE_ID"
step "Upload the App Store Connect In-App Purchase Key so RevenueCat can verify receipts."
step "Then Apps → + New → Play Store. Package name: $BUNDLE_ID"
note "The Play Store app can wait if you are only hand-testing on iOS today."
pause "Press Enter once the project and at least the App Store app exist."

# ── 4 ───────────────────────────────────────────────────────────────────
stage "RevenueCat — SDK API keys"
ENV_FILE="$MOBILE_ENV"
say "The app reads these at build time (apps/mobile/src/lib/purchases.ts)."
open_url "https://app.revenuecat.com/projects"
step "API keys — a top-level item in the left sidebar, low down, above"
note "  Integrations and Project settings. It is NOT a Project settings tab."
note "  The same key also sits on Apps → your App Store app."
step "Copy the App Store key — it starts with 'appl_'."
ask EXPO_PUBLIC_REVENUECAT_IOS_KEY "Paste the iOS (appl_) key:"
step "Copy the Play Store key — it starts with 'goog_'. Leave blank to skip Android."
ask EXPO_PUBLIC_REVENUECAT_ANDROID_KEY "Paste the Android (goog_) key:"
[[ -n "$EXPO_PUBLIC_REVENUECAT_IOS_KEY" ]] && write_env EXPO_PUBLIC_REVENUECAT_IOS_KEY "$EXPO_PUBLIC_REVENUECAT_IOS_KEY"
[[ -n "$EXPO_PUBLIC_REVENUECAT_ANDROID_KEY" ]] && write_env EXPO_PUBLIC_REVENUECAT_ANDROID_KEY "$EXPO_PUBLIC_REVENUECAT_ANDROID_KEY"
note "These are public SDK keys — safe in the client, not secrets."
warn "EXPO_PUBLIC_* are inlined at build time: rebuild the dev client after this."
pause

# ── 5 ───────────────────────────────────────────────────────────────────
stage "App Store Connect — the three products"
say "Three products, one offering. Prices are fixed by ADR-0005."
open_url "https://appstoreconnect.apple.com/apps"
step "Your app → Monetization → Subscriptions. Create a group, e.g. 'Mibo Premium'."
step "In that group add an Auto-Renewable Subscription at \$39.99 / year."
ask RC_PRODUCT_ANNUAL "Product ID you gave the yearly subscription:"
step "Add a second Auto-Renewable Subscription in the same group at \$6.99 / month."
ask RC_PRODUCT_MONTHLY "Product ID you gave the monthly subscription:"
step "Then Monetization → In-App Purchases → + → Non-Consumable, at \$79.99."
ask RC_PRODUCT_LIFETIME "Product ID you gave the lifetime purchase:"

# Strip whitespace: these are pasted from App Store Connect and a trailing space
# survives the paste, then fails to match in RevenueCat with no visible cause.
RC_PRODUCT_ANNUAL="${RC_PRODUCT_ANNUAL//[[:space:]]/}"
RC_PRODUCT_MONTHLY="${RC_PRODUCT_MONTHLY//[[:space:]]/}"
RC_PRODUCT_LIFETIME="${RC_PRODUCT_LIFETIME//[[:space:]]/}"
say ""
note "Lifetime must be Non-Consumable: RevenueCat sends it as NON_RENEWING_PURCHASE"
note "with no expiry, which is the only shape the server treats as permanent"
note "(apps/api/src/revenuecat.ts, ADR-0016)."
say ""
step "Give all three a cleared-for-sale price and at least one localization."
pause "Press Enter once all three exist and are 'Ready to Submit'."

# ── 6 ───────────────────────────────────────────────────────────────────
stage "App Store Connect — sandbox testers"
say "You need two: one buys premium, the other checks the partner path."
open_url "https://appstoreconnect.apple.com/access/users/sandbox"
step "Sandbox Testers → + → create a buyer account. Use an email you can receive."
step "Create a second tester for the partner parent in the same household."
warn "Never sign into iCloud with these. On the device use Settings → Developer → Sandbox Apple Account."
note "Both testers must map to parents in the same household — the webhook resolves"
note "the buyer by Clerk user id and writes the entitlement on their household."
pause "Press Enter once both sandbox testers exist."

# ── 7 ───────────────────────────────────────────────────────────────────
stage "RevenueCat — Product catalog → Products"
say "Import the three App Store Connect ids so RevenueCat can price them."
open_url "https://app.revenuecat.com/projects"
step "Product catalog → Products tab → + New / Import."
step "Add: $RC_PRODUCT_ANNUAL"
step "Add: $RC_PRODUCT_MONTHLY"
step "Add: $RC_PRODUCT_LIFETIME"
note "Each must attach to the App Store app you created in stage 2."
pause "Press Enter once all three products show in the catalog."

# ── 8 ───────────────────────────────────────────────────────────────────
stage "RevenueCat — the 'premium' entitlement"
say "The identifier is not a free choice — the server compares it literally."
open_url "https://app.revenuecat.com/projects"
step "Product catalog → Entitlements tab → + New."
step "Identifier: premium        ← lowercase, exactly this, no other spelling."
step "Attach all three products from stage 6 to it."
say ""
note "apps/api/src/revenuecat.ts only reacts to events whose entitlement_id is"
note "'premium'; apps/mobile/src/lib/purchases.ts reads entitlements.active.premium."
note "Any other identifier means purchases succeed and nothing unlocks."
pause "Press Enter once the entitlement exists with all three products."

# ── 9 ───────────────────────────────────────────────────────────────────
stage "RevenueCat — the current offering"
say "The paywall renders exactly the current offering's three packages."
open_url "https://app.revenuecat.com/projects"
step "Product catalog → Offerings tab → + New. Identifier: default"
step "Add package 'Annual'   → $RC_PRODUCT_ANNUAL"
step "Add package 'Monthly'  → $RC_PRODUCT_MONTHLY"
step "Add package 'Lifetime' → $RC_PRODUCT_LIFETIME"
step "Mark this offering as Current."
say ""
note "premiumPackages() throws 'current offering is missing' if none is current,"
note "and 'must contain three products' unless exactly Annual + Monthly + Lifetime"
note "resolve. A fourth package type is filtered out; a missing one is fatal."
pause "Press Enter once the offering is current with all three packages."

# ── 10 ──────────────────────────────────────────────────────────────────
stage "RevenueCat — webhook and signing secret"
ENV_FILE="$API_ENV"
say "The webhook is the only thing that may write an entitlement (ADR-0016)."
open_url "https://app.revenuecat.com/projects"
step "Integrations → Webhooks → Add new configuration."
step "Webhook URL:"
printf '      %s%s%s\n' "$BOLD" "$WEBHOOK_URL" "$RESET"
step "Environment: send both Sandbox and Production."
step "Leave the Authorization header blank — the server verifies the signature instead."
step "Save, then copy the signing secret. It is shown once and cannot be retrieved later."
ask_secret REVENUECAT_WEBHOOK_SIGNING_SECRET "Paste the signing secret:"
if [[ -z "$REVENUECAT_WEBHOOK_SIGNING_SECRET" ]]; then
  warn "No secret captured — the API refuses to boot without it and every webhook 401s."
  SKIPPED+=("REVENUECAT_WEBHOOK_SIGNING_SECRET in apps/api/.env and on Railway")
else
  write_env REVENUECAT_WEBHOOK_SIGNING_SECRET "$REVENUECAT_WEBHOOK_SIGNING_SECRET"
  railway_set REVENUECAT_WEBHOOK_SIGNING_SECRET "$REVENUECAT_WEBHOOK_SIGNING_SECRET"
fi
say ""
note "The server accepts INITIAL_PURCHASE, RENEWAL, CANCELLATION, EXPIRATION,"
note "PRODUCT_CHANGE and NON_RENEWING_PURCHASE. Send all event types — the rest"
note "are stored for the audit trail and change nothing."
pause

# ── 11 ──────────────────────────────────────────────────────────────────
stage "R2 — bucket, credentials, lifecycle"
say "scripts/setup-r2.sh does the whole thing: bucket, CORS, the 30-day rule"
say "(ADR-0017), bucket-scoped credentials, and the four Railway variables."
say ""
step "You need one bootstrap Cloudflare API token with two permissions:"
note "  Account → Workers R2 Storage → Edit"
note "  Account → API Tokens → Edit"
note "  Scope it to your account under Account Resources. Cloudflare says Edit"
note "  where its docs say Write — same permission."
open_url "https://dash.cloudflare.com/profile/api-tokens"
say ""
if confirm "Run scripts/setup-r2.sh now?"; then
  say ""
  "$REPO_ROOT/scripts/setup-r2.sh" || warn "setup-r2.sh failed — rerun it by hand; it is idempotent."
  say ""
  say "Verifying the four variables landed on Railway:"
  for key in R2_ACCOUNT_ID R2_BUCKET R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY; do
    if railway variable list --service api --json 2>/dev/null | jq -e --arg k "$key" 'has($k)' >/dev/null; then
      printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$key"
    else
      printf '  %s✗%s %s missing\n' "$RED" "$RESET" "$key"
      SKIPPED+=("Railway variable $key (rerun scripts/setup-r2.sh)")
    fi
  done
else
  SKIPPED+=("scripts/setup-r2.sh — photo proof uploads stay broken until it runs")
fi
pause

# ── 12 ──────────────────────────────────────────────────────────────────
stage "Device test — M3.4 purchase, restore, partner"
warn "From here on you need a real device, a dev client built AFTER stage 3,"
warn "and the sandbox tester from stage 6 signed in."
say ""
say "Sign in as a parent whose Clerk account exists in this household."
check "M3.4 sandbox purchase" "Hitting a gate shows the paywall with all three prices, and buying one succeeds."
check "M3.4 premium without restart" "Premium unlocks in the running app — no force-quit needed."
check "M3.4 restore on reinstall" "Delete the app, reinstall, sign in, Restore Purchases → premium returns with no local state."
check "M3.4 partner sees premium" "The second parent, who bought nothing, sees the household as premium."
pause

# ── 13 ──────────────────────────────────────────────────────────────────
stage "Device test — M3.12 photo proof"
say "Needs stage 10 to have completed, and a chore with photo proof required."
check "M3.12 camera opens" "Tapping done on a photo-proof chore opens the camera from the done moment."
check "M3.12 waiting copy" "After the snap the card reads as waiting for a parent, not as complete."
check "M3.12 offline upload" "In airplane mode the snap is accepted, and it uploads once the network returns."
pause

# ── 14 ──────────────────────────────────────────────────────────────────
stage "Device test — M3.8 allowance screen and RTL"
check "M3.8 allowance screen" "The allowance screen renders correctly on the device."
check "M3.8 Hebrew RTL" "With the device language set to Hebrew the screen mirrors properly — no clipped or reversed numbers."
pause

# ── 15 ──────────────────────────────────────────────────────────────────
stage "Device test — the M3 exit criterion"
say "One pass, end to end, on a free household."
check "quota shows a price" "A free household adding a second child hits the quota and sees a price."
check "webhook flips entitlement" "A sandbox purchase flips the household to premium via the webhook."
check "custom reward" "A custom reward can be added and redeemed."
check "payout drops coins" "A payout is recorded and the child's coins drop."
check "history past 7 days" "The grid scrolls past 7 days."
check "photo chore pays" "A photo chore is completed, approved, and pays."
pause

# ── 16 ──────────────────────────────────────────────────────────────────
stage "Report back to issue #$ISSUE"
say "Posting the hand-test results as a comment."
if (( ${#RESULTS[@]} == 0 )); then
  warn "No hand-test results recorded — nothing to report."
  SKIPPED+=("the hand-test comment on issue #$ISSUE")
  finish
  exit 0
fi
comment=$(printf '## Hand-test results\n\nRun via `scripts/setup-premium.sh` on %s.\n\n%s\n' \
  "$(date -u '+%Y-%m-%d %H:%M UTC')" "$(printf '%s\n' "${RESULTS[@]}")")
printf '\n%s\n\n' "$comment"
if confirm "Post this to issue #$ISSUE?"; then
  if printf '%s' "$comment" | gh issue comment "$ISSUE" --body-file - >/dev/null 2>&1; then
    printf '  %s✓ posted%s to issue #%s\n' "$GREEN" "$RESET" "$ISSUE"
  else
    warn "gh could not post — copy the comment above onto the issue by hand."
    SKIPPED+=("the hand-test comment on issue #$ISSUE")
  fi
else
  SKIPPED+=("the hand-test comment on issue #$ISSUE")
fi
pause

finish
