#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES — M7.2 Android push via FCM (GitHub issue #109).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# open_url override — the library opens the default browser, which here is Arc.
# These dashboards are worked in Chrome, so target it by name and fall back to
# the library's behaviour if it is not installed.
BROWSER_APP="${BROWSER_APP:-Google Chrome}"
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s %s(%s)%s\n' "$GREEN" "$RESET" "$url" "$DIM" "$BROWSER_APP" "$RESET"
  if [[ "$OSTYPE" == darwin* ]] && open -a "$BROWSER_APP" "$url" >/dev/null 2>&1; then
    return
  fi
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser - visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser - visit it manually: $url"
}

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
MOBILE_DIR="$REPO_ROOT/apps/mobile"
GOOGLE_SERVICES="$MOBILE_DIR/google-services.json"
PACKAGE="com.mibokids.app"
ISSUE=109
# Remembered between runs; nothing secret goes in here — the service-account key
# is only ever referenced by its path, never copied. The parent email is
# personal, which is why the file is ignored.
ENV_FILE="$REPO_ROOT/scripts/.env.setup-fcm"   # ignored by .gitignore's .env.*

RESULTS=()

# check "label" "what the tester should see" — record a pass/fail for the issue comment.
check() {
  local label="$1" expectation="$2" reply=""
  step "$expectation"
  printf '  %s? %s — did that happen? [y/n/Enter = not yet]%s ' "$YELLOW" "$label" "$RESET"
  read -r reply || true
  case "$reply" in
    [Yy]*)
      RESULTS+=("- [x] $label — $expectation")
      printf '  %s✓ recorded as passing%s\n' "$GREEN" "$RESET" ;;
    [Nn]*)
      RESULTS+=("- [ ] $label — FAILED: $expectation")
      printf '  %s✗ recorded as failing%s\n' "$RED" "$RESET" ;;
    *)
      RESULTS+=("- [ ] $label — not yet run: $expectation")
      printf '  %s· recorded as not yet run%s\n' "$DIM" "$RESET" ;;
  esac
}

# record "label" "outcome" pass|fail — a result the wizard measured itself.
record() {
  if [[ "$3" == pass ]]; then
    RESULTS+=("- [x] $1 — $2")
    printf '  %s✓ %s%s\n' "$GREEN" "$2" "$RESET"
  else
    RESULTS+=("- [ ] $1 — FAILED: $2")
    printf '  %s✗ %s%s\n' "$RED" "$2" "$RESET"
  fi
}

# expand_path "~/x" — the path with a leading ~ resolved; `read` leaves it literal.
expand_path() { local p="$1"; printf '%s' "${p/#\~/$HOME}"; }

# `railway run` injects the api service's variables. DATABASE_URL among them is
# the private-network host, unreachable from a laptop; DATABASE_PUBLIC_URL is the
# proxy that resolves (same reasoning as scripts/device-hand-tests.sh).
_psql_at() {
  cd "$REPO_ROOT" && railway run --service api -- sh -c "psql -At \"\${DATABASE_PUBLIC_URL:-\$DATABASE_URL}\" -c \"$1\""
}

banner "Mibo Android push — Firebase, FCM V1 key, EAS, device check"

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools the later stages shell out to."
missing=0
for tool in jq eas railway psql pnpm gh; do
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$tool"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$tool"
    missing=1
  fi
done
if (( missing )); then
  warn "Install the missing tools first — stages 6, 8, 9 and 10 need them."
  confirm "Continue anyway?" || exit 1
fi
say ""
if eas_user=$(cd "$MOBILE_DIR" && eas whoami 2>/dev/null); then
  printf '  %s✓%s EAS signed in as %s\n' "$GREEN" "$RESET" "$(printf '%s' "$eas_user" | head -n1)"
else
  warn "eas whoami failed — run 'eas login' in another terminal before stage 6."
fi
if jq -e '.expo.android.googleServicesFile == "./google-services.json"' "$MOBILE_DIR/app.json" >/dev/null; then
  printf '  %s✓%s app.json points android.googleServicesFile at ./google-services.json\n' "$GREEN" "$RESET"
else
  warn "apps/mobile/app.json has no android.googleServicesFile — this branch predates #109."
  confirm "Continue anyway?" || exit 1
fi
pause "Press Enter when the tooling looks right."

# ── 2 ───────────────────────────────────────────────────────────────────
stage "Firebase — the project"
say "Android remote push goes through FCM, and FCM belongs to a Firebase project."
say "iOS is untouched by all of this: it pushes through APNs, which EAS already holds."
open_url "https://console.firebase.google.com/"
step "Create a project named 'Mibo' (or open it if it already exists)."
step "When asked about Google Analytics: turn it OFF."
note "  Nothing in the app would send to it — expo-notifications pulls in Firebase"
note "  Messaging only, not the Analytics SDK — but an unused analytics property on"
note "  a kids' app is one more thing to explain on Play's Data safety form. Children"
note "  are anonymous in analytics (ADR-0009) and PostHog is the only analytics."
pause "Press Enter once the project exists."

# ── 3 ───────────────────────────────────────────────────────────────────
stage "Firebase — the Android app and google-services.json"
open_url "https://console.firebase.google.com/"
step "Project overview → Add app → Android."
step "Android package name: $PACKAGE        ← exactly this; it cannot be changed later."
step "App nickname: Mibo Android. Leave the SHA-1 blank — push does not need it."
step "Register app → Download google-services.json."
step "Skip the 'Add Firebase SDK' steps — expo-notifications does that at prebuild."
say ""
downloaded=""
while :; do
  printf '  %sPath to the downloaded file%s %s[~/Downloads/google-services.json]%s ' \
    "$BOLD" "$RESET" "$DIM" "$RESET"
  read -r downloaded || true
  downloaded=$(expand_path "${downloaded:-~/Downloads/google-services.json}")
  if [[ ! -f "$downloaded" ]]; then
    warn "No file at $downloaded."
  elif ! jq -e --arg p "$PACKAGE" \
      '[.client[].client_info.android_client_info.package_name] | index($p) != null' \
      "$downloaded" >/dev/null 2>&1; then
    warn "That file has no client for $PACKAGE — download it from the right app."
  else
    break
  fi
  confirm "Try another path?" || { SKIPPED+=("apps/mobile/google-services.json"); downloaded=""; break; }
done
if [[ -f "$downloaded" ]] && [[ "$downloaded" != "$GOOGLE_SERVICES" ]]; then
  cp "$downloaded" "$GOOGLE_SERVICES"
  printf '  %s✓ copied%s → apps/mobile/google-services.json\n' "$GREEN" "$RESET"
fi
FIREBASE_PROJECT_ID=""
if [[ -f "$GOOGLE_SERVICES" ]]; then
  FIREBASE_PROJECT_ID=$(jq -r '.project_info.project_id' "$GOOGLE_SERVICES")
  write_env FIREBASE_PROJECT_ID "$FIREBASE_PROJECT_ID"
  note "Firebase project id: $FIREBASE_PROJECT_ID"
fi
say ""
note "This file is public configuration, not a secret — the same values end up"
note "inside every APK anyone can download — so it is committed (stage 7). EAS"
note "Build uploads only what git would, so an ignored copy would never reach a build."
pause

# ── 4 ───────────────────────────────────────────────────────────────────
stage "Firebase — the FCM V1 service-account key"
say "This one IS a secret: it lets anyone send push as Mibo. It goes to EAS and"
say "nowhere else — never into the repo, never into Railway."
open_url "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID:-_}/settings/serviceaccounts/adminsdk"
step "Project settings → Service accounts → Firebase Admin SDK."
step "Generate new private key → Generate key. A JSON file downloads."
step "Move it OUT of Downloads to somewhere private, e.g. your password manager's"
note "  attachments or ~/.secrets/. Not anywhere under $REPO_ROOT."
say ""
SA_KEY=""
while :; do
  ask SA_KEY_PATH "Path to the service-account key JSON:"
  SA_KEY=$(expand_path "${SA_KEY_PATH:-}")
  if [[ ! -f "$SA_KEY" ]]; then
    warn "No file at '$SA_KEY'."
  elif [[ "$(cd -- "$(dirname -- "$SA_KEY")" && pwd)/" == "$REPO_ROOT/"* ]]; then
    warn "That file is inside the repo. Move it out — one 'git add .' and it is public."
  elif ! jq -e '.type == "service_account"' "$SA_KEY" >/dev/null 2>&1; then
    warn "That is not a service-account key (no \"type\": \"service_account\")."
  elif [[ -n "$FIREBASE_PROJECT_ID" ]] \
      && [[ "$(jq -r '.project_id' "$SA_KEY")" != "$FIREBASE_PROJECT_ID" ]]; then
    warn "The key belongs to project '$(jq -r '.project_id' "$SA_KEY")', not '$FIREBASE_PROJECT_ID'."
    note "  A key from another project sends fine and every push fails MismatchSenderId."
  else
    write_env SA_KEY_PATH "$SA_KEY_PATH"
    printf '  %s✓%s %s (project %s)\n' "$GREEN" "$RESET" \
      "$(jq -r '.client_email' "$SA_KEY")" "$(jq -r '.project_id' "$SA_KEY")"
    break
  fi
  confirm "Try another path?" || { SKIPPED+=("the FCM V1 service-account key"); SA_KEY=""; break; }
done
pause

# ── 5 ───────────────────────────────────────────────────────────────────
stage "Google Cloud — the FCM V1 API and the key's role"
say "Firebase usually does both for you. Check, because either one missing"
say "fails every push with an error that reads like a wrong key."
open_url "https://console.cloud.google.com/apis/library/fcm.googleapis.com?project=${FIREBASE_PROJECT_ID:-}"
step "Firebase Cloud Messaging API must read 'API Enabled'. If not: Enable."
note "  Not the 'Cloud Messaging' legacy API — Google shut that one off in 2024."
say ""
open_url "https://console.cloud.google.com/iam-admin/iam?project=${FIREBASE_PROJECT_ID:-}"
step "Find the firebase-adminsdk-… principal (the client_email above)."
step "It needs a role that can send: 'Firebase Admin SDK Administrator Service Agent'"
note "  (the default) or 'Firebase Cloud Messaging API Admin'."
note "If stage 4 refused to generate a key, an org policy"
note "(iam.disableServiceAccountKeyCreation) is blocking it — lift it for this project"
note "under IAM & Admin → Organization policies, then go back to stage 4."
pause "Press Enter once the API is enabled and the role is there."

# ── 6 ───────────────────────────────────────────────────────────────────
stage "EAS — upload the key (Android → Push Notifications: FCM V1)"
say "EAS holds the key and Expo's push service uses it to reach FCM on your behalf."
say "The menu path, which 'eas credentials' is about to show you:"
step "Select platform: Android"
step "Build profile: production    (credentials are per package, so this covers every profile)"
step "Google Service Account"
step "Manage your Google Service Account Key for Push Notifications (FCM V1)"
step "Set up a Google Service Account Key for Push Notifications (FCM V1)"
step "Upload a new service account key → path:"
printf '      %s%s%s\n' "$BOLD" "${SA_KEY:-<the key from stage 4>}" "$RESET"
note "Then choose 'Go back' / Exit until it returns here."
say ""
if confirm "Run 'eas credentials -p android' now?"; then
  (cd "$MOBILE_DIR" && eas credentials -p android) \
    || warn "eas credentials exited non-zero — check the key shows up on the dashboard below."
else
  SKIPPED+=("upload the FCM V1 key: cd apps/mobile && eas credentials -p android")
fi
say ""
open_url "https://expo.dev/accounts/nadavg/projects/mibo/credentials"
step "Android → $PACKAGE → 'FCM V1 service account key' shows the firebase-adminsdk email."
note "Once it is there the local file is only a backup — keep it private or delete it;"
note "a new one can always be generated in stage 4."
pause "Press Enter once EAS shows the key."

# ── 7 ───────────────────────────────────────────────────────────────────
stage "Commit google-services.json"
say "Android builds fail at prebuild without it: app.json names the file."
if [[ ! -f "$GOOGLE_SERVICES" ]]; then
  warn "apps/mobile/google-services.json does not exist — stage 3 did not finish."
  SKIPPED+=("commit apps/mobile/google-services.json")
elif git -C "$REPO_ROOT" diff --quiet HEAD -- "$GOOGLE_SERVICES" 2>/dev/null \
    && git -C "$REPO_ROOT" ls-files --error-unmatch "$GOOGLE_SERVICES" >/dev/null 2>&1; then
  printf '  %s✓%s already committed, unchanged\n' "$GREEN" "$RESET"
else
  git -C "$REPO_ROOT" status --short -- "$GOOGLE_SERVICES" | sed 's/^/    /'
  if confirm "Commit it to $(git -C "$REPO_ROOT" branch --show-current) now?"; then
    git -C "$REPO_ROOT" add -- "$GOOGLE_SERVICES"
    git -C "$REPO_ROOT" commit -m "chore(mobile): google-services.json for Android push (#$ISSUE)" -- "$GOOGLE_SERVICES" \
      && printf '  %s✓ committed%s — push it before building on EAS\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("commit apps/mobile/google-services.json")
  fi
fi
pause

# ── 8 ───────────────────────────────────────────────────────────────────
stage "Production build on a physical Android device"
say "The first acceptance criterion is a *production-profile* build, because that is"
say "the one testers get. It is an .aab, so it reaches a phone through Play."
say ""
if confirm "Start 'eas build -p android --profile production' now?"; then
  (cd "$MOBILE_DIR" && eas build --platform android --profile production) \
    || { warn "The build failed — read the EAS log before carrying on."; SKIPPED+=("production Android build"); }
else
  note "Run it yourself: cd apps/mobile && eas build --platform android --profile production"
fi
say ""
open_url "https://play.google.com/console"
step "Mibo → Test and release → Internal testing → Create new release."
step "Upload the .aab from the EAS build page → Save → Start rollout."
note "  Play rejects a versionCode it has already seen. If it does:"
note "    cd apps/mobile && eas build:version:set -p android   then rebuild."
note "  No internal track yet? scripts/setup-play-listing.sh stage 9 sets it up."
step "On the phone: install Mibo from the internal-testing link."
step "Sign in as a parent and allow notifications: on the push screen after"
note "  connecting, or later from More → Evening summary → Allow. That row only shows"
note "  while Android can still ask; if it is gone, allow Mibo in Android Settings →"
note "  Apps → Mibo → Notifications, then close and reopen the app (it registers on open)."
pause "Press Enter once the parent is signed in with notifications allowed."

# ── 9 ───────────────────────────────────────────────────────────────────
stage "Verify — the device registered an Expo push token"
say "Reading the token straight from the live database, so the check is the server's"
say "view rather than the app's."
PUSH_TO=""
PUSH_LOCALE="en"
while :; do
  ask PARENT_EMAIL "Email of the parent you signed in as:"
  # Lower-cased as the server stores it, and matched against a strict pattern so
  # nothing typed here can carry SQL or shell through the quoting to psql.
  PARENT_EMAIL=$(printf '%s' "$PARENT_EMAIL" | tr '[:upper:]' '[:lower:]')
  if [[ "$PARENT_EMAIL" =~ ^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]+$ ]]; then
    write_env PARENT_EMAIL "$PARENT_EMAIL"
    break
  fi
  warn "That does not look like an email."
done
TOKEN_SQL="select d.expo_push_token || ' ' || d.locale from parent_devices d join parents p on p.id = d.parent_id where p.email = '$PARENT_EMAIL' and d.platform = 'android' and d.expo_push_token is not null order by d.last_seen_at desc limit 1;"
row=""
if command -v railway >/dev/null 2>&1 && command -v psql >/dev/null 2>&1; then
  row=$(_psql_at "$TOKEN_SQL" 2>/dev/null | tail -n1 || true)
else
  warn "railway or psql missing — cannot read the token."
fi
# The server's expoPushTokenSchema accepts both prefixes; so does this.
if [[ "$row" =~ ^(Expo(nent)?PushToken\[[^][:space:]]+\])\ (en|he)$ ]]; then
  PUSH_TO="${BASH_REMATCH[1]}"
  PUSH_LOCALE="${BASH_REMATCH[3]}"
  record "Expo push token" "A production Android build registered an Expo push token for $PARENT_EMAIL (locale $PUSH_LOCALE)." pass
else
  record "Expo push token" "No Android push token on the server for $PARENT_EMAIL." fail
  note "Most likely, in order:"
  note "  · the build predates google-services.json (stage 7) — getExpoPushTokenAsync"
  note "    throws 'Default FirebaseApp is not initialized' without it;"
  note "  · notifications were not allowed, so the app never asked for a token;"
  note "  · the app was not reopened after allowing."
  note "  adb logcat | grep 'parent push registration failed' shows the device's reason."
fi
pause

# ── 10 ──────────────────────────────────────────────────────────────────
stage "Verify — a Digest push arrives"
say "Sends one Digest through apps/api/src/push.ts — the same client the cron uses —"
say "with EXPO_ACCESS_TOKEN from Railway, then reads the receipt back from Expo."
note "It does not go through the cron: that would spend tonight's real claim."
# The body of the send. Kept here rather than as a file under apps/api because it
# is a one-off check, not something the server ships. tsx -e compiles to CJS, so
# the top-level awaits live inside an async function.
read -r -d '' SEND_TS <<'TS' || true
(async () => {
  const { expoPush } = await import('./src/push.ts');
  const { digestCopy } = await import('@chores/shared');
  const to = process.env.PUSH_TO!;
  const locale = process.env.PUSH_LOCALE === 'he' ? 'he' : 'en';
  const push = expoPush(process.env.EXPO_ACCESS_TOKEN || undefined);
  const copy = digestCopy(locale, {
    children: [{ first_name: 'Mibo', due_count: 3, done_count: 2 }],
    undecided_redemptions: 1,
  });
  const [sent] = await push.send([
    {
      to,
      ...copy,
      data: {
        kind: 'parent_digest',
        chore_date: new Date().toISOString().slice(0, 10),
        path: '/(parent)',
      },
    },
  ]);
  if (!sent.ok) {
    console.log(`TICKET ${sent.error}`);
    process.exit(2);
  }
  // FCM's answer lands on the receipt, not the ticket: a wrong key sends "ok" and fails here.
  for (let i = 0; i < 6; i++) {
    await new Promise((r) => setTimeout(r, 5000));
    const receipt = (await push.receipts([sent.ticket]))[sent.ticket];
    if (receipt) {
      console.log(receipt.ok ? 'RECEIPT ok' : `RECEIPT ${receipt.error}`);
      process.exit(receipt.ok ? 0 : 2);
    }
  }
  console.log('RECEIPT pending');
  process.exit(2);
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
TS
if [[ -z "$PUSH_TO" ]]; then
  warn "No token from stage 9 — nothing to send to."
  record "Digest arrives" "Not sent: no Android push token." fail
else
  step "Put the phone down with the app in the background or closed."
  pause "Press Enter to send."
  out=$(cd "$REPO_ROOT" && PUSH_TO="$PUSH_TO" PUSH_LOCALE="$PUSH_LOCALE" \
    railway run --service api -- pnpm --filter api exec tsx -e "$SEND_TS" 2>&1 | tail -n1 || true)
  printf '  %s%s%s\n' "$DIM" "$out" "$RESET"
  case "$out" in
    "RECEIPT ok")
      printf '  %s✓ Expo and FCM accepted it%s\n' "$GREEN" "$RESET" ;;
    *InvalidCredentials*)
      warn "EAS has no FCM V1 key for $PACKAGE, or the API in stage 5 is off." ;;
    *MismatchSenderId*)
      warn "google-services.json and the service-account key are from different projects." ;;
    *DeviceNotRegistered*)
      warn "FCM no longer knows this install — reinstall, reopen, and rerun from stage 9." ;;
    *)
      warn "Unexpected answer — see the line above." ;;
  esac
  check "Digest arrives" "A Mibo Evening summary notification appeared on the Android phone."
fi
pause

# ── report ──────────────────────────────────────────────────────────────
_clear
printf '\n%s%s▸ Report back to issue #%s%s\n' "$BOLD" "$BLUE" "$ISSUE" "$RESET"
if (( ${#RESULTS[@]} == 0 )); then
  warn "No results recorded — nothing to report."
  SKIPPED+=("the results comment on issue #$ISSUE")
  finish
  exit 0
fi
comment=$(printf '## FCM setup results\n\nRun via `scripts/setup-fcm.sh` on %s.\n\n%s\n' \
  "$(date -u '+%Y-%m-%d %H:%M UTC')" "$(printf '%s\n' "${RESULTS[@]}")")
printf '\n%s\n\n' "$comment"
if confirm "Post this to issue #$ISSUE?"; then
  if printf '%s' "$comment" | gh issue comment "$ISSUE" --body-file - >/dev/null 2>&1; then
    printf '  %s✓ posted%s to issue #%s\n' "$GREEN" "$RESET" "$ISSUE"
  else
    warn "gh could not post — copy the comment above onto the issue by hand."
    SKIPPED+=("the results comment on issue #$ISSUE")
  fi
else
  SKIPPED+=("the results comment on issue #$ISSUE")
fi
pause

finish
