#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — M6.5 Play Console listing and internal testing (GitHub issue #103), and
# M7.5 App content: access, ads, rating, audience, Data safety (GitHub issue #112).
#
#   scripts/setup-play-listing.sh                the whole wizard
#   scripts/setup-play-listing.sh --app-content  only the App content stages; reports
#                                                to #112 instead of #103
#   scripts/setup-play-listing.sh --check        only count docs/store/listing.md against
#                                                the store limits; exits 1 on any failure
# ──────────────────────────────────────────────────────────────────────────

APP_CONTENT_ONLY=0
case "${1:-}" in
  "" | --check) ;;
  --app-content) APP_CONTENT_ONLY=1 ;;
  *) printf 'usage: %s [--app-content | --check]\n' "$0" >&2; exit 2 ;;
esac
# Preflight, contact and policy, six App content stages, verify, report — plus the
# listing's seven when the whole wizard runs.
if (( APP_CONTENT_ONLY )); then TOTAL_STAGES=10; else TOTAL_STAGES=17; fi

# Play Console is worked in Chrome, not the default browser — same wrapper as
# scripts/setup-store-listing.sh.
BROWSER_APP="${BROWSER_APP:-Google Chrome}"
open_url_chrome() {
  local url="$1"
  if [[ "$OSTYPE" == darwin* ]] && open -a "$BROWSER_APP" "$url" >/dev/null 2>&1; then
    printf '  %s↗ opening%s %s %s(%s)%s\n' "$GREEN" "$RESET" "$url" "$DIM" "$BROWSER_APP" "$RESET"
    return
  fi
  open_url "$url"
}

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
SPEC="$REPO_ROOT/docs/spec/05-store-listing.md"
LISTING="$REPO_ROOT/docs/store/listing.md"
SCREENSHOTS="$REPO_ROOT/docs/store/screenshots"
STORE_WIZARD="$REPO_ROOT/scripts/setup-store-listing.sh"
API_BASE="${API_BASE:-https://mibokids.app}"
PRIVACY_URL="$API_BASE/privacy"
TERMS_URL="$API_BASE/terms"
WEBSITE_URL="$API_BASE"
PACKAGE="com.mibokids.app"
PLAY_CONSOLE="https://play.google.com/console"
DELETE_ACCOUNT_URL="$API_BASE/delete-account"
REVIEW_NOTES="$REPO_ROOT/docs/store/review-notes.md"
if (( APP_CONTENT_ONLY )); then ISSUE=112; else ISSUE=103; fi

# The Play title, docs/spec/05-store-listing.md. Play indexes the long description
# separately, so the title carries the "for Kids" iOS keeps in its subtitle — and
# Play's title is Play's business, not guideline 2.3.8's.
PLAY_TITLE="Mibo: Chores Tracker for Kids"

# Every block docs/store/listing.md must hold. Each one's limit lives on its marker
# line in that file, so the limit and the copy are reviewed together.
REQUIRED_FIELDS=(
  en.ios.promo en.ios.description en.play.short en.play.full
  he.ios.promo he.ios.description he.play.short he.play.full
)

RESULTS=()
TESTER_COUNT=0
CONTACT_EMAIL=""

# A UTF-8 locale for counting: both stores count characters, and under the C locale
# a Hebrew letter is two bytes and every Hebrew field reads as twice its length.
UTF8_LOCALE=""
for l in C.UTF-8 en_US.UTF-8 C.utf8 en_US.utf8; do
  if [[ "$(printf 'א' | LC_ALL=$l wc -m 2>/dev/null | tr -d ' ')" == "1" ]]; then
    UTF8_LOCALE="$l"; break
  fi
done

# chars "text" — its length in characters, as the stores count it.
chars() { printf '%s' "$1" | LC_ALL="$UTF8_LOCALE" wc -m | tr -d ' '; }

# listing_field KEY — the text of one block of docs/store/listing.md: the lines
# between the ```text fence after its marker and the closing fence.
listing_field() {
  awk -v key="$1" '
    index($0, "<!-- field: " key " ") == 1 { f = 1; next }
    f == 1 && /^```/ { f = 2; next }
    f == 2 && /^```/ { exit }
    f == 2 { print }
  ' "$LISTING"
}

# listing_limit KEY — the limit=N on that block's marker.
listing_limit() {
  grep -F -- "<!-- field: $1 " "$LISTING" | sed -nE 's/.*limit=([0-9]+).*/\1/p' | head -n1
}

# subscription_blurb — the 3.1.2 paragraph exactly as scripts/setup-store-listing.sh
# pastes it, rebuilt from that script's source rather than copied into this one: two
# copies of the paragraph Apple rejects on are two copies that drift.
subscription_blurb() {
  local src bs='\$' d='$'
  src=$(sed -n '/^SUBSCRIPTION_BLURB=/,/PRIVACY_URL"$/p' "$STORE_WIZARD")
  [[ -n "$src" ]] || return 1
  src=${src#SUBSCRIPTION_BLURB=\"}
  src=${src%\"}
  src=${src//$'\\\n'/}
  src=${src//"$bs"/"$d"}
  src=${src//'$TERMS_URL'/"$TERMS_URL"}
  src=${src//'$PRIVACY_URL'/"$PRIVACY_URL"}
  printf '%s' "$src"
}

# ok / bad "line" — one preflight verdict.
ok()  { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
bad() { printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"; listing_ok=0; }

# check_listing — every block present, inside its store limit, and saying what the
# rules at the top of docs/store/listing.md say it must. Non-zero on any failure.
check_listing() {
  listing_ok=1
  if [[ -z "$UTF8_LOCALE" ]]; then
    bad "no UTF-8 locale — Hebrew cannot be counted in characters"
    return 1
  fi
  if [[ ! -f "$LISTING" ]]; then
    bad "docs/store/listing.md is missing"
    return 1
  fi
  local key text limit n
  for key in "${REQUIRED_FIELDS[@]}"; do
    text=$(listing_field "$key")
    limit=$(listing_limit "$key")
    if [[ -z "$text" || -z "$limit" ]]; then
      bad "$(printf '%-18s missing, or its marker has no limit' "$key")"
      continue
    fi
    n=$(chars "$text")
    if (( n <= limit )); then
      ok "$(printf '%-18s %4s/%s' "$key" "$n" "$limit")"
    else
      bad "$(printf '%-18s %4s/%s — over the limit' "$key" "$n" "$limit")"
    fi
  done

  n=$(chars "$PLAY_TITLE")
  if grep -Fq -- "\`$PLAY_TITLE\`" "$SPEC" 2>/dev/null && (( n <= 30 )); then
    ok "$(printf '%-18s %4s/30, and still the spec'\''s' "play title" "$n")"
  else
    bad "play title '$PLAY_TITLE' — over 30, or no longer in docs/spec/05-store-listing.md"
  fi

  # 3.1.2: the English iOS description ends with the store wizard's paragraph, verbatim.
  local blurb desc fact
  blurb=$(subscription_blurb || true)
  desc=$(listing_field en.ios.description)
  if [[ -n "$blurb" && "$desc" == *"$blurb" ]]; then
    ok "en.ios.description ends with setup-store-listing.sh's 3.1.2 paragraph"
  else
    bad "en.ios.description does not end with setup-store-listing.sh's 3.1.2 paragraph"
  fi
  # The Hebrew one is a translation, so its facts are checked rather than its words.
  desc=$(listing_field he.ios.description)
  for fact in '$6.99' '$39.99' '$79.99' '24' "$TERMS_URL" "$PRIVACY_URL"; do
    if [[ "$desc" != *"$fact"* ]]; then
      bad "he.ios.description's 3.1.2 paragraph is missing '$fact'"
    fi
  done

  # Play's descriptions are Play's: no Apple Account, no Sign in with Apple (iOS only).
  for key in en.play.full he.play.full; do
    if [[ "$(listing_field "$key")" == *Apple* ]]; then
      bad "$key mentions Apple — Play's copy must not"
    fi
  done
  # 2.3.8: the prose is written to the parent, never claiming children as the audience.
  for key in en.ios.promo en.ios.description en.play.short en.play.full; do
    if listing_field "$key" | grep -qiE 'for (kids|children)'; then
      bad "$key says 'for kids' or 'for children' — 2.3.8, ADR-0018"
    fi
  done

  (( listing_ok ))
}

# clip_tool — the clipboard command on this machine, if any.
clip_tool() {
  if   command -v pbcopy   >/dev/null 2>&1; then printf 'pbcopy'
  elif command -v wl-copy  >/dev/null 2>&1; then printf 'wl-copy'
  elif command -v xclip    >/dev/null 2>&1; then printf 'xclip -selection clipboard'
  elif command -v clip.exe >/dev/null 2>&1; then printf 'clip.exe'
  fi
}

# copy_quiet "what" "value" — onto the clipboard without printing it, for blocks of
# up to 4000 characters that would scroll the instructions off the screen.
copy_quiet() {
  local label="$1" value="$2" tool
  tool=$(clip_tool)
  if [[ -z "$tool" ]]; then
    note "  (no clipboard tool — copy it from docs/store/listing.md by hand)"
    return
  fi
  # shellcheck disable=SC2086  # the tool string carries its own flags
  if printf '%s' "$value" | $tool >/dev/null 2>&1; then
    printf '  %s✎ on the clipboard%s %s%s (%s chars)%s\n' \
      "$GREEN" "$RESET" "$DIM" "$label" "$(chars "$value")" "$RESET"
  else
    note "  (clipboard write failed — copy it from docs/store/listing.md by hand)"
  fi
}

# copy "what" "value" — as scripts/setup-store-listing.sh: print it, then clipboard.
copy() {
  printf '  %s%s%s\n' "$BOLD" "$2" "$RESET"
  copy_quiet "$1" "$2"
}

# copy_field "what" KEY — one block of docs/store/listing.md onto the clipboard.
copy_field() { copy_quiet "$1" "$(listing_field "$2")"; }

# next_paste "what" — hold the clipboard until the human has pasted the last value.
next_paste() { pause "Pasted? Enter puts $1 on the clipboard."; }

# play_access_notes — the "Any other information" box for App access: the ```text
# block after <!-- play-access --> in docs/store/review-notes.md.
play_access_notes() {
  awk '
    index($0, "<!-- play-access -->") == 1 { f = 1; next }
    f == 1 && /^```/ { f = 2; next }
    f == 2 && /^```/ { exit }
    f == 2 { print }
  ' "$REVIEW_NOTES"
}

# ds_decl "Category → Type" "required|optional" "purposes" — one Data safety data
# type, in the order Play asks. Collected, never shared: every recipient is a service
# provider acting on our instructions (Clerk, Railway, R2, PostHog, Sentry, RevenueCat,
# Expo), which Play's definition of "shared" exempts. Never ephemeral: all of it is
# stored. Saying both once keeps the declarations from drifting apart.
ds_decl() {
  local type="$1" required="$2" purposes="$3"
  step "$type"
  printf '      %s%-22s%s %s\n' "$DIM" "Collected / shared:" "$RESET" "Collected (not shared)"
  printf '      %s%-22s%s %s\n' "$DIM" "Processed ephemerally:" "$RESET" "No"
  printf '      %s%-22s%s %s\n' "$DIM" "Required or optional:" "$RESET" "$required"
  printf '      %s%-22s%s %s\n' "$DIM" "Purposes:" "$RESET" "$purposes"
}

# check "section" "what must be true" — as scripts/setup-store-listing.sh.
check() {
  local label="$1" expectation="$2" reply=""
  step "$expectation"
  printf '  %s? %s — is that true? [y/n/Enter = not yet]%s ' "$YELLOW" "$label" "$RESET"
  read -r reply || true
  case "$reply" in
    [Yy]*)
      RESULTS+=("- [x] $label — $expectation")
      printf '  %s✓ recorded as done%s\n' "$GREEN" "$RESET" ;;
    [Nn]*)
      RESULTS+=("- [ ] $label — FAILED: $expectation")
      printf '  %s✗ recorded as failing%s\n' "$RED" "$RESET" ;;
    *)
      RESULTS+=("- [ ] $label — not yet done: $expectation")
      printf '  %s· recorded as not yet done%s\n' "$DIM" "$RESET" ;;
  esac
}

# count_images DIR — PNG and JPEG files directly in DIR.
count_images() {
  [[ -d "$1" ]] || { printf '0'; return; }
  find "$1" -maxdepth 1 -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' \) \
    | wc -l | tr -d ' '
}

if [[ "${1:-}" == "--check" ]]; then
  check_listing
  exit $?
fi

if (( APP_CONTENT_ONLY )); then
  banner "Mibo — Play Console App content"
else
  banner "Mibo — Play Console listing, App content and internal testing"
fi

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Preflight — tools, the copy, and its lengths"
say "1. The tools the later stages shell out to:"
for tool in curl gh; do
  if command -v "$tool" >/dev/null 2>&1; then
    ok "$tool"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$tool"
    case "$tool" in
      curl) SKIPPED+=("install curl — the preflight cannot tell a live URL from a dead one") ;;
      gh)   SKIPPED+=("install gh — the last stage posts the verification comment with it") ;;
    esac
  fi
done
if [[ -n "$(clip_tool)" ]]; then
  ok "a clipboard tool"
else
  warn "no clipboard tool — every block will have to be copied from docs/store/listing.md by hand"
fi
say ""
say "2. docs/store/listing.md, counted against the stores' limits:"
if ! check_listing; then
  warn "Fix docs/store/listing.md before pasting anything into Play Console."
  exit 1
fi
say ""
say "3. The URLs the listing points at:"
urls_live=1
for url in "$PRIVACY_URL" "$TERMS_URL" "$WEBSITE_URL" "$DELETE_ACCOUNT_URL"; do
  if curl -fsS --max-time 15 -o /dev/null "$url" 2>/dev/null; then
    ok "$url"
  else
    printf '  %s✗%s %s does not answer\n' "$RED" "$RESET" "$url"
    urls_live=0
  fi
done
if (( ! urls_live )); then
  warn "Deploy before the listing goes live: scripts/deploy-api.sh"
  warn "Data safety's Delete account URL must load without errors, or Play rejects it."
  SKIPPED+=("deploy the API so the listing's URLs resolve")
fi
say ""
say "4. The App access notes, docs/store/review-notes.md:"
access_notes=""
[[ -f "$REVIEW_NOTES" ]] && access_notes=$(play_access_notes)
if [[ -z "$access_notes" ]]; then
  printf '  %s✗%s no <!-- play-access --> block\n' "$RED" "$RESET"
  warn "Restore the Play Console App access section of docs/store/review-notes.md."
  exit 1
elif (( $(chars "$access_notes") > 500 )); then
  printf '  %s✗%s %s/500 — Play documents no limit, so keep it under the old one\n' \
    "$RED" "$RESET" "$(chars "$access_notes")"
  exit 1
else
  ok "$(printf '%-18s %4s/500' "play-access" "$(chars "$access_notes")")"
fi
say ""
say "5. The build and the contact address:"
if grep -Fq "\"package\": \"$PACKAGE\"" "$REPO_ROOT/apps/mobile/app.json" 2>/dev/null; then
  ok "apps/mobile/app.json builds $PACKAGE"
else
  warn "apps/mobile/app.json does not name $PACKAGE — stop. Play binds the package on"
  warn "the first upload and it can never change after that."
  exit 1
fi
CONTACT_EMAIL=$(sed -nE "s/^const CONTACT_EMAIL = '([^']+)'.*/\1/p" \
  "$REPO_ROOT/apps/api/src/landing.ts" 2>/dev/null | head -n1 || true)
if [[ -n "$CONTACT_EMAIL" ]]; then
  ok "contact address, from apps/api/src/landing.ts: $CONTACT_EMAIL"
else
  warn "could not read CONTACT_EMAIL from apps/api/src/landing.ts — the contact stage will ask."
fi
pause "Press Enter when the preflight looks right."

if (( ! APP_CONTENT_ONLY )); then
# ── 2 ───────────────────────────────────────────────────────────────────
stage "App details — create the app"
say "Play Console → Home → Create app. Skip to the next stage if Mibo already exists."
open_url_chrome "$PLAY_CONSOLE"
say ""
step "App name:"
copy "App name" "$PLAY_TITLE"
note "  The icon on the device still says 'Mibo' — the launcher label comes from the"
note "  build, not from this field."
step "Default language: English (United States) – en-US"
note "  Mibo's app was created with en-GB and the dashboard shows it as 'Default –"
note "  English (United Kingdom)'. Harmless — every English locale falls back to it —"
note "  but pick en-US here if the app is being created fresh."
step "App or game: App.   Free or paid: Free."
note "  Free is permanent: a free app can never become paid. Premium is sold in-app"
note "  through RevenueCat (scripts/setup-premium.sh), so Free is the right answer."
step "Tick the Developer Program Policies and US export laws declarations → Create app."
say ""
warn "The package name is not asked here. Play binds it on the first upload (stage 15),"
warn "and it must be $PACKAGE — it can never change after that."
pause "Press Enter once the app exists in Play Console."

# ── 3 ───────────────────────────────────────────────────────────────────
stage "Default store listing — English"
say "Grow users → Store presence → Store listings → Create default store listing."
note "  The page is two steps, Assets then Review, and nothing is saved by 'Save as"
note "  draft' alone: the listing counts only once Review → Save has run (stage 6)."
open_url_chrome "$PLAY_CONSOLE"
say ""
step "App name (30):"
copy "App name" "$PLAY_TITLE"
next_paste "the short description"
step "Short description (80):"
copy_field "en short description" en.play.short
next_paste "the full description"
step "Full description (4000):"
copy_field "en full description" en.play.full
note "  Written to the parent (2.3.8, ADR-0018), ending with a Play-worded"
note "  subscription paragraph — Apple's 3.1.2 paragraph says 'Apple Account' and"
note "  has no business on Play."
pause "Press Enter once the English text is saved."

# ── 4 ───────────────────────────────────────────────────────────────────
stage "Default store listing — Hebrew translation"
say "Same page → the language button ('Default – English …') → Manage languages →"
say "search Hebrew → tick Hebrew – iw-IL → Apply. The page switches to iw-IL."
note "  Play still files Hebrew under the old code iw, not he. Not 'Purchase"
note "  translations', and not Translations → Store listings in the sidebar — both"
note "  order bought or machine translation."
say ""
step "App name (30): the English title — the field starts empty and is required."
copy "App name" "$PLAY_TITLE"
note "  docs/spec/05-store-listing.md fixes the title in English only; a Hebrew title"
note "  is an ASO decision the spec has not made."
next_paste "the Hebrew short description"
step "Short description (80):"
copy_field "he short description" he.play.short
next_paste "the Hebrew full description"
step "Full description (4000):"
copy_field "he full description" he.play.full
note "  Paste it as is: the bullets and the Latin 'Mibo' lay out correctly once Play"
note "  renders the page right to left. Judge the preview, not the edit box."
note "  Save as draft, then switch the language button back to the default: the"
note "  graphics and screenshots go on the English listing, and stage 6's Review →"
note "  Save commits both languages' text."
pause "Press Enter once the Hebrew text is in and saved as a draft."

# ── 5 ───────────────────────────────────────────────────────────────────
stage "Graphics — icon and feature graphic"
say "Default store listing → Common visual assets. Both are required."
note "  'Add assets' opens an asset-library panel on the right: Upload puts the file in"
note "  the library already ticked, and the panel's Add puts it in the slot."
say ""
ICON_SRC="$REPO_ROOT/apps/mobile/assets/images/icon.png"
ICON_OUT="$REPO_ROOT/docs/store/play/icon-512.png"
FEATURE="$REPO_ROOT/docs/store/play/feature-graphic.png"
step "App icon: 512 x 512, 32-bit PNG, at most 1 MB."
if [[ -f "$ICON_OUT" ]]; then
  note "  Already made: docs/store/play/icon-512.png"
elif command -v sips >/dev/null 2>&1 && [[ -f "$ICON_SRC" ]] \
  && confirm "Make it now from apps/mobile/assets/images/icon.png?"; then
  mkdir -p "$(dirname "$ICON_OUT")"
  if sips -z 512 512 "$ICON_SRC" --out "$ICON_OUT" >/dev/null 2>&1; then
    printf '  %s✓ wrote%s docs/store/play/icon-512.png\n' "$GREEN" "$RESET"
  else
    warn "sips failed — resize apps/mobile/assets/images/icon.png to 512 x 512 by hand."
  fi
else
  note "  Resize apps/mobile/assets/images/icon.png to 512 x 512."
fi
note "  Use the art the build carries: a listing icon that differs from the launcher"
note "  icon is a metadata-policy strike."
say ""
step "Feature graphic: 1024 x 500, JPEG or 24-bit PNG, no transparency."
if [[ -f "$FEATURE" ]]; then
  note "  Found: docs/store/play/feature-graphic.png"
else
  warn "Nothing in the repo is this shape yet. Keep text away from the edges — Play"
  warn "crops and overlays it — and caption it for the parent, as the screenshots are."
  SKIPPED+=("a 1024 x 500 feature graphic at docs/store/play/feature-graphic.png")
fi
note "  Graphics are per language, and a translation with none uses the default"
note "  language's — so iw-IL needs nothing here."
pause "Press Enter once the icon and feature graphic are uploaded."

# ── 6 ───────────────────────────────────────────────────────────────────
stage "Screenshots — per device class"
say "Default store listing → Phone screenshots, then Tablet assets (collapsed: open"
say "it) → 7-inch and 10-inch."
note "  PNG or JPEG, no transparency, 16:9 or 9:16, each side 320–3840 px"
note "  (10-inch: 1080–7680 px). Two to eight per class; four or more at 1080 px or"
note "  wider on phones make the app eligible for Play's recommendations."
say ""
say "What docs/store/screenshots/android/en/store/ holds right now:"
for class in phone tablet-7 tablet-10; do
  n=$(count_images "$SCREENSHOTS/android/en/store/$class")
  if (( n >= 2 && n <= 8 )); then
    ok "$(printf '%-10s %s' "$class" "$n")"
  else
    printf '  %s✗%s %-10s %s — needs 2 to 8\n' "$YELLOW" "$RESET" "$class" "$n"
  fi
done
note "  Captioned from the seeded review household (#100, #111) by the local-only,"
note "  gitignored nextjs/ generator. A missing set is recorded in stage 16, not blocking."
say ""
step "Upload each folder in file order — the Parent side leads (ADR-0018):"
note "  1. a parent approving a chore   2. setting chores   3. the allowance"
note "  then the child's day, the pet, rewards, and the feature pills."
warn "apps/mobile/app.json sets supportsTablet: true, so the tablet sets matter —"
warn "without them Play marks the app as not designed for tablets."
step "English sets on the default listing only: iw-IL falls back to them."
say ""
warn "Three traps in the asset panel, all met uploading Mibo's sets:"
note "  · Add places a batch in the REVERSE of the panel's most-recent-first order,"
note "    and a multi-file upload finishes in no fixed order. Upload one file at a"
note "    time, 01 first, and the slot comes out in file order. Otherwise drag tiles"
note "    into place — a tile dropped on another's left half lands before it."
note "  · The panel stays bound to the slot it was opened from. Close it (×) before"
note "    clicking the next set's Add assets, or the 10-inch set lands in the 7-inch"
note "    slot (14/8, 'Too many images')."
note "  · A file can drop out of a quick run of single uploads. Count the slot: 7/8."
say ""
step "Next → Review → AI asset declaration:"
note "  Every bundled illustration — bird icon, pet, trees, splash — was generated"
note "  (docs/design/prompts.md). So: 'Label assets as created or edited using AI',"
note "  then tick the icon, the feature graphic and screenshots 01, 04, 05 and 07 in"
note "  each class — the ones that show the bird, the pet or the trees. 02, 03 and 06"
note "  are UI, emoji and the coin only."
step "Label assets and submit → Save → 'Not now' on Go to Publishing overview."
note "  Nothing goes to Google here; the listing is reviewed with the first release."
note "  Run Review → Save again after the Hebrew text, which is a separate save."
pause "Press Enter once both languages are saved and the dashboard's 'Set up your Store Listing' is gone."

# ── 7 ───────────────────────────────────────────────────────────────────
stage "Categorisation — category and tags"
say "Grow users → Store presence → Store settings → App category."
open_url_chrome "$PLAY_CONSOLE"
step "App or game: App.   Category: Parenting."
note "  Parenting is Play's category for exactly this reader, and it keeps the listing"
note "  addressed to the parent. Productivity, the iOS primary, is the fallback."
step "Tags → Manage tags: up to five, the closest Play offers to chores, family and"
step "routines. Play's list is fixed; skip a near miss rather than force it."
note "  Mibo's: Parenting, Personal finance, Productivity. Nothing nearer exists —"
note "  no chores, habit, to-do or family tag."
say ""
warn "Target audience and content (App content) is NOT set here. An age group under"
warn "13 pulls in the Families policy and its SDK requirements — Play's version of"
warn "the question ADR-0018 answers for Apple. It is stage 12."
pause "Press Enter once the category and tags are saved."
fi

# ── 8 ───────────────────────────────────────────────────────────────────
stage "Contact details and privacy policy"
say "Store settings → Store listing contact details. The email is shown publicly."
if [[ -z "$CONTACT_EMAIL" ]]; then
  ask CONTACT_EMAIL "Contact email for the listing:"
fi
step "Email:"
copy "Contact email" "$CONTACT_EMAIL"
next_paste "the website"
step "Website:"
copy "Website" "$WEBSITE_URL"
note "  The apex serves the support page (#84) — App Store Connect's Support URL too."
step "Phone: leave empty."
next_paste "the privacy policy URL"
say ""
step "Policy and programs → App content → Privacy policy:"
copy "Privacy policy URL" "$PRIVACY_URL"
note "  The rest of App content is the next six stages."
pause "Press Enter once contact details and the policy URL are saved."

# ── 9 ───────────────────────────────────────────────────────────────────
stage "App content — App access"
say "Policy and programs → App content → App access. Parents sign in, so a reviewer"
say "needs the #100 review account — the same one App Review gets."
open_url_chrome "$PLAY_CONSOLE"
say ""
step "First, rebuild the review household so the reviewer never inherits the last"
step "reviewer's state (every R2_* variable is required — docs/store/review-notes.md):"
note "    DATABASE_URL=… CLERK_SECRET_KEY=… R2_ACCOUNT_ID=… R2_BUCKET=… \\"
note "    R2_ACCESS_KEY_ID=… R2_SECRET_ACCESS_KEY=… pnpm --filter api seed:review"
if ! confirm "Re-seeded just now?"; then
  SKIPPED+=("re-seed the review household before Play reviews it (pnpm --filter api seed:review)")
fi
say ""
step "Choose: All or some functionality is restricted → Add instructions."
step "Instruction name:"
copy "Instruction name" "Demo parent account"
next_paste "the username"
step "Username:"
copy "Username" "review@mibokids.app"
say ""
step "Password: the value of REVIEW_SECRET on Railway. Type it in Play Console"
step "only — it is never written into this repo or onto this clipboard."
pause "Password typed? Enter puts the other information on the clipboard."
step "Any other information required to access your app:"
copy_quiet "App access notes" "$(play_access_notes)"
note "  From docs/store/review-notes.md. Play wants reusable credentials that skip any"
note "  one-time code; the password typed where the code goes is exactly that."
step "Leave 'no other information required' unticked → Add → Save."
pause "Press Enter once App access is saved."

# ── 10 ──────────────────────────────────────────────────────────────────
stage "App content — Ads, Advertising ID and the declarations that do not apply"
say "App content lists each of these as its own section. Answer every one: an"
say "unanswered section blocks every release, including internal testing."
say ""
step "Ads → Does your app contain ads? → No."
note "  No ads and no advertising SDK, on either side of the app."
step "Advertising ID → Does your app use advertising ID? → No."
note "  Nothing in the app reads it, and no SDK it carries (PostHog, Sentry,"
note "  RevenueCat, Expo) adds com.google.android.gms.permission.AD_ID. If Play"
note "  flags AD_ID in an uploaded bundle anyway, something merged it in: remove it"
note "  with tools:node=\"remove\" rather than change this answer."
step "Government apps → No. Mibo is not developed by or for a government."
step "Financial features → My app doesn't provide any financial features."
note "  Allowance is a ledger of coins a parent pays out by hand: no money moves"
note "  through the app, nothing is lent, held, transferred or invested. Say so if"
note "  asked. The subscription is a Play purchase, not a financial feature."
step "Health apps → My app doesn't provide any health features."
step "News apps → No.   COVID-19 apps → not a contact tracing or status app."
say ""
warn "Photo and video permissions or Foreground service permissions should not be"
warn "listed: the camera needs no declaration and the bundle asks for neither"
warn "READ_MEDIA_* nor a foreground service. If Play lists one, stop — a dependency"
warn "merged the permission in, and the fix is the manifest, not a declaration."
pause "Press Enter once each of these sections is saved."

# ── 11 ──────────────────────────────────────────────────────────────────
stage "App content — Content rating (IARC)"
say "Content rating → Start new questionnaire. The answers match the iOS age rating"
say "(scripts/setup-store-listing.sh, 4+): the same app, so the same facts."
say ""
step "Email address for IARC correspondence:"
copy "IARC email" "$CONTACT_EMAIL"
step "Category: All other app types — not Game, not Social or communication."
note "  The pet and the grove are rewards inside a chores tool, not a game."
say ""
step "Violence, sexuality, language, controlled substances, crude humor, gambling"
step "and simulated gambling: No to every question."
step "Users interact or exchange content (voice, text, images, audio): No."
note "  Google's test is whether users can freely exchange content they made. A"
note "  child's Photo Proof goes only to a parent of the same household, through a"
note "  five-minute link (ADR-0017); there is no chat, no feed and no way to reach"
note "  anyone outside the family. iOS answered the same question the same way."
step "Shares the user's current physical location with other users: No."
step "Digital purchases: Yes — the premium subscription, in parent mode only."
step "Web browser or search engine: No.   News or educational product: No."
say ""
step "Summary: expect ESRB Everyone, PEGI 3, USK 0 and IARC 3+, with the"
step "interactive element In-App Purchases. Anything higher means one descriptor"
step "was answered wrong — go back rather than accept it for a chores app."
step "Submit → Apply rating."
pause "Press Enter once the rating is applied."

# ── 12 ──────────────────────────────────────────────────────────────────
stage "App content — Target audience and content"
say "ADR-0018, Google Play: any age group under 13 puts the app under the Families"
say "policy, whose SDK rules PostHog and Sentry fail. Mibo is for the parent."
say ""
step "Target age: tick Ages 18 and over ONLY. Every other box stays empty."
note "  The child uses a device a parent joins with a Join Code; the person who"
note "  finds, installs, sets up and pays for Mibo is the parent."
step "Restrict Minor Access: leave it OFF."
note "  A kid device is often a supervised child account. Restricting minors would"
note "  stop the parent installing Mibo on it, and there is no other way to join."
say ""
step "Could your store listing unintentionally appeal to children? → No."
step "If Play asks for a reason:"
copy "Appeal answer" "Mibo is a chores and allowance app for parents. The parent installs it, creates the household, sets the chores, approves them and pays the allowance. The store listing is written to the parent and its first screenshots show the parent side: approvals, setting chores and the allowance. A child uses it only on a device the parent sets up with a code."
note "  The listing leads with the Parent side for exactly this question (the screenshots,"
note "  docs/store/listing.md). If Play objects to 'for Kids' in the title, ADR-0018's"
note "  prepared fallback is 'Mibo: Chores Tracker' — a title edit, not a form answer."
step "Ads (on this form): No.   Store presence: nothing to opt into → Save."
say ""
warn "If Play rejects this, or forces the Families policy, STOP. That is ADR-0018's"
warn "'to revisit' — a new decision about the SDKs, not a form to answer differently."
audience_reply=""
printf '  %s? Saved with 18 and over only? [y = saved / n = Play pushed back / Enter = not yet]%s ' \
  "$YELLOW" "$RESET"
read -r audience_reply || true
case "$audience_reply" in
  [Yy]*) ;;
  [Nn]*)
    SKIPPED+=("Target audience: Play pushed back on 18+ — reopen ADR-0018, do not change the form")
    finish
    exit 1 ;;
  *) SKIPPED+=("Target audience: save it with Ages 18 and over only") ;;
esac

# ── 13 ──────────────────────────────────────────────────────────────────
stage "App content — Data safety: collection, security and deletion"
say "Data safety → Start. The answers are the iOS App Privacy answers"
say "(scripts/setup-store-listing.sh, stages 6–10) in Play's words, and both follow"
say "apps/api/src/privacy.ts — a form that says what the policy does not is the"
say "inconsistency a reviewer finds first."
open_url_chrome "$PLAY_CONSOLE"
say ""
step "Does your app collect or share any of the required user data types? → Yes."
step "Is all of the user data collected by your app encrypted in transit? → Yes."
note "  Every request is HTTPS: the API, Clerk, R2 uploads, PostHog, Sentry,"
note "  RevenueCat and Expo push."
step "Account creation methods: OAuth (Sign in with Google) and Username and other"
step "authentication (email with a one-time code). Not Username and password."
note "  Only a parent creates an account; a child has none (ADR-0001)."
step "Delete account URL:"
copy "Delete account URL" "$DELETE_ACCOUNT_URL"
note "  Names the app and developer, gives the in-app steps (More → Delete my"
note "  account) and a request path for anyone without the app (#115, ADR-0019)."
step "Do you provide a way for users to request that their data is deleted? → Yes."
note "  In the app and at the same URL. Photo Proof also deletes itself after 30 days."
step "Independent security review: No."
pause "Press Enter, then the data types."

# ── 14 ──────────────────────────────────────────────────────────────────
stage "App content — Data safety: data types and usage"
say "Tick exactly these types and no others, then answer each one as shown."
say ""
ds_decl "Personal info → Name" "Required" "App functionality, Account management"
note "      The parent's name from their sign-in provider; a child's first name a"
note "      parent typed. A child gives us no name themselves."
ds_decl "Personal info → Email address" "Required" "App functionality, Account management"
note "      The parent's address from Clerk, and a partner-invite address."
ds_decl "Personal info → User IDs" "Required" "App functionality, Analytics, Account management"
note "      The parent's Clerk account id, also their id in PostHog and Sentry."
ds_decl "Financial info → Purchase history" "Optional" "App functionality"
note "      RevenueCat's subscription status for the household (ADR-0016). Optional:"
note "      only a parent who subscribes has one. Not User payment info — Google takes"
note "      the payment and no card detail reaches us."
ds_decl "Photos and videos → Photos" "Optional" "App functionality"
note "      Photo Proof, only when a chore asks for it: a private R2 bucket, a"
note "      five-minute link for a parent of the same household, gone after 30"
note "      days (ADR-0017)."
ds_decl "App activity → App interactions" "Required" "Analytics"
note "      PostHog events: the parent by account id, a Kid Device anonymously by a"
note "      random per-device id (ADR-0009). Autocapture and replay are off."
note "      Also covers iOS's Other Usage Data, which Play has no type for: the"
note "      interface mode, age band, hashed household id, platform and language"
note "      that ride on those events."
ds_decl "App activity → Other user-generated content" "Required" "App functionality"
note "      Chore and reward titles, the pet's name, completions, the coin ledger,"
note "      redemptions and the grove."
ds_decl "App info and performance → Crash logs" "Required" "App functionality"
note "      Sentry, rebuilt from an allowlist; a native crash is sent by Sentry's own"
note "      code first and carries a stack trace and device details (ADR-0015)."
ds_decl "Device or other IDs" "Required" "App functionality, Analytics"
note "      Expo push tokens, the hashed kid-device token and the per-device"
note "      analytics id issued when a Join Code is redeemed (ADR-0009)."
say ""
note "Not ticked, and why: Location, Contacts, Messages, Audio, Files, Calendar,"
note "Health, Web browsing, In-app search history, Installed apps — never collected."
note "Diagnostics and Other app performance data — tracing and profiling are off;"
note "the crash report is the only thing Sentry gets."
say ""
step "Preview: every type reads Collected, nothing under Data shared, and the"
step "badges read Data is encrypted in transit and You can request that data be"
step "deleted. Then Submit."
warn "Saved is not submitted: the section shows complete only after Submit."
pause "Press Enter once Data safety is submitted."

if (( ! APP_CONTENT_ONLY )); then
# ── 15 ──────────────────────────────────────────────────────────────────
stage "Internal testing — tester list and the first release"
say "Test and release → Testing → Internal testing."
open_url_chrome "$PLAY_CONSOLE"
say ""
step "Testers tab → Create email list, e.g. 'Mibo internal'."
note "  Each address must be a Google account. Include the parents testing the"
note "  household and the demo account from #100 — M6's exit criterion is an internal"
note "  release on Play with the same account App Review gets."
ask PLAY_TESTERS "Tester emails, comma-separated (counted for the report, never posted):"
if [[ -n "${PLAY_TESTERS:-}" ]]; then
  TESTER_COUNT=$(printf '%s' "$PLAY_TESTERS" | tr ',' '\n' | grep -c '@' || true)
fi
note "  $TESTER_COUNT address(es) for the list."
step "Save the list and tick it for this track."
say ""
step "Build the Android App Bundle (EAS keeps the versionCode remotely):"
note "    cd apps/mobile && eas build --platform android --profile production"
note "  The production profile builds an .aab. Download it from the EAS build page."
say ""
step "Releases tab → Create new release."
note "  Accept Play App Signing when offered — it is the default, cannot be undone,"
note "  and is what lets a lost upload key be replaced."
step "Upload the .aab. Play binds the package on this first upload: $PACKAGE"
warn "The first upload has to go through the Console; eas submit cannot make it."
step "Release name: Play fills it from the version. Release notes, en-US:"
copy "Release notes" "First internal build of Mibo."
step "Next → Save → Start rollout to Internal testing."
say ""
step "Testers tab → copy the opt-in link and send it to the list."
note "  Each tester opens it once, accepts, then installs from Play."
warn "A personal developer account made after November 2023 must also run a closed"
warn "test with 12 testers for 14 days before it gets production access. Internal"
warn "testing does not count toward it — check the Dashboard before planning launch."
pause "Press Enter once the release is rolled out to internal testing."
fi

# ── 16 ──────────────────────────────────────────────────────────────────
stage "Verify every section this run covers"
say "One pass over the record. Answer honestly — the point is the list of what is"
say "still missing, not a clean sheet."
say ""
if (( ! APP_CONTENT_ONLY )); then
check "App details" "Mibo exists in Play Console as a free app, default language en-US."
check "English listing" "The main store listing shows '$PLAY_TITLE' and the short and full descriptions from docs/store/listing.md."
check "Hebrew listing" "An iw-IL translation holds the Hebrew short and full descriptions, and its preview reads right to left."
check "Graphics" "A 512 x 512 icon and a 1024 x 500 feature graphic are uploaded."
check "Phone screenshots" "Two to eight phone screenshots on the default listing."
check "Tablet screenshots" "Two to eight 7-inch and 10-inch tablet screenshots on the default listing."
check "Category and tags" "The app category is Parenting (or the recorded fallback) and tags are chosen."
check "Contact details" "Email ${CONTACT_EMAIL:-(none)} and website $WEBSITE_URL are saved, and the privacy policy URL is $PRIVACY_URL."
check "Internal testing" "A release of $PACKAGE is rolled out to Internal testing to a list of $TESTER_COUNT address(es) that includes the #100 demo account."
check "Install" "A tester installed the build from the opt-in link and it opened."
fi
check "Privacy policy" "App content → Privacy policy is $PRIVACY_URL and shows complete."
check "App access" "Restricted, with the review account and the notes from docs/store/review-notes.md, after a fresh seed:review."
check "Ads and Advertising ID" "Contains ads: No. Uses advertising ID: No."
check "Declarations" "Government, Financial features, Health, News and COVID-19 are each answered 'none' and show complete."
check "Content rating" "IARC category All other app types; the applied rating is Everyone / PEGI 3 / USK 0 with In-App Purchases."
check "Target audience" "Ages 18 and over only, does not appeal to children, Restrict Minor Access off, and Play accepted it."
check "Data safety" "Nine data types, all collected and none shared, encrypted in transit, deletion at $DELETE_ACCOUNT_URL — submitted."
check "App content" "Every section on Policy and programs → App content shows complete."
pause

# ── 17 ──────────────────────────────────────────────────────────────────
stage "Report back to issue #$ISSUE"
say "Posting the section-by-section result as a comment."
if (( ${#RESULTS[@]} == 0 )); then
  warn "Nothing recorded — nothing to report."
  SKIPPED+=("the verification comment on issue #$ISSUE")
  finish
  exit 0
fi
# shellcheck disable=SC2016  # the backticks are Markdown for the issue comment
if (( APP_CONTENT_ONLY )); then
  comment=$(printf '## Play Console App content — verification\n\nRun via `scripts/setup-play-listing.sh --app-content` on %s.\n\n%s\n' \
    "$(date -u '+%Y-%m-%d %H:%M UTC')" "$(printf '%s\n' "${RESULTS[@]}")")
else
  comment=$(printf '## Play Console listing and App content — verification\n\nRun via `scripts/setup-play-listing.sh` on %s.\nInternal-testing list: **%s** address(es).\n\n%s\n' \
    "$(date -u '+%Y-%m-%d %H:%M UTC')" "$TESTER_COUNT" "$(printf '%s\n' "${RESULTS[@]}")")
fi
printf '\n%s\n\n' "$comment"
if confirm "Post this to issue #$ISSUE?"; then
  if printf '%s' "$comment" | gh issue comment "$ISSUE" --body-file - >/dev/null 2>&1; then
    printf '  %s✓ posted%s to issue #%s\n' "$GREEN" "$RESET" "$ISSUE"
  else
    warn "gh could not post — copy the comment above onto the issue by hand."
    SKIPPED+=("the verification comment on issue #$ISSUE")
  fi
else
  SKIPPED+=("the verification comment on issue #$ISSUE")
fi
pause

finish
