#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES — move the API and the public URLs onto the apex of mibokids.app.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

DOMAIN="${DOMAIN:-mibokids.app}"
NEW_BASE="https://$DOMAIN"
# Railway's generated hostname. It is not being retired: every build already in TestFlight has it
# compiled in via EXPO_PUBLIC_API_URL, and the RevenueCat webhook is configured against it.
RAILWAY_BASE="https://api-production-c5c7.up.railway.app"
# The api service itself. `railway variables --service api` confirms the port; the ids are stable
# for the life of the project and are what turns a four-click hunt into one link.
RAILWAY_PROJECT_ID="8fa437be-0083-4488-a53c-1ae0e5d9e6e3"
RAILWAY_SERVICE_ID="53d5f449-fb15-41e4-a2b4-0ce92122901b"
API_PORT="3000"
REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
EAS_JSON="$REPO_ROOT/apps/mobile/eas.json"
ISSUE=84

# Verification results, reported to issue #84 by the last stage.
RESULTS=()

# The library opens the default browser, which here is Arc. Railway, Cloudflare, App Store Connect
# and Google Cloud are all worked in Chrome, so try Chrome by name first and hand back to the
# library otherwise — a wrapper rather than a shadowing copy, matching the sibling wizards.
BROWSER_APP="${BROWSER_APP:-Google Chrome}"
open_url_chrome() {
  local url="$1"
  if [[ "$OSTYPE" == darwin* ]] && open -a "$BROWSER_APP" "$url" >/dev/null 2>&1; then
    printf '  %s↗ opening%s %s %s(%s)%s\n' "$GREEN" "$RESET" "$url" "$DIM" "$BROWSER_APP" "$RESET"
    return
  fi
  open_url "$url"
}

# fail "..." — a hard stop, in the library's red. Every exit in this wizard leaves the domain
# half-moved, so they should not read like notes.
fail() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }

# copy "what" "value" — put a value on the clipboard so it goes into a form character-for-character.
# A privacy URL typed by hand is a privacy URL with a typo App Review reads.
copy() {
  local label="$1" value="$2" tool=""
  if   command -v pbcopy   >/dev/null 2>&1; then tool="pbcopy"
  elif command -v wl-copy  >/dev/null 2>&1; then tool="wl-copy"
  elif command -v xclip    >/dev/null 2>&1; then tool="xclip -selection clipboard"
  elif command -v clip.exe >/dev/null 2>&1; then tool="clip.exe"
  fi
  printf '  %s%s%s\n' "$BOLD" "$value" "$RESET"
  if [[ -z "$tool" ]]; then
    note "  (no clipboard tool found — copy the line above by hand)"
    return
  fi
  if printf '%s' "$value" | $tool >/dev/null 2>&1; then
    printf '  %s✎ on the clipboard%s %s%s%s\n' "$GREEN" "$RESET" "$DIM" "$label" "$RESET"
  else
    note "  (clipboard write failed — copy the line above by hand)"
  fi
}

# check "label" "what must be true" — record a step as verified, failing or not yet done. Three
# answers rather than two: a step the human could not attempt yet must not be recorded as a
# failure, and abandoning the run is the only other way to avoid that (CODING_STANDARDS.md).
check() {
  local label="$1" expectation="$2" reply=""
  step "$expectation"
  printf '  %s? %s — is that true? [y/n/Enter = not yet]%s ' "$YELLOW" "$label" "$RESET"
  read -r reply || true
  case "$reply" in
    [Yy]*)
      RESULTS+=("- [x] $label — $expectation")
      printf '  %s✓ recorded as done%s\n' "$GREEN" "$RESET" ;;
    [Nn]*)
      RESULTS+=("- [ ] $label — FAILED: $expectation")
      printf '  %s✗ recorded as failing%s\n' "$RED" "$RESET" ;;
    *)
      RESULTS+=("- [ ] $label — not yet done: $expectation")
      printf '  %s· recorded as not yet done%s\n' "$DIM" "$RESET" ;;
  esac
}

# page_ok BASE PATH PATTERN — fetch a page whole and look for a string in it. Captured into a
# variable rather than piped into `grep -q`, because under `pipefail` a reader that stops early
# reports a healthy fetch as a failed one (CODING_STANDARDS.md).
page_ok() {
  local base="$1" path="$2" pattern="$3" body=""
  if ! body=$(curl -fsS --max-time 20 "$base$path"); then
    return 1
  fi
  grep -qi -- "$pattern" <<<"$body"
}

# The three pages a record we do not control links by absolute URL, and a string each one must
# contain. App Store Connect holds the second, Google's OAuth consent screen holds all three.
PUBLIC_PAGES=("/:Mibo" "/privacy:Privacy Policy" "/terms:Terms of Service")

# public_pages_ok BASE — check all three against one hostname. Returns failure if any is wrong, and
# prints a line per page either way. Called once before the cutover and once after.
public_pages_ok() {
  local base="$1" entry path needle ok=0
  for entry in "${PUBLIC_PAGES[@]}"; do
    path="${entry%%:*}"; needle="${entry#*:}"
    if page_ok "$base" "$path" "$needle"; then
      step "$base$path serves \"$needle\"."
    else
      fail "$base$path does not serve \"$needle\"."
      ok=1
    fi
  done
  return "$ok"
}

# ns_of DOMAIN — the domain's nameservers, one per line.
ns_of() { dig +short NS "$1" 2>/dev/null | sed 's/\.$//' | sort; }

banner "Move the API and the public URLs onto $DOMAIN"

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Preflight — is there anything worth pointing the domain at?"
say "The cutover publishes three URLs to records we do not control: App Review's"
say "privacy field and Google's OAuth consent screen. Pointing $DOMAIN at a"
say "deploy that 404s one of them is worse than leaving it on Railway's hostname."
say ""

for tool in dig curl jq; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    fail "$tool is not installed, and this wizard verifies the cutover with it."
    note "  macOS: brew install bind jq   Debian/Ubuntu: apt install dnsutils jq"
    exit 1
  fi
done
step "dig, curl and jq are present."

if grep -qi 'ns\.cloudflare\.com' <<<"$(ns_of "$DOMAIN")"; then
  step "$DOMAIN is on Cloudflare nameservers — DNS is ours to edit."
else
  fail "$DOMAIN is not on Cloudflare nameservers."
  note "  Register it first: scripts/buy-domain.sh"
  exit 1
fi

# The repo is the source of truth for which hostname the app calls. A wizard that cuts a domain
# over while the store profile still builds against Railway's name has moved nothing.
if [[ -f "$EAS_JSON" ]] && grep -q "$NEW_BASE" "$EAS_JSON"; then
  step "apps/mobile/eas.json already builds against $NEW_BASE."
else
  fail "apps/mobile/eas.json does not name $NEW_BASE."
  note "  The repo half of #$ISSUE has not landed. Nothing to cut over to."
  exit 1
fi

say ""
say "Checking Railway's hostname serves all three public pages at this commit."
if "$REPO_ROOT/scripts/check-deploy.sh" "$RAILWAY_BASE"; then
  step "the live API is HEAD."
else
  fail "the live API is not HEAD, so the pages this ticket added may not be there."
  note "  Deploy first: scripts/deploy-api.sh"
  exit 1
fi

if ! public_pages_ok "$RAILWAY_BASE"; then
  note "  Google's consent screen links all three. Fix them before moving the domain."
  exit 1
fi
say ""
note "Nothing so far has changed anything. The next stage does."
pause

# ── 2 ───────────────────────────────────────────────────────────────────
stage "Railway — add $DOMAIN as a custom domain on the api service"
say "Railway hands back two records, and both are required: a CNAME target and a"
say "TXT record that proves the domain is yours. Without the TXT, Railway never"
say "verifies the domain and the certificate is never issued."
# The api service directly. The workspace dashboard lands on Settings → Domains, which is
# Railway's own registrar — a different product with the same word on it, and the wrong page.
open_url_chrome "https://railway.com/project/$RAILWAY_PROJECT_ID/service/$RAILWAY_SERVICE_ID"
say ""
step "Settings tab → Networking → Custom Domain → + Custom Domain."
step "Enter the apex, with no www and no api. prefix:"
copy "the hostname" "$DOMAIN"
step "Select a port: $API_PORT — the service's PORT variable, which is what the"
step "server binds to. Railway does not pre-fill it."
say ""
note "The apex rather than api.$DOMAIN: Google's consent screen needs /, /privacy"
note "and /terms to answer at $DOMAIN as entered, so the apex has to serve them"
note "either way, and the store's privacy and support fields read better without"
note "an api. in front. Cloudflare flattens the CNAME at the apex, so this works."
say ""
ask CNAME_TARGET "The CNAME value Railway shows (e.g. abc123.up.railway.app)"
ask TXT_NAME     "The TXT record Name Railway shows"
ask TXT_VALUE    "The TXT record Value Railway shows"
if [[ -z "$CNAME_TARGET" || -z "$TXT_NAME" || -z "$TXT_VALUE" ]]; then
  fail "All three are needed. Re-run once Railway has shown them."
  exit 1
fi
pause

# ── 3 ───────────────────────────────────────────────────────────────────
stage "Cloudflare DNS — the CNAME and the TXT"
say "Railway may offer to write these records for you — an 'Authorize DNS records'"
say "dialog naming Cloudflare. Take it: it creates exactly the two records below,"
say "with the right proxy status on each, and nothing else in the zone is touched."
say "Read its removal list first all the same — it should name only records"
say "identical to the ones it is adding, and never anything under clerk., accounts."
say "or clkmail., which are Clerk's and must survive."
say ""
say "If it does not offer, or you declined it, add them by hand:"
open_url_chrome "https://dash.cloudflare.com/?to=/:account/$DOMAIN/dns"
say ""
step "DNS → Records → Add record. First the CNAME:"
note "    Type          CNAME"
note "    Name          @"
note "    Target        $CNAME_TARGET"
note "    Proxy status  Proxied — the ORANGE cloud, on"
say ""
warn "Proxying must be ON for a Cloudflare-hosted domain on Railway. With it off,"
warn "Cloudflare does not associate the domain with the Railway service and the"
warn "hostname answers ERR_TOO_MANY_REDIRECTS. This is the opposite of the usual"
warn "advice, and it is Railway's own documented requirement."
say ""
note "Cloudflare rewrites Name '@' to '$DOMAIN' after saving — that is CNAME"
note "flattening doing its job, not a mistake."
say ""
step "Then the TXT record, exactly as Railway gave it:"
note "    Type   TXT"
note "    Name   $TXT_NAME"
note "    Value  $TXT_VALUE"
say ""
warn "Skip the TXT and everything else in this wizard looks fine until the"
warn "certificate silently never arrives."
pause "Press Enter once both records are saved."

# ── 4 ───────────────────────────────────────────────────────────────────
stage "Cloudflare SSL/TLS — Full, and not Full (Strict)"
say "Two settings, and one of them is a trap: Full (Strict) requires the origin"
say "certificate to match the hostname exactly, which fails inside Railway's own"
say "renewal window and returns a 526 to everyone, weeks after this wizard ran."
open_url_chrome "https://dash.cloudflare.com/?to=/:account/$DOMAIN/ssl-tls"
say ""
step "SSL/TLS → Overview → encryption mode: Full."
warn "Full. NOT Full (Strict)."
step "SSL/TLS → Edge Certificates → Universal SSL: enabled."
say ""
step "Back in Railway, the custom domain should now read 'Cloudflare proxy"
step "detected' with a green cloud, and then issue its certificate."
say ""
note "Railway has a 72-hour window to issue the certificate; in practice it is"
note "minutes. The next stage waits for it."
pause

# ── 5 ───────────────────────────────────────────────────────────────────
stage "Verify the new hostname is genuinely the same API"
say "A hostname that answers and a hostname that answers *this build* are"
say "different facts. Both are checked, plus the three public pages."
say ""
say "Polling $NEW_BASE/health."

# Generous, because the alternative — declaring success early — points App Review and Google at a
# hostname that does not resolve. Ctrl-C and re-run is always safe; nothing below is destructive.
deadline=$((SECONDS + 600))
live=0
while (( SECONDS < deadline )); do
  if curl -fsS --max-time 10 "$NEW_BASE/health" >/dev/null 2>&1; then live=1; break; fi
  printf '  %s· not answering yet, %ss left%s\r' "$DIM" "$((deadline - SECONDS))" "$RESET"
  sleep 15
done
printf '\033[2K'

if (( live )); then
  step "$NEW_BASE/health answers over TLS."
  if "$REPO_ROOT/scripts/check-deploy.sh" "$NEW_BASE"; then
    RESULTS+=("- [x] \`$NEW_BASE/health\` answers over a valid certificate and reports HEAD's commit")
  else
    RESULTS+=("- [ ] \`$NEW_BASE/health\` answers but does not report HEAD's commit")
    warn "It answers, but not with this commit. Something else is on that hostname."
  fi
  if public_pages_ok "$NEW_BASE"; then
    RESULTS+=("- [x] \`$NEW_BASE\` serves \`/\`, \`/privacy\` and \`/terms\`")
  else
    RESULTS+=("- [ ] \`$NEW_BASE\` does NOT serve all of \`/\`, \`/privacy\` and \`/terms\` — see the run above")
  fi
  if page_ok "$RAILWAY_BASE" "/health" 'ok'; then
    step "Railway's own hostname still answers — shipped builds keep working."
    RESULTS+=("- [x] the Railway hostname still answers, so TestFlight builds keep working")
  else
    fail "Railway's hostname stopped answering. Every build in TestFlight calls it."
    RESULTS+=("- [ ] the Railway hostname stopped answering — TestFlight builds are broken")
  fi
else
  warn "Nothing on $NEW_BASE after ten minutes."
  note "That is not necessarily wrong — check the domain's state in Railway."
  note "Then continue with: scripts/check-deploy.sh $NEW_BASE"
  RESULTS+=("- [ ] not yet done: $NEW_BASE did not answer within ten minutes")
  SKIPPED+=("verifying $NEW_BASE — scripts/check-deploy.sh $NEW_BASE")
fi
pause

# ── 6 ───────────────────────────────────────────────────────────────────
stage "App Store Connect — re-save the two public URLs"
say "Decided in #82: these move before 1.0 is submitted, because changing a"
say "privacy URL after App Review has read it is worse than changing it now."
open_url_chrome "https://appstoreconnect.apple.com/apps"
say ""
step "Mibo → App Privacy → Privacy Policy → Edit. Replace the URL with:"
copy "the privacy URL" "$NEW_BASE/privacy"
step "Save."
say ""
step "Then the left sidebar → iOS App → 1.0 Prepare for Submission. Scroll past"
step "Promotional Text, Description and Keywords; Support URL is the field under"
step "Keywords, beside Marketing URL. Not the App Review page — that is where you"
step "submit, and it has no such field."
copy "the support URL" "$NEW_BASE"
step "Save."
say ""
note "The Railway URL is not removed anywhere — it is replaced in these two fields"
note "only, and the hostname itself keeps answering."
say ""
check "Privacy Policy URL" "App Store Connect's Privacy Policy URL is $NEW_BASE/privacy."
check "Support URL" "The 1.0 version's Support URL is $NEW_BASE."
pause

# ── 7 ───────────────────────────────────────────────────────────────────
stage "Google's OAuth consent screen — as a parent sees it"
say "Three links on the consent screen were entered as $DOMAIN URLs to get the"
say "OAuth app published, because up.railway.app is a public suffix and Google"
say "will not accept a link on a domain nobody can prove they own. Two of the"
say "three were 404 until this wizard ran."
open_url_chrome "https://console.cloud.google.com/auth/branding"
say ""
step "Check Authorised domains still lists $DOMAIN, and that the three links are:"
note "    Application home page            $NEW_BASE"
note "    Application privacy policy link  $NEW_BASE/privacy"
note "    Application Terms of Service     $NEW_BASE/terms"
say ""
warn "Curling those three proves nothing about the consent screen — it renders"
warn "whatever was saved in this form, which is the thing being checked."
say ""
step "So open the consent screen itself. The cheapest way needs no build — Clerk's"
step "own account portal runs the same production instance and the same Google"
step "OAuth client, so it shows the same screen:"
note "    https://accounts.$DOMAIN/sign-in  →  Continue with Google"
step "Tap each of the three links at the bottom of the screen."
say ""
warn "A development build cannot do this check. It carries the pk_test_ key, whose"
warn "sign-in goes through Clerk's development instance — which uses Clerk's own"
warn "shared Google credentials and shows Clerk's consent screen, not ours. It also"
warn "401s against the live API, whose CLERK_SECRET_KEY is sk_live_."
say ""
note "Google skips the consent screen for an account that has already granted"
note "access. Use an account that has not, or revoke Mibo first at"
note "https://myaccount.google.com/permissions"
say ""
check "Consent screen links" \
  "All three links on Google's consent screen open a real page, checked by tapping them."
pause

# ── 8 ───────────────────────────────────────────────────────────────────
stage "What not to undo, and report back to issue #$ISSUE"
say "Two things are deliberately left pointing at Railway's hostname."
say ""
step "1. The custom domain in Railway stays. Do not remove it. Every build already"
step "   in TestFlight has $RAILWAY_BASE compiled in"
step "   via EXPO_PUBLIC_API_URL and cannot be changed without a new build."
say ""
step "2. The RevenueCat webhook may keep its Railway URL. It is the only writer of"
step "   an entitlement (ADR-0016), it works, and both hostnames answer — so there"
step "   is nothing to gain today by touching it, and a typo in that one field is"
step "   a premium purchase that never lands. scripts/setup-premium.sh now names"
step "   $NEW_BASE, so a fresh setup or a deliberate re-point goes to the new"
step "   hostname; an existing webhook on Railway's name is equally correct."
say ""
if (( ${#RESULTS[@]} == 0 )); then
  warn "Nothing recorded — nothing to report."
  SKIPPED+=("the verification comment on issue #$ISSUE")
  finish
  exit 0
fi
# shellcheck disable=SC2016  # the backticks are Markdown for the issue comment
comment=$(printf '## Domain cutover to %s — verification\n\nRun via `scripts/setup-domain.sh` on %s.\nAPI base is now `%s`; `%s` is kept for builds already shipped.\n\n%s\n' \
  "$DOMAIN" "$(date -u '+%Y-%m-%d %H:%M UTC')" "$NEW_BASE" "$RAILWAY_BASE" \
  "$(printf '%s\n' "${RESULTS[@]}")")
printf '\n%s\n\n' "$comment"
if confirm "Post this to issue #$ISSUE?"; then
  if printf '%s' "$comment" | gh issue comment "$ISSUE" --body-file - >/dev/null 2>&1; then
    printf '  %s✓ posted%s to issue #%s\n' "$GREEN" "$RESET" "$ISSUE"
  else
    warn "gh could not post — copy the comment above onto the issue by hand."
    SKIPPED+=("the verification comment on issue #$ISSUE")
  fi
else
  SKIPPED+=("the verification comment on issue #$ISSUE")
fi
pause

finish
note "The API is $NEW_BASE. The 1.0 build and submission are #83."
printf '\n'
