#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
# The stages section below redefines this to prefer Chrome, which is why shellcheck
# sees this definition as uncalled. It is the fallback shape every wizard's override
# is written from; the disable is here, not file-wide, so a dead function among the
# authored stages still gets reported.
# shellcheck disable=SC2329
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES — M4.9 Sign in with Apple on the production Clerk instance (issue #85).
#
# Two halves, and each is invisible from where the other is configured. Apple's
# side wants an App ID capability, a Services ID and a one-download private key;
# Clerk's production instance wants those three values typed into it. Neither
# dashboard can tell you the app is missing the `usesAppleSignIn` entitlement,
# and the entitlement alone signs nobody in.
#
# Guideline 4.8 is why this is a submission blocker: the app offers Google, so it
# must also offer a sign-in that collects only name and email and lets the user
# keep the address private. Sign in with Apple is the only such option here.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=13

# open_url override — the library opens the default browser, which here is Arc.
# These dashboards are worked in Chrome, so target it by name and fall back to
# the library's behaviour if it is not installed.
BROWSER_APP="${BROWSER_APP:-Google Chrome}"
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s %s(%s)%s\n' "$GREEN" "$RESET" "$url" "$DIM" "$BROWSER_APP" "$RESET"
  if [[ "$OSTYPE" == darwin* ]] && open -a "$BROWSER_APP" "$url" >/dev/null 2>&1; then
    return
  fi
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser - visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser - visit it manually: $url"
}

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
MOBILE="$REPO_ROOT/apps/mobile"
BUNDLE_ID="com.mibokids.app"
# The production instance, named literally. Every clerk call below passes it: the
# CLI otherwise picks an instance for you, and this ticket exists partly because
# scripts/clerk-setup.sh did that and reconfigured development three times while
# production's redirect allowlist sat empty behind a store build.
PROD_INSTANCE="ins_3Ju3HWvao1YJ00AczgcGiG8Q9aI"
ACCOUNT_PORTAL="https://accounts.mibokids.app/sign-in"
# The app's own redirect, built by makeRedirectUri({ scheme: 'mibo', path: 'sso-callback' })
# in src/components/parent-sign-in.tsx. The other two are historical and harmless.
REDIRECT_URLS=("mibo://sso-callback" "mibo://parent" "mibo://")
ISSUE=85

# The banner promises this wizard remembers values across re-runs, and `ask` delivers
# that by reading ENV_FILE — so it needs somewhere to write. Not an app's .env: none of
# these identifiers is read by any workspace. `.env.*` is already gitignored, which is
# what keeps this scratchpad out of the repo. The .p8 never comes near it: its contents
# go from the file Apple served straight into the Clerk dashboard, and `*.p8` is
# gitignored too.
ENV_FILE="$REPO_ROOT/.env.apple-signin"

RESULTS=()

# clerk_cli — the Clerk CLI, installed globally if present, else via npx.
clerk_cli() {
  if command -v clerk >/dev/null 2>&1; then clerk "$@"; else npx -y clerk@latest "$@"; fi
}

# prod_config FILE — write the production instance's config to FILE. Returns
# non-zero when it could not be read, so callers fall back to asking the human
# rather than reporting "not configured" from an empty file.
prod_config() {
  clerk_cli config pull --instance "$PROD_INSTANCE" > "$1" 2>/dev/null
}

# apple_field FILE KEY — echo connection_oauth_apple.KEY from a pulled config,
# or nothing. Named keys only: a grep for "apple" also matches Clerk's list of
# every *available* provider, which says nothing about what is enabled.
apple_field() {
  python3 -c 'import json,sys
c = json.load(open(sys.argv[1]))
print((c.get("connection_oauth_apple") or {}).get(sys.argv[2]) or "")' "$1" "$2" 2>/dev/null || true
}

# check "label" "what the tester should see" — record a pass/fail for the issue comment.
check() {
  local label="$1" expectation="$2" reply=""
  step "$expectation"
  printf '  %s? %s — did that happen? [y/n/Enter = not yet]%s ' "$YELLOW" "$label" "$RESET"
  read -r reply || true
  case "$reply" in
    [Yy]*)
      RESULTS+=("- [x] $label — $expectation")
      printf '  %s✓ recorded as passing%s\n' "$GREEN" "$RESET" ;;
    [Nn]*)
      RESULTS+=("- [ ] $label — FAILED: $expectation")
      printf '  %s✗ recorded as failing%s\n' "$RED" "$RESET" ;;
    *)
      RESULTS+=("- [ ] $label — not yet run: $expectation")
      printf '  %s· recorded as not yet run%s\n' "$DIM" "$RESET" ;;
  esac
}

banner "Mibo — Sign in with Apple on the production Clerk instance"

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools the later stages shell out to."
missing=0
for tool in python3 npx; do
  if command -v "$tool" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$tool"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$tool"
    missing=1
  fi
done
if command -v clerk >/dev/null 2>&1; then
  printf '  %s✓%s clerk (%s)\n' "$GREEN" "$RESET" "$(clerk -v 2>/dev/null || echo installed)"
else
  warn "clerk CLI not installed globally — every clerk step runs through npx (slower)."
  say "Install it once for a faster run:  brew install clerk/stable/clerk"
fi
if command -v gh >/dev/null 2>&1; then
  printf '  %s✓%s gh (stage 13 posts the results to issue #%s)\n' "$GREEN" "$RESET" "$ISSUE"
else
  printf '  %s✗%s gh\n' "$RED" "$RESET"
  SKIPPED+=("the hand-test comment on issue #$ISSUE (gh missing)")
fi
(( missing )) && { warn "Install the missing tools before continuing."; confirm "Continue anyway?" || exit 1; }
say ""
say "Signing in to Clerk. A browser tab will open — approve it there."
if clerk_cli whoami >/dev/null 2>&1; then
  note "already signed in"
else
  clerk_cli auth login || warn "clerk auth login failed — the verify stages will not be able to read anything."
fi
say ""
note "every Clerk call in this wizard passes --instance $PROD_INSTANCE"
note "that is production. Nothing here touches the development instance."
if linked=$(clerk_cli whoami 2>/dev/null); then
  if printf '%s' "$linked" | grep -qF "$PROD_INSTANCE"; then
    printf '  %s✓%s that is the production instance of the linked application\n' "$GREEN" "$RESET"
  else
    warn "the linked application does not report $PROD_INSTANCE as its production instance."
    warn "Either the wrong application is linked, or the id in this script has gone stale."
    confirm "Continue anyway?" || exit 1
  fi
fi
pause "Press Enter when the tooling looks right."

# ── 2 ───────────────────────────────────────────────────────────────────
stage "The entitlement in app.json"
say "This is the half no dashboard can report on. Without it the built app has no"
say "com.apple.developer.applesignin entitlement, and startSSOFlow({ strategy:"
say "'oauth_apple' }) cannot complete on a device however right Clerk is."
say ""
if grep -q '"usesAppleSignIn": *true' "$MOBILE/app.json"; then
  printf '  %s✓%s app.json sets ios.usesAppleSignIn\n' "$GREEN" "$RESET"
else
  warn "app.json does not set ios.usesAppleSignIn — add it under \"ios\":"
  say '      "usesAppleSignIn": true'
  SKIPPED+=("add \"usesAppleSignIn\": true under ios in apps/mobile/app.json")
fi
say ""
say "Proving the resolved config actually carries the entitlement, rather than"
say "trusting that the key was spelt right:"
ENTITLED=""
if entitlements=$(cd "$MOBILE" && npx expo config --type introspect 2>/dev/null); then
  if printf '%s' "$entitlements" | grep -q 'com.apple.developer.applesignin'; then
    printf '  %s✓%s expo config introspect shows com.apple.developer.applesignin\n' "$GREEN" "$RESET"
    ENTITLED=yes
  else
    warn "the introspected config has no applesignin entitlement."
    SKIPPED+=("get com.apple.developer.applesignin into the introspected expo config")
  fi
else
  warn "couldn't run 'npx expo config --type introspect' — check it by hand."
fi
say ""
warn "This is a native change. It ships in a new build, never as an OTA update:"
warn "an entitlement lives in the signed binary, and expo-updates replaces only JS."
pause

# ── 3 ───────────────────────────────────────────────────────────────────
stage "Apple — the App ID capability"
say "Sign in with Apple has to be switched on for the App ID itself before any"
say "Services ID can reference it."
open_url "https://developer.apple.com/account/resources/identifiers/list/bundleId"
step "Open the App ID for $BUNDLE_ID."
step "Under Capabilities, tick Sign in with Apple, then Save."
step "Leave it as 'Enable as a primary App ID' — Mibo has no app group to join."
note "Saving a capability re-issues the provisioning profile. EAS fetches a fresh"
note "one per build, so there is nothing to download by hand here."
pause "Press Enter once the capability is enabled and saved."

# ── 4 ───────────────────────────────────────────────────────────────────
stage "Apple — the Services ID"
say "The Services ID is the OAuth client id Clerk presents to Apple. It is a"
say "separate identifier from the App ID and must not reuse its string."
open_url "https://developer.apple.com/account/resources/identifiers/list/serviceId"
step "+ → Services IDs → Continue."
step "Description: Mibo Sign in with Apple"
step "Identifier: something distinct from the bundle id, e.g. $BUNDLE_ID.signin"
step "Register it, then reopen it — the configuration only appears after it exists."
say ""
ask APPLE_SERVICES_ID "The Services ID you registered:"
APPLE_SERVICES_ID="${APPLE_SERVICES_ID//[[:space:]]/}"
if [[ "$APPLE_SERVICES_ID" == "$BUNDLE_ID" ]]; then
  warn "That is the bundle id. Apple rejects a Services ID that collides with the App ID."
  SKIPPED+=("register a Services ID distinct from $BUNDLE_ID")
fi
[[ -n "$APPLE_SERVICES_ID" ]] && write_env APPLE_SERVICES_ID "$APPLE_SERVICES_ID"
note "Leave this page open — stage 6 comes back to register a return URL on it."
pause

# ── 5 ───────────────────────────────────────────────────────────────────
stage "Clerk — the exact return URL"
say "Clerk generates the return URL. Read it off the page; do not build it from"
say "the domain by hand."
open_url "https://dashboard.clerk.com"
step "Pick the Mibo application, then switch the instance selector to Production."
step "Configure → SSO connections → Add connection → For all users → Apple."
step "Turn on 'Use custom credentials'. Clerk then shows an 'Authorized redirect URI'"
step "  (some layouts call it Return URL). Copy it exactly, including the scheme."
say ""
warn "Do NOT enable or save the connection yet — stage 8 fills the credentials. An"
warn "enabled connection with empty credentials is a live Apple button on production"
warn "that cannot complete, and it fails for a real parent, not for you."
say ""
warn "Copy, never retype. Today's Google connection was dead for an hour because a"
warn "client id had picked up an 'http://' prefix on the way in — a typo of that"
warn "class is invisible on the dashboard and only shows up as a user's failure."
say ""
ask APPLE_RETURN_URL "Paste Clerk's return URL:"
APPLE_RETURN_URL="${APPLE_RETURN_URL//[[:space:]]/}"
if [[ "$APPLE_RETURN_URL" != https://* ]]; then
  warn "Apple accepts https:// return URLs only — that value will be rejected."
  SKIPPED+=("take the https:// return URL from Clerk's Apple connection page")
fi
[[ -n "$APPLE_RETURN_URL" ]] && write_env APPLE_RETURN_URL "$APPLE_RETURN_URL"
pause

# ── 6 ───────────────────────────────────────────────────────────────────
stage "Apple — register the return URL on the Services ID"
say "Apple matches the return URL literally. One character off and the callback"
say "fails after the parent has already approved, which reads like a Clerk fault."
open_url "https://developer.apple.com/account/resources/identifiers/list/serviceId"
step "Open ${APPLE_SERVICES_ID:-the Services ID} → Configure next to Sign in with Apple."
step "Primary App ID: $BUNDLE_ID"
step "Under Website URLs, Domains and Subdomains: the host of the URL below."
step "Under Return URLs, paste it whole:"
printf '      %s%s%s\n' "$BOLD" "${APPLE_RETURN_URL:-<the URL from stage 5>}" "$RESET"
step "Next → Done → Continue → Save."
note "Apple will not accept a bare domain in Return URLs, nor a path in Domains."
pause "Press Enter once the return URL is saved on the Services ID."

# ── 7 ───────────────────────────────────────────────────────────────────
stage "Apple — the Sign in with Apple key"
warn "READ THIS BEFORE YOU CLICK DOWNLOAD."
say ""
say "The .p8 private key is served exactly once. Apple keeps the public half and"
say "will not show you the file again — a lost key means revoking it and creating"
say "another, which breaks every sign-in issued against the old one."
say ""
step "Put it somewhere you will still have it next year, not ~/Downloads."
step "It is a secret: never commit it, and never paste it into a shell command"
step "  (it would land in your shell history)."
say ""
pause "Press Enter when you have somewhere to put it."
open_url "https://developer.apple.com/account/resources/authkeys/list"
step "+ → Key Name: Mibo Sign in with Apple"
step "Tick Sign in with Apple, then Configure → Primary App ID: $BUNDLE_ID → Save."
step "Continue → Register → Download. Keep the AuthKey_XXXXXXXXXX.p8 file."
say ""
ask APPLE_KEY_ID "The Key ID Apple shows (10 characters):"
APPLE_KEY_ID="${APPLE_KEY_ID//[[:space:]]/}"
say ""
step "Your Team ID is top right of the Apple Developer page, and on Membership details."
ask APPLE_TEAM_ID "Your Apple Team ID (10 characters):"
APPLE_TEAM_ID="${APPLE_TEAM_ID//[[:space:]]/}"
for pair in "APPLE_KEY_ID:$APPLE_KEY_ID" "APPLE_TEAM_ID:$APPLE_TEAM_ID"; do
  name="${pair%%:*}"; value="${pair#*:}"
  if [[ -n "$value" && ${#value} -ne 10 ]]; then
    warn "$name is ${#value} characters; Apple's are 10. Check it before stage 8."
  fi
done
[[ -n "$APPLE_KEY_ID" ]] && write_env APPLE_KEY_ID "$APPLE_KEY_ID"
[[ -n "$APPLE_TEAM_ID" ]] && write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"
pause

# ── 8 ───────────────────────────────────────────────────────────────────
stage "Clerk — the custom credentials"
say "Back to the Apple connection on the PRODUCTION instance. Development uses"
say "Clerk's shared credentials; production has none and must be told all four."
open_url "https://dashboard.clerk.com"
step "Production instance → Configure → SSO connections → Apple."
step "Apple Services ID / Client ID:  ${APPLE_SERVICES_ID:-<from stage 4>}"
step "Apple Team ID:                  ${APPLE_TEAM_ID:-<from stage 7>}"
step "Apple Key ID:                   ${APPLE_KEY_ID:-<from stage 7>}"
step "Apple Private Key: open the .p8 in a text editor and paste its whole"
step "  contents, BEGIN/END lines included."
step "App Bundle ID: $BUNDLE_ID"
note "The bundle id field is for Apple's native sign-in sheet. Mibo signs in through"
note "the browser flow, so it is not load-bearing today — fill it anyway, so a later"
note "move to the native sheet is a client change and not another trip through Apple."
step "Enable the connection and Save."
say ""
warn "Check each field for a stray 'http://', a trailing space, or a smart quote"
warn "that a copy out of a PDF brings with it. Stage 9 reads them back."
pause "Press Enter once the connection is saved and enabled."

# ── 9 ───────────────────────────────────────────────────────────────────
stage "Verify — the connection, read back from Clerk"
say "Reading connection_oauth_apple off the production instance."
CFG="$(mktemp)"
trap 'rm -f "$CFG"' EXIT
CONNECTION_OK=""
if prod_config "$CFG"; then
  apple_enabled=$(apple_field "$CFG" enabled)
  apple_client=$(apple_field "$CFG" client_id)
  apple_team=$(apple_field "$CFG" team_id)
  apple_key=$(apple_field "$CFG" key_id)
  apple_bundle=$(apple_field "$CFG" bundle_id)
  if [[ "$apple_enabled" == True ]]; then
    printf '  %s✓%s enabled\n' "$GREEN" "$RESET"
  else
    printf '  %s✗%s not enabled\n' "$RED" "$RESET"
  fi
  for pair in "client_id (Services ID):$apple_client" "team_id:$apple_team" \
              "key_id:$apple_key" "bundle_id:$apple_bundle"; do
    label="${pair%%:*}"; value="${pair#*:}"
    if [[ -z "$value" ]]; then
      printf '  %s✗%s %s is empty\n' "$RED" "$RESET" "$label"
    else
      printf '  %s✓%s %s = %s\n' "$GREEN" "$RESET" "$label" "$value"
    fi
  done
  case "$apple_client$apple_team$apple_key" in
    *http*) warn "one of those values contains 'http' — that is the typo that broke Google." ;;
    *) : ;;
  esac
  if [[ "$apple_enabled" == True && -n "$apple_client" && -n "$apple_team" && -n "$apple_key" ]]; then
    CONNECTION_OK=yes
  else
    SKIPPED+=("finish the Apple SSO connection on the production Clerk instance")
  fi
else
  warn "couldn't pull the production config — verify the connection on the dashboard."
  SKIPPED+=("verify connection_oauth_apple on the production instance by hand")
fi
note "client_secret is the .p8 and is never echoed here."
pause

# ── 10 ──────────────────────────────────────────────────────────────────
stage "Verify — the production redirect allowlist"
say "Clerk checks the allowlist server-side when the flow starts, so a fix here"
say "reaches an already-shipped build with no rebuild. Production's allowlist was"
say "empty on the first store build, and every sign-in failed with 'the current"
say "redirect url does not match an authorised url'."
registered=$(clerk_cli api --instance "$PROD_INSTANCE" /redirect_urls 2>/dev/null || true)
if [[ -z "$registered" ]]; then
  warn "couldn't read the allowlist — check it on the dashboard."
  SKIPPED+=("verify the production redirect URL allowlist holds ${REDIRECT_URLS[*]}")
else
  for url in "${REDIRECT_URLS[@]}"; do
    if printf '%s' "$registered" | grep -qF "\"$url\""; then
      printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$url"
    elif clerk_cli api --instance "$PROD_INSTANCE" -X POST /redirect_urls \
        -d "{\"url\":\"$url\"}" --yes >/dev/null 2>&1; then
      printf '  %s✓ registered%s %s\n' "$GREEN" "$RESET" "$url"
    else
      printf '  %s✗%s %s — add it by hand\n' "$RED" "$RESET" "$url"
      SKIPPED+=("register $url as a production Clerk redirect URL")
    fi
  done
fi
note "mibo://sso-callback is the one the app asks for; the other two are historical."
pause

# ── 11 ──────────────────────────────────────────────────────────────────
stage "Verify — a real Apple ID through the Account Portal"
say "The portal exercises Clerk's side alone: no build, no entitlement, no device."
say "If it fails here, the app cannot work, and you know the fault is not the app."
open_url "$ACCOUNT_PORTAL"
step "Continue with Apple. Use a real Apple ID, and choose Hide My Email."
note "Hiding the address is the case worth testing, not the awkward one: parents.email"
note "is nullable exactly because a token may carry no email claim, and the app has to"
note "reach a parents row regardless."
check "portal sign-in" "Continue with Apple completes and the portal shows you signed in."
say ""
say "Confirming the Clerk user landed on the PRODUCTION instance:"
if users=$(clerk_cli api --instance "$PROD_INSTANCE" '/users?limit=5&order_by=-created_at' 2>/dev/null); then
  if printf '%s' "$users" | grep -q 'oauth_apple'; then
    printf '  %s✓%s a user with an oauth_apple account exists on production\n' "$GREEN" "$RESET"
  else
    warn "no oauth_apple account among the five newest Clerk users on production."
    SKIPPED+=("confirm the Apple sign-in created a user on the production instance")
  fi
else
  warn "couldn't list production users — check Users on the dashboard instead."
fi
pause

# ── 12 ──────────────────────────────────────────────────────────────────
stage "Verify — the app on a physical device"
warn "This needs a build made AFTER stage 2, signed against the profile Apple"
warn "re-issued in stage 3. A TestFlight build from scripts/release-ios.sh is one."
say ""
[[ -z "$ENTITLED" ]] && warn "stage 2 could not prove the entitlement — expect the Apple button to fail."
[[ -z "$CONNECTION_OK" ]] && warn "stage 9 could not confirm the connection — expect the Apple button to fail."
say ""
check "apple button signs in" "Parent sign-in → the Apple button completes and lands on the parent home."
check "hidden email resolves to a parent" "Signing in with Hide My Email still reaches create-household or an existing household — never an error screen."
check "google still works" "The Google button still signs in — 4.8 wants both social options live, not one."
pause

# ── 13 ──────────────────────────────────────────────────────────────────
stage "Report back to issue #$ISSUE"
if (( ${#RESULTS[@]} == 0 )); then
  warn "No hand-test results recorded — nothing to report."
  SKIPPED+=("the hand-test comment on issue #$ISSUE")
  finish
  exit 0
fi
# The backticks below are markdown for the GitHub comment, not command substitution;
# the single quotes are what keeps them literal.
# shellcheck disable=SC2016
comment=$(printf '## Sign in with Apple — production verification\n\nRun via `scripts/setup-apple-signin.sh` on %s, against instance `%s`.\n\n%s\n' \
  "$(date -u '+%Y-%m-%d %H:%M UTC')" "$PROD_INSTANCE" "$(printf '%s\n' "${RESULTS[@]}")")
printf '\n%s\n\n' "$comment"
if confirm "Post this to issue #$ISSUE?"; then
  if printf '%s' "$comment" | gh issue comment "$ISSUE" --body-file - >/dev/null 2>&1; then
    printf '  %s✓ posted%s to issue #%s\n' "$GREEN" "$RESET" "$ISSUE"
  else
    warn "gh could not post — copy the comment above onto the issue by hand."
    SKIPPED+=("the hand-test comment on issue #$ISSUE")
  fi
else
  SKIPPED+=("the hand-test comment on issue #$ISSUE")
fi
pause

finish
