#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — what pre-submission QA could not reach from a simulator.
#
# The dev-client pass of 2026-09-29 covered onboarding, the partner invite
# path and the kid's Today; its four findings landed in the commit after
# accb9b2. Everything below needs a store build on a real phone: the OS push
# prompt, a real camera, a night passing, the production Clerk instance and
# an Android device. The script only asks and records; a human with two
# phones does the rest.
#
# ISSUE=<n> in the environment posts the results to that GitHub issue at the
# end; without it the markdown is printed for pasting.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

ISSUE="${ISSUE:-}"
RESULTS=()
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# check "label" "what the tester should see" — record pass/fail for the
# report. Bare Enter is "not yet run" and lands in neither column.
check() {
  local label="$1" expectation="$2" reply=""
  step "$expectation"
  printf '  %s? %s — did that happen? [y/n/Enter = not yet]%s ' "$YELLOW" "$label" "$RESET"
  read -r reply || true
  case "$reply" in
    [Yy]*)
      RESULTS+=("- [x] $label — $expectation")
      printf '  %s✓ recorded as passing%s\n' "$GREEN" "$RESET" ;;
    [Nn]*)
      RESULTS+=("- [ ] $label — FAILED: $expectation")
      printf '  %s✗ recorded as failing%s\n' "$RED" "$RESET" ;;
    *)
      RESULTS+=("- [ ] $label — not yet run: $expectation")
      printf '  %s· recorded as not yet run%s\n' "$DIM" "$RESET" ;;
  esac
}

banner "Mibo — the hand-tests a simulator cannot run"

# ── 1 ───────────────────────────────────────────────────────────────────
stage "Before you start"
say "You need:"
step "an iPhone with the TestFlight build of Mibo, and an Android phone with"
say "  the internal-testing build — both against the LIVE API and the"
say "  PRODUCTION Clerk instance (the store builds already are)."
step "two real Apple IDs / Google accounts that can receive mail: parent A"
say "  and parent B. The production Clerk instance has no test inboxes."
step "a third phone, or one of the two, to be the Kid Device."
say ""
say "Checking the live API is the commit you think it is:"
if out=$("$REPO_ROOT/scripts/check-deploy.sh" 2>&1); then
  printf '%s\n' "$out" | sed 's/^/  /'
else
  warn "check-deploy.sh did not pass — the live API may be an older build."
  printf '%s\n' "$out" | sed 's/^/  /'
  SKIPPED+=("scripts/check-deploy.sh did not pass before the run")
fi
say ""
note "Results are recorded as you go; Ctrl-C loses the ones not yet posted."
pause "Ready?"

# ── 2 ───────────────────────────────────────────────────────────────────
stage "Language: saved, then whole on the next open"
say "Parent phone, signed in, More → Language. Pick the other language."
check "language: saved screen" "Tapping 'Change language' shows 'Language saved' with the close-and-reopen instructions — the app does NOT blink, reload, or change any string yet."
check "language: still whole" "Tap another tab. Every screen is still entirely in the OLD language and direction; nothing is half-mirrored."
say ""
say "Now close Mibo fully: swipe up and pause, then swipe Mibo away. Reopen."
check "language: applied on relaunch" "The whole app — strings, layout, header — is in the new language and direction."
check "language: no deep-link replay" "The app opens where it normally opens (Today), not on any screen a deep link or notification had opened earlier."
say ""
say "Hebrew tab bar (iPhone AND Android, phone language English, app in Hebrew):"
check "tabs: Today at the start" "In Hebrew, 'היום' is the RIGHTMOST tab and 'עוד' the leftmost, on both phones."
say "Then set the ANDROID phone itself to עברית (Settings → System → Languages)"
say "with the app still in Hebrew, and reopen Mibo:"
check "tabs: Android phone in Hebrew" "The order is the same — 'היום' rightmost. It has not flipped back to left-to-right."
say "And the IPHONE set to עברית (Settings → General → Language & Region), app in Hebrew:"
check "tabs: iPhone in Hebrew" "'היום' is still the rightmost tab, and the Today tab is the one open when Mibo starts."
check "tabs: Android back" "Android, app in Hebrew: open More, then Chores, then press back — it returns towards Today, never lands on More as the 'first' tab."
note "Set the phone language back afterwards. Repeat the whole stage the other way"
note "round (Hebrew → English) if there is time; the direction change is symmetric."
pause

# ── 3 ───────────────────────────────────────────────────────────────────
stage "Reinstall forgets kid mode"
say "Kid phone: join a child with a code. Confirm the kid Today screen shows."
say "Then delete Mibo from the phone and install it again from TestFlight /"
say "the Play internal track."
check "reinstall: welcome, not kid mode" "The reinstalled app opens on the welcome screen with the Parent / Kid choice — not on the child's Today."
check "reinstall: parent list updated" "On the parent phone, Children → that child → the old device is no longer listed as active (open the child fresh; it re-reads on mount)."
note "The first launch after install tells the server the old device left,"
note "then clears the role and session. Offline at that moment, the device"
note "list keeps the old entry until the parent revokes it — that is expected."
pause

# ── 4 ───────────────────────────────────────────────────────────────────
stage "OS push prompt and the evening digest"
say "Fresh household on parent phone A (or a phone that has never answered"
say "the push prompt for Mibo — delete and reinstall if it has)."
check "push: setup screen asks" "Finishing setup reaches the 'connected' screen, then the push explanation. 'Allow' raises the iOS/Android system prompt; allowing it goes to Today."
check "push: More → Evening summary" "On a phone that said 'Not now': More → Evening summary shows the same explanation, and 'Allow' raises the OS prompt from there."
check "push: kid explanation" "On the kid phone, the kid-side explanation screen's 'Allow' raises the OS prompt."
say ""
say "Then leave a chore done-but-unreviewed and wait for the household's"
say "digest time (More → Evening summary shows it). Phone locked, app closed."
check "push: digest arrives" "The evening digest arrives as a push, names the child by first name only, and tapping it opens Today."
pause

# ── 5 ───────────────────────────────────────────────────────────────────
stage "Rewards: ask, approve, decline"
say "Give the child enough coins (complete and approve a few chores)."
check "reward: request" "Kid phone → Shop → a reward the child can afford → the coins leave the balance at once, and the reward reads as waiting for a parent."
check "reward: approve" "Parent Today shows the request; Approve → the kid phone shows it granted on its next sync, the coins stay gone."
check "reward: decline" "Request another; Decline on the parent phone → the kid phone gets the coins back, the request is gone."
check "reward: cannot afford" "A reward priced above the balance cannot be requested from the kid phone."
pause

# ── 6 ───────────────────────────────────────────────────────────────────
stage "Photo proof, real camera"
say "Premium household; a chore with photo proof required."
check "photo: camera on done" "Tapping done on the chore opens the CAMERA (not the library), on the kid phone."
check "photo: waiting copy" "After the snap the chore reads as waiting for a parent, not done."
check "photo: parent sees it" "Parent Today shows the photo; Approve pays the coins."
check "photo: airplane mode" "Airplane mode on the kid phone, snap a proof: accepted locally. Network back on → it uploads and the parent sees it, without anyone tapping anything."
pause

# ── 7 ───────────────────────────────────────────────────────────────────
stage "Allowance"
check "allowance: screen" "Parent → Money tab renders the child's balance, the ledger, and the payout control correctly on the phone (both platforms)."
check "allowance: payout" "Record a payout → the child's balance drops by exactly that amount; the ledger shows the payout as its own line."
check "allowance: kid sees it" "Kid phone, after sync: the balance matches the parent's number."
pause

# ── 8 ───────────────────────────────────────────────────────────────────
stage "The next morning"
say "This one needs a night. Set up before bed:"
step "a daily chore left NOT done today on the kid phone;"
step "a child with a streak of at least one day (a chore done and approved yesterday and today)."
say "Come back after midnight household time (More shows the timezone)."
check "morning: missed chore" "The kid Today shows yesterday's chore as missed and today's as fresh — the missed one is not carried forward as still doable."
check "morning: streak reset" "The child whose chore was missed shows a streak of 0; a child who missed nothing keeps theirs."
check "morning: parent Today" "The parent's Today has rolled over to the new date with nothing from yesterday still awaiting approval unless it really is."
pause

# ── 9 ───────────────────────────────────────────────────────────────────
stage "Sign in with Apple and Google, production Clerk"
say "Signed-out parent phone, store build."
check "sign-in: Apple" "iPhone: 'Continue with Apple' completes and lands on create-household (new account) or Today (existing). Hide-my-email accounts work too."
check "sign-in: Google (iOS)" "iPhone: 'Continue with Google' completes the same way."
check "sign-in: Google (Android)" "Android: 'Continue with Google' completes the same way."
check "sign-in: email code" "Email code sign-in against the production instance delivers a real mail and signs in."
check "sign-in: survives relaunch" "Close and reopen: still signed in, no second prompt."
pause

# ── 10 ──────────────────────────────────────────────────────────────────
stage "Partner invite, two real accounts"
say "Parent A: More → Partner → invite parent B's real address."
check "partner: mail arrives" "Parent B receives the invitation mail."
check "partner: B joins" "Parent B signs in on the second phone (any provider) → lands in A's household, not on create-household."
note "This is the fix from accb9b2: the session token has no email claim on"
note "this Clerk instance, so the server asks Clerk for it (cached ten minutes)."
note "B signing in with a DIFFERENT address than the one invited must NOT join."
check "partner: sees premium" "If A's household is premium, B sees it premium too (entitlement is the household's, ADR-0016)."
check "partner: no setup routing" "B is not sent through guided setup; the Finish setup card on Today is the only nudge."
pause

# ── 11 ──────────────────────────────────────────────────────────────────
stage "Android, the whole pass"
say "Nothing above was ever run on Android before this build. Run the"
say "quickest complete loop on the Android phone as a KID device too:"
check "android: kid join" "Android phone joins as a Kid Device with a code and shows Today."
check "android: done + approve" "A chore done on Android reaches the parent and approval reaches Android."
check "android: exit by PIN" "Exit kid mode with the Parent PIN works; five wrong PINs cost a minute."
check "android: back button" "The hardware/gesture back never leaves kid mode."
check "android: Hebrew" "Hebrew on Android mirrors properly — numbers still read left to right, currency on the right side."
pause

# ── 12 ──────────────────────────────────────────────────────────────────
stage "Report"
if (( ${#RESULTS[@]} == 0 )); then
  warn "No results recorded — nothing to report."
  finish
  exit 0
fi
comment=$(printf '## TestFlight hand-test results\n\nRun via `scripts/testflight-hand-tests.sh` on %s.\n\n%s\n' \
  "$(date -u '+%Y-%m-%d %H:%M UTC')" "$(printf '%s\n' "${RESULTS[@]}")")
printf '\n%s\n\n' "$comment"
if [[ -n "$ISSUE" ]]; then
  if confirm "Post this to issue #$ISSUE?"; then
    if printf '%s' "$comment" | gh issue comment "$ISSUE" --body-file - >/dev/null 2>&1; then
      printf '  %s✓ posted%s to issue #%s\n' "$GREEN" "$RESET" "$ISSUE"
    else
      warn "gh could not post — copy the comment above onto the issue by hand."
      SKIPPED+=("the hand-test comment on issue #$ISSUE")
    fi
  else
    SKIPPED+=("the hand-test comment on issue #$ISSUE")
  fi
else
  note "No ISSUE set — copy the markdown above wherever the results belong."
fi
pause

finish
note "Every FAILED line is a fix before submission. 'Not yet run' lines are"
note "the next run's list: ISSUE=<n> scripts/testflight-hand-tests.sh."
printf '\n'
